### ISSUE TITLE
Click a link with the actual url

### ISSUE THREAD

**Issue by shadeglare** [lhorie/mithril.js#1001]
Is there a way to prevent page reloading when click a link with the actual url?

**Comment by barneycarroll** [comment]
Yes, you can use the click event's [`preventDefault`](https://developer.mozilla.org/en/docs/Web/API/Event/preventDefault) method to stop the link's native behaviour (navigating to the location described by the `href` attribute):

```Javascript 
m( 'a', {
  href    : '/elsewhere',
  onclick : function( e ){
    e.preventDefault()
  }
}, 'Blocked link' )
```

If you're using [Mithril routing](https://lhorie.github.io/mithril/routing.html) you will have difficulty running conditional logic to prevent Mithril's routing behaviour, because setting an `onclick` handler will override the routing handler Mithril binds to elements via `onclick` when you set `config : m.route`. If this is the case you will have to specify the routing behaviour explicitly in your own `onclick` handler, for example:

```Javascript 
m( 'a', {
  href    : '/elsewhere',
  onclick : function( e ){
    e.preventDefault()
    
    if( this.pathname != m.route() )
      m.route( this.pathname )
  }
}, 'Possibly blocked link' )
```

The example above assumes you're using `m.route.mode = 'pathname'` — it can be modified to suit other routing modes.

**Comment by shadeglare** [comment]
Is there a reason why mithril doesn't prevent page reloading for the same url by default?

**Comment by barneycarroll** [comment]
No. The question is "why would it?". This isn't default browser behaviour — the browser and Mithril are unopinionated about why a user may or may not want to reload a page they are already on.

If you have a site or app where the user encounters a link to the page they are already on, and they may try to follow that link and it is undesirable for them to trigger the normal behaviour of that link, then it's up to the site developer to work out how and why this situation is problematic (if it is) and how to go about redressing it if they think it's worth it.

I developed an application where users would be expected to navigate to the same route repeatedly for a variety of reasons: they might have changed some query parameters to display different information, or they might want to reinstate default state or get the latest data for a location that shows time-sensitive information. In this situation I found that since most of the elements on the page (the site furniture) wouldn't change, it was undesirable to have Mithril redraw the DOM from scratch, but it was desirable for controllers to execute to determine new conditions based on time, side effects, query parameters etc. You can prevent the total DOM redraw (internally referred to as an 'all' redraw strategy) by setting redraw strategy to 'diff' in the controller itself:

```Javascript 
var component = {
  controller : function(){
    m.redraw.strategy( 'diff' )
  },
  
  view : function( ctrl ){
    // Whatever 
  }
}
```

Depending on your concerns, something similar might be useful…?

**Comment by shadeglare** [comment]
Thanks for the answer. I'm developing a side project using mithril and just want to know its limitations. I also interested in the best practices. I used react/redux + react-router where routing has many advanced features but need something more light and less boilerplate for now and mithril is quite useful for this sort of things.

**Comment by dontwork** [comment]
Isn't the answer to this just to add config: m.route to the link in question

**Comment by isiahmeadows** [comment]
@dontwork 

- If this is about disabling a link, then it's adding an `onclick: function (e) { e.preventDefault() }`.
- If this is so the URL is used in a route, then it's adding a `config: m.route`.

I really can't figure out which of the two it is.

**Comment by isiahmeadows** [comment]
@shadeglare 

- If you need to load the same page as a new page, use a standard link.
- If you need to disable a link, use `onclick: function (e) { e.preventDefault() }`.
- If you need to route to a different route in the same page, you can use `m("a", {config: m.route})`.
- If you want to disable links to the current route, you can use this wrapper:

  ```js
  m.route = (function (old) {
    return function (el) {
      if (!(arguments.length >= 3 && el instanceof Element && old() === el.href)) {
        return old.apply(undefined, arguments)
      }
    }
  })(m.route)
  ```

The first two aren't Mithril-specific, BTW.
