### ISSUE TITLE
Invalidating images in the dom diffing

### ISSUE THREAD

**Issue by pieroxy** [lhorie/mithril.js#1004]
Hi,

I am using Mithril to display a product catalog. In the product list page, I have small blocks that display the product image along with some description. When the page charges for the first time, you see white blocks along with text, then images appear. 

When I change the sort order, I display different products. Mithril dom diffing does its job just fine and will reuse existing DOM to display the new data (including IMG tags where it will only change the SRC attribute). Hence, all descriptions will change instantly, but the old images still show until the new one starts to load which may take a while depending on the connection of the user.

This leads to a page where wrong pictures are shown.

I am struggling to find a way to "invalidate" those images when the diffing occurs. I could display a blank image, a spinning wheel, ... anything will do as long as those old images go away.

Of course, I could scan the whole DOM to invalidate those images by hand. I'd rather set an option into mithril to not reuse IMG objects in its diffing if the SRC differs.

I have no idea if that makes sense.

**Comment by barneycarroll** [comment]
Hi @pieroxy — can I just say thanks for lz-string — it proved invaluable in my last Mithril app! :)

Frankly I'm surprised that the browser would keep displaying the old image while it loads the new `src`. I would expect it to display nothing as soon as the src changes.

To my mind the simple solution is to force Mithril to create new DOM elements for each individual image. This can be achieved using the [`key`](https://lhorie.github.io/mithril/mithril.html#dealing-with-sorting-and-deleting-in-lists) property:

```javascript
m( 'img', {
  src : imgSrc,
  key : imgSrc 
} )
```

The source is the very thing that uniquely identifies the image, therefore there is no need to create a new reference for this.

This solution would be less desirable when you are expecting the same images to re-appear in the list in different position, since Mithril only recycles `key`ed elements if they keep a unique parent element between draws. In this case, it may be desirable to associate the key with the list item that contains the image:

```javascript
m( 'li.item', {
  key : imgSrc
},
  m( 'img', {
    src : imgSrc 
  } )
)
```

This presents its own problems, again depending on the dynamic behaviour of the list: whereas previously list items would be recycled aggressively, now they are destroyed and created depending on identity. So it would work very well for dynamically sorted list, not so well for a dynamically filtered list.

The complicated solution that doesn't force opinionated DOM recycling logic would be to use DOM scripting within the view via the [`config` method](https://lhorie.github.io/mithril/mithril.html#the-config-attribute):

```javascript
var loadingSrc = 'data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=='

m( 'img', {
  src    : imgSrc,
  config : function( element, initialised, state ){
    // If the current state hasn't been recorded 
    // (and it won't have the first time we get here)
    if( imgSrc != state.oldSrc ){
      // Load the new source programmatically
      var newImg = new Image( imgSrc )

      // If the source has not loaded synchronously
      if( !newImg.complete ){
        // Then display placeholder image in place
        element.src = loadingSrc

        // And display the desired source when it loads
        newImg.onload = function apply(){
          element.src = imgSrc
        }
      }

      // Record the current source for internal logic
      state.oldSrc = imgSrc
    }
  }
} )
```

**Comment by pieroxy** [comment]
lz-string is also useful to me ;-) You're welcome.

Back on topic, that looks fantastic. I'll test it soon and then close the ticket. Thanks a bunch.

**Comment by pieroxy** [comment]
Well, it works great. I guess it's another case of RTFM...

Thanks a bunch anyways :-)
