### ISSUE TITLE
speed improvement: cache regexp

### ISSUE THREAD

**Issue by adriengibrat** [lhorie/mithril.js#1008]
In Mithril code source regexp are never cached, they alway written as literals inside function body.
This could be optimised, in particular inside `parseTagAttrs`, which is called each time `m` is called.
See https://github.com/lhorie/mithril.js/blob/69f90deb64cc90401a2f172c274e5c78921c80d9/mithril.js#L87

Would you accept a PR ?

**Comment by adriengibrat** [comment]
BTW, the regexp in `routeUnobtrusive` at https://github.com/lhorie/mithril.js/blob/69f90deb64cc90401a2f172c274e5c78921c80d9/mithril.js#L1711
seems to target parent link tag, but will match any tag with the letter `a` (table, area, acronym, etc.)

smells like a little bug ...

**Comment by leeoniya** [comment]
Pretty sure all modern javascript JITs already cache immutable regexes (all that are defined using literal notation). Pulling regexes out of the functions for which they are made is very likely unnecessary and definitely reduces readability.

Have you measured the perf difference? Maybe it benefits older browsers with shittier JITs.

**Comment by tinchoz49** [comment]
I execute this code in chrome:
```js
function isFooBar(str) {
  return str.match(/Foo/)
}
console.time('1');isFooBar("Foo");console.timeEnd('1');
console.time('2');isFooBar("Bar");console.timeEnd('2');
```

and the result was:

VM173:5 1: 0.141ms
VM173:6 2: 0.017ms

So i think the javascript JITs already cache immutable regexes, at least the V8.

**Comment by adriengibrat** [comment]
@tinchoz49 you just pinpointed a match can takes more time than a rejection

The test should be more like http://jsperf.com/regex-caching-lp/2

Speed improvement may be small but given the number of times `m` and other functions can be called, they are a few place where this little optimization could be done.

And also, naming regexp is not easy, but alway improve readability.

**Comment by leeoniya** [comment]
I tried this optimization about an hour ago [1] in domvm and reverted it [2] since there was no measurable difference in real-world perf [3]. In both cases it's very far from being any sort of bottleneck in the lib. Feel free to flip between the two commits in the repo. I assume the same holds true for Mithril.

[1] https://github.com/leeoniya/domvm/commit/db874a046a8a8ee0c6b81f491490ed1337355149
[2] https://github.com/leeoniya/domvm/commit/de0dd1f40f1520e4b2788a1240e4281fe1b3d073
[3] http://leeoniya.github.io/domvm/test/bench/dbmonster/

**Comment by adriengibrat** [comment]
@leeoniya i'm sure you're right: most javascript engines caches litteral regexes

V8 may not need this kind of optimization, [unless this comment is true](https://github.com/less/less.js/issues/2501#issuecomment-78469030), any way let's agrgeed this is an optimization for "shittier" JS Engines

I just can't find any serious (multiple browsers, including IE & Edge) tests about this...

**Comment by lhorie** [comment]
Just tried and yes the difference is smaller than per-run variances, so pretty much negligible in Chrome.

The routeUnobtrusive test does look weird

**Comment by adriengibrat** [comment]
I've made a separate PR https://github.com/lhorie/mithril.js/pull/1009 about routeUnobtrusive.

Again, I know it's not an issue in Chrome, we all aggreed on this. 

The point is, is it on other browsers? Do we care about it?

**Comment by adriengibrat** [comment]
I've run some more tests with various browsers (mobile, IE11, etc) via crossbrowsertesting.com on http://jsperf.com/regex-caching-lp/2

They are just few versions of chrome where the difference is sensible (I guess, this may be explained by https://github.com/less/less.js/issues/2501#issuecomment-78469030)

A lot of mobile and "old" (i.e. not evergreen) browsers do optimize this, so i'm closing the issue.

**Comment by isiahmeadows** [comment]
@adriengibrat To be honest, if you really wanted to speed up the selector parsing, you shouldn't even be using regular expressions in the first place. The only reason why I haven't implemented that in core is because I'm concerned about size (it could literally add upwards of a kilobyte alone to the library), and with current tooling, it's not practical to split that out as two separate, complementary implementations. (I'm hoping I can do alternate implementations with @lhorie's rewrite, though.)
