### ISSUE TITLE
Allow to set key-attribute for `{subtree: 'retain'}`

### ISSUE THREAD

**Issue by StephanHoyer** [lhorie/mithril.js#1013]
I want to partially redraw a list if things. If I sometimes return `{subtree: 'retain'}` and sometimes not and the order of the list items is fluctuation I don't have expected behaviour.

I use `key`-attribute for the this list-elements but I can't use them for the ones I'm retaining. Would be great to have that though.

**Comment by barneycarroll** [comment]
Right, so the problem is that subtree retaining must work based on position — any `{subtree: 'retain'}` node (I call these 'retainers' for convenience) will skip the node, leaving whatever was rendered there last time. It's pretty clear to me that a single list whose items can be `key`ed nodes *or* retainers can face contradictory directives in how to manage DOM.

Rather than extend the language, might it not be better simply to retain the items contents? It's tough to make the assertion without having a test case, but I would think that deferring retaining logic to the items themselves (rather than their container) would be more adaptable to a general model, too — eg:

```javascript
const retainer = { subtree : 'retain' }

const List = {
  view : list =>
    list.map( item => 
      m( Item, Object.assign( { key : item.id }, item ) )
    )
)

const Item = {
  view : item => {
    // Simple condition for the sake of example
    {
      if( item.contents === ctrl.contents )
        return retainer

      ctrl.contents = item.contents
    }

    return m( /* whatever */ )
  }
}
```

**Comment by StephanHoyer** [comment]
Works like a charm. Thanks @barneycarroll
