### ISSUE TITLE
m.prop doesn't seem to work with native promises?

### ISSUE THREAD

**Issue by lord** [lhorie/mithril.js#1076]
I'm on the NPM version (`0.2.4 `), running Chrome 50.0.2661.102.

Here's some (I think?) failing code:

```js
t = m.prop(new Promise(function() {}))
t() // expected value is undefined, but instead returns the pending promise
```

It should be `undefined` (at least as far as I understand promises?) because it's a unresolved promise, which is [`undefined` until it's resolved](http://mithril.js.org/mithril.prop.html#third-party-promise-library-support). I think this may be because on [this check](https://github.com/lhorie/mithril.js/blob/42b21a59504248e127678afb4780b3ba4b126db0/mithril.js#L1341-L1342), the `Promise` object fails both the `isObject` and `isFunction` checks. It's not a function, so it fails that check, and `isObject` seems to check it's type against `[object Object]`, but at least this version of Chrome says it's an `[object Promise]` instead.

(Also, forgive me if I'm just misunderstanding, I've tried to read as many docs as I can before reporting.)

**Comment by isiahmeadows** [comment]
I've known about this for a while, but I've never been sure how it's best fixed. It's ill-defined, undocumented, and for this reason, I always use this method below:

```js
var t = m.prop()
promise.then(t)
t()
```

It's probably more of a design oversight, but I've been cautious to change it because I'm not sure how breaking it would be to fix `m.prop` to work like the above.

@lhorie Thoughts, WRT both 0.2.x and 1.x?

**Comment by lhorie** [comment]
Fixed promise absorption for native promises

**Comment by lord** [comment]
:+1: thanks!
