### ISSUE TITLE
Is promise finally gone?

### ISSUE THREAD

**Issue by leiyangyou** [lhorie/mithril.js#1139]
Seems like finally method on promises are gone, is there a reason for this?

**Comment by isiahmeadows** [comment]
@leiyangyou It appears to have been lost somewhere in 270b20a (diff quite large), and may not necessarily have been intentional. It was [this segment](https://github.com/lhorie/mithril.js/blob/c1912d272648a43d1fedc2cdc1565a0634ee4f53/mithril.js#L119-L129) that got dropped.

@lhorie I vaguely remember past discussion on this, maybe on Gitter, but it's too fuzzy for me to tell if it's my imagination or not. Would you be okay with me restoring that segment of code (it's a whopping 10 lines of code).

**Comment by lhorie** [comment]
I removed it because it isn't part of the spec. In the upcoming 1.0, promises are replaced by streams and there's no similar mechanism there

**Comment by isiahmeadows** [comment]
@lhorie I thought there was a reason for it, it's just I didn't remember. I don't believe it mentioned in the changelog or any other more permanent place (Gitter is logged, but the logs aren't easily accessible), so that probably didn't help.

**Comment by lhorie** [comment]
it was mentioned in the change log for v2.2-rc.1
