### ISSUE TITLE
Discussion: drop m.mount?

### ISSUE THREAD

**Issue by lhorie** [lhorie/mithril.js#1145]
As I was writing docs for `m.mount`, I realised I couldn't come up with a very convincing use case for it. And to boot, there were some comments in the chat yesterday from someone who was clearly confused trying to to use `m.route` and `m.mount` at the same time.

I'm wondering if `m.mount` is something that could be moved off to an optional module separated from the main bundle (or possibly even dropped altogether), given that you're far more likely to use `m.route` or `m.render`

What do you guys think? Do you use `m.mount`? How?

**Comment by bruce-one** [comment]
I was anticipating using `m.mount` to facilitate using Mithril components within an application that was otherwise using a different framework (hence I just wanted to sprinkle in small pieces of Mithril code, and still wanted to have auto redrawing for consistency with the way I normally use `m.route` (rather than using `m.render`)).

Alas, I went with that for a day or so, and then just moved to `m.render` as things got larger. _But_ I still think the concept of `m.mount` is useful (or else I probably wouldn't have used Mithril in this project -> I elected to use Mithril because I knew I could sprinkle it in without having framework opinions conflicting with the existing code).

Having said that... Is there a reason we couldn't conceptually replace `m.route` with `m.mount`, with optional routes? If that makes any sense? :-s (Might be a terrible idea :-p I'm still thinking it through... :-p ) Eg, for something fairly standard it's `m.newMount(document.body, '/', { '/': Something, '/asdf': SomethingElse })`; and for something that's just embedding a component within a larger non-Mithril project (or, just in a simple page) it's just `m.newMount(document.getElementById('nav'), Something)`.

(I think part of why I'm thinking of it like this is because "mounting" a Mithril application sounds/feels more correct in a sense; which I mention because what I'm thinking can probably/possibly be achieved via `m.render(document.getElementById('nav'), '/', { '/path...': Something })`, but that feels like it "makes less sense".)

I think `m.mount` has value (and am still expecting to use it for some simple cross page components (like nav and a header), whilst using `m.render` for a few complete pages, but not all of them).

I think I "like" `m.mount` more than `m.render` (because it acts more like `m.route`).

**Comment by barneycarroll** [comment]
> you're far more likely to use `m.route` or `m.render`

Not sure where you're getting this from. The only time I can ever remember hearing from people using `m.render` from the lists & chat is by accident, and my general impression was that most users weren't using Mithril for routing.

What I have seen, and I think may behind this urge to banish the API, is people getting confused because they think they need to use `m.mount` every time they want a nested invocation of a discretely referenced piece of code. People express it in different ways, but it boils down to people thinking `m.mount` is necessary for invoking a component, and they try to do things like this:

```
m( '.wrapper', {
  config : function( el, init ){
    if( !init )
      m.mount( el, NestedComponent )
  }
} )
```

In my opinion this boils down to a lack of familiarity with recursion and / or declarative structures and / or functional idioms in Javascript, which is very common. If you're used to writing imperative code and haven't really written anything that scales significantly, the terseness of nested component invocation *will* be a surprise. In fact, you often see people come in to the chatroom to express wonder or confusion at the ability for Mithril to transparently manage stateful components that were declared once. Coming from a jQuery background, you'd expect to have to write that code imperatively, in a function, and bind that function to an API yourself (bonus points for looking for a teardown API to match!). 

Maybe the docs could be better sequenced and written such that people don't end up making this mistake so often — perhaps introduce an example of declarative nested components sooner? — but I don't think the API itself is problematic: a non-routed, redrawing Mithril island is a perfectly legitimate thing. 'mounting' a component sounds like exactly the write verb to me.

Besides, it's certainly not worth writing off all the legitimate benefits of `m.mount` simply because somebody occasionally misuses it!

**Comment by lhorie** [comment]
> a non-routed, redrawing Mithril island is a perfectly legitimate thing

Aha, that's the convincing use case I was looking for. Thanks!
