### ISSUE TITLE
[rewrite] Components literals and RouteResolvers differ in subtle ways

### ISSUE THREAD

**Issue by pygy** [lhorie/mithril.js#1254]
As described by @porsager in the gitter chat, If you use a component where you used to use a RouteResolver with just a `render` hook, the semantics are different.

```JS
{
  '/foo' : {view() {return m(Layout, m(Foo)}},
  '/bar' : {view() {return m(Layout, m(Bar)}}
}
```
^^^ Going from `/foo` to `/bar` causes the Layout to be torn down and rebuilt.

```JS
{
  '/foo' : {onmatch(resolve){resolve()}, view() {return m(Layout, m(Foo)}},
  '/bar' : {onmatch(resolve){resolve()}, view() {return m(Layout, m(Bar)}}
}
```
^^^ Here the layout is diffed and likely preserved.

**Comment by lhorie** [comment]
hmm you're right, that's no fun

**Comment by pygy** [comment]
A solution would be to use a constructor and typecheck it with `instanceof`, rather than duck typing as is currently done. `'/foo': new RouteResolver({view:...})` or hid the `new` in a wrapper and have `'/foo': RouteResolver({view:...})`.

**Comment by barneycarroll** [comment]
I'm concerned that the API surface for routing is getting ever larger without any correlating practical opportunities for users compared to v0. Is the diff behaviour difference between `Component.view` & `RouteResolver.view` a feature or a bug? What does your code above propose to do @pygy?

**Comment by pygy** [comment]
The difference between `Component.view` and `RouteResolver.view` is IMO a feature, since it replaces `m.redraw.strategy` in a way that's cleaner than the original. I'd rather set the `redraw` mode when defining routes than when handling events.

re. API surface, it has already been introduced in the form of the RouteResolver type. We're currently cheating a bit because it is implicit and duck-typed, but the complexity is already there.

If we want a `view` on the `RouteResolver`, we can't tell apart a `RouteResolver` and a `Component` that only have a `view`, hence the suggestion of an explicit type.

Conceptually:

```JS
router.resolver = function(o){
  return Object.assign(new Resolver(), o)
}
function Resolver(){}
Resolver.protype = {
  onmatch(resolve) {resolve()},
  view(vnode) {return vnode}
}
```

**Comment by barneycarroll** [comment]
Forgive my quoting you in reverse order @pygy but I think we're going about this the wrong way, justifying the worth of an API in reverse order - based on what the current behaviour happens to be, rather than what is desirable in terms of usability.

> re. API surface, it has already been introduced in the form of the RouteResolver type. We're currently cheating a bit because it is implicit and duck-typed, but the complexity is already there.

When observing oversights in a new layer of complexity, I always prefer to try and redress or eliminate the original ambiguity rather than introducing more complexity to work around it. The fact that that complexity is already there should be challenged, not justified with more.

> I'd rather set the redraw mode when defining routes than when handling events.

Actually, event handlers unrelated to routing will still trigger redraws implicitly, so we have a new API to affect redraw strategy within those handlers which involves mutating the native event object. Preferring one over the other is not a coherent argument when both are necessary.

> The difference between `Component.view` and `RouteResolver.view` is IMO a feature, since it replaces `m.redraw.strategy` in a way that's cleaner than the original.

Bear with me and trust that I'm not being facetious when I say that 'cleaner' seems highly arbitrary here. This feature is not documented, it is an accidental difference between the 2. If we are to retro-actively document RouteResolvers to say that this is one of their core purposes, that is revisionist at best. Certainly it is not one of the core ideas justifying them in the first place. The fact that DOM is not recycled when ComponentB instance replaces ComponentC instance is not a feature, but an incidental aspect of the virtual DOM diffing algorithm. The idea that people would want to decide between RouteResolvers and Components as their route endpoints based on whether they want top level DOM recycling does not sound like a usable feature to me.

**Comment by lhorie** [comment]
> Is the diff behaviour difference between Component.view & RouteResolver.view a feature

It's supposed to be a feature. The semantics I'd like to have are these:

1) components are recreated if diffed against different components. Let's call this "component boundary semantics"
2) plain function calls within views don't necessarily recreate their returned subtree. Let's call this "view boundary semantics"
3) top level should have view boundary semantics
4) item 3) can be overridden by using a component

That takes care of pretty much all the use cases I can think of, with one exception: There should be a way of recreating a component that is diffed against itself. Currently this is the only thing I don't have a solution for

**Comment by pygy** [comment]
So, `render` is back... Closing.
