### ISSUE TITLE
m.request duplicate header values

### ISSUE THREAD

**Issue by pine3ree** [lhorie/mithril.js#1345]
### Description:

using this config in m.request
```js
var xhrConfig = function(xhr) {
    xhr.setRequestHeader("Content-Type", "application/json; charset=UTF-8");
};
```
works fine with GET requests, but ends in 

```
Content-Type: application/json; charset=UTF-8 application/json; charset=UTF-8
```
### Steps to Reproduce:

```js
var xhrConfig = function(xhr) {
    xhr.setRequestHeader("Content-Type", "application/json; charset=UTF-8");
};

m.request({
    url: '/my/url',
    method: 'POST',
   config: xhrConfig,
   data: { 'a': 1, 'b': 2 }
});
```

retrieving the request Content-Type via php $_SERVER['CONTENT_TYPE'] and the browser's developer tools

### Expected:

```
Content-Type: application/json; charset=UTF-8 
```

### Actual:

```
Content-Type: application/json; charset=UTF-8 application/json; charset=UTF-8
```

Anyone else experiencing it?

kind regards,
maks

**Comment by pine3ree** [comment]
closing as this is due to how XMLHttpRequest.setRequestHeader() works and because mithril is already setting Content-Type to application/json; charset=utf-8 when data is sent via a non GET method

**Comment by james-m-henderson** [comment]
What if somebody needs a different content type for their header?  It just gets concatenated with the default one if you set it the way it says in the docs.

I have an API I interact with that expects custom content types and will not accept the concatenated version.

This makes sense, since the spec for Content-Type precludes multiple types:

    media-type     = type "/" subtype *( ";" parameter )

https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.7

I'm not sure of any obvious way to actually replace the Content-Type with one that will be compatible.  This seems like a major problem, so I must be missing something.

In this JSFiddle (from another bug), I am observing the same concatenated content types:

http://jsfiddle.net/hm0745uw/

Copied from my debug panel:
    Content-Type:application/json; charset=UTF-8 application/x-www-form-urlencoded

So this leave my option to be using a different function than JSON.stringify as the serialization code to trick mithril into not automatically setting the content type.  That seems a bit hacky, especially if the content type I want is a subset of json, and the JSON.stringify serializer will work fine.

Mithril code in question:

    		if (options.serialize === JSON.stringify &&
    				options.data &&
    				options.method !== "GET") {
    			xhr.setRequestHeader("Content-Type",
    				"application/json; charset=utf-8")
    		}

What is the right way to fix this problem?

Thanks,

James

**Comment by isiahmeadows** [comment]
Is this using the `config: function (xhr) { ... }` property?

-----

Isiah Meadows
me@isiahmeadows.com

**Comment by ChiliConSql** [comment]
@james-m-henderson did you fix this? I am having the same issue.
