### ISSUE TITLE
[rewrite] List of reserved attribute names

### ISSUE THREAD

**Issue by simov** [lhorie/mithril.js#1350]
I just stumbled upon this:

```js
route.render = (vnode) => {
  return m(app.route.index, {tag: route.tag})
}
```

I should have known that the `tag` key is reserved, but still is it documented somewhere?

**Comment by pygy** [comment]
It can be deduced from the [vnode](https://github.com/lhorie/mithril.js/blob/e1883816c9dc2de69bef19a25d524795dc253001/docs/vnodes.md#vnode-types) and [hyperscript](https://github.com/lhorie/mithril.js/blob/e1883816c9dc2de69bef19a25d524795dc253001/docs/hyperscript.md#api) docs (since the `tag` property is what makes an object a vnode, and the `attributes` argument to `m` is optional).

That being said, it could be explicitly stated.

**Comment by simov** [comment]
:+1:
