### ISSUE TITLE
isInitialized for element in a different component

### ISSUE THREAD

**Issue by codeclown** [lhorie/mithril.js#1363]
### Description:

Mithril 0.2.5

If an element is similar and in the same DOM position, but comes from a different component, `isInitialized` in `config` is initially `true`.

### Steps to Reproduce:

[JSFiddle](https://jsfiddle.net/ce2om7xd/)

### Expected:

Because the component has not been initialized before, `isInitialized` for the new element should not be `true` initially. I am not sure if this is intended behaviour or not, but I am listing it here because it could be a bug.

**Comment by dwaltrip** [comment]
Hey there. This is happening because mithril doesn't have enough information to differentiate between the DOM structure returned by your two different components.

You can solve this by passing in a unique `key` property, which Mithril will use distinguish between the virtual elements returned by your components.

 [Here is an updated JSFiddle](https://jsfiddle.net/ce2om7xd/4/).

 In the [API docs](http://mithril.js.org/mithril.html) for the `m` function, there are a few sections that discuss the `key` parameter in more detail.

**Comment by codeclown** [comment]
Right, I was aware of `key`, but thought that an entirely different component would be enough to differentiate. Thanks for the updated fiddle!

**Comment by dwaltrip** [comment]
Hmm. You may have a decent argument there. I'm just a regular mithril user, and I'm not sure about the exact specifics of the diff engine.

However, I do know that for Mithril 1.0, which is in the works, they are doing a massive overhaul. The behavior for a finicky case like this might change with the new version of the library.

**Comment by isiahmeadows** [comment]
Here's a better explanation, and why it's working as intended:

When you change components, Mithril normally tears down the tree and
rebuilds the new one from scratch. This is both in 0.2 and the future 1.0.
And here's a reason why: imagine if you have a Bootstrap carousel and
navigation panel in a separate tabs inside a box. Suppose you start on the
carousel and let Bootstrap register its event handlers (it uses
`addEventListener`,  not `onevent`, so Mithril is never aware of it). If
you click on the navigation bar, you expect all the event listeners to not
exist in the new tree. You don't want seemingly random navigation buttons
to unexpectedly trigger carousel behaviors. The proper way to ensure this
is to completely tear down the old carousel before adding the navigation.
So you have to use components here, not only for better code structure, but
also the semantics of clearing the child when the component is removed.

Now, `key` and `context.retain` exist as escape hatches for this. It tells
the engine to reuse the element for where it's going, even if it otherwise
wouldn't be kept. There exist legitimate use cases for this, but you're
probably already aware of this (hence the issue).
