### ISSUE TITLE
Document piecemeal usage

### ISSUE THREAD

**Issue by isiahmeadows** [lhorie/mithril.js#1419]
Followup to #1132.

The pieces exist, which is nice. Now, they need documented. Currently, it takes a degree of inference to figure out that yes, individual render modules exist, and you have to read the source to figure out what is offered by each module. That isn't ideal for future users.

**Comment by lhorie** [comment]
Yep, it's on my todo list (but if you want to send a PR, that's cool too)

**Comment by barneycarroll** [comment]
A few suggestions:

* Recommend and imply throughout core documentation examples that users require the default index, ie `import m from 'mithril'
* Document streams as an optional extra which is to be treated as a separate lib / module which happens to be in the same mono-package
* Document ospec in a similar tone but give it further distance, as a kind of 'by the way'
* Document custom Mithril builds and piece-meal usage of core Mithril as an advanced topic (and this can really wait — certainly not a barrier to release IMO)

The foreboding elephant in the room is advice for plugin, extension, component authors. I think Mithril is easily small enough and sufficiently complete as a full DOM SPA framework in its bundled form that people should be strongly discouraged from publishing packages that depend upon piece-meal imports of bundled Mithril core's constituent modules. I would personally take a stance similar to @trueadm's WRT Inferno PR: this is highly specialised stuff for people with very specific, esoteric and rare requirements. Do not treat modular imports of Mithril core's constituent parts as a default under any circumstances, and do not promote packages which depend on them unless you are prepared to write your own explicit caveat-laden instructions for how your intended adopters should configure their own custom Mithril build WRT your esoteric package. AFAIC this is a recondite expert level feature which should be promoted to the average user under no circumstances. To be explicit about the dangers of this: modules depending on piece-meal Mithril module dependencies will not work with a consuming package that imports the bundled Mithril module. Having to support naive adopters coming in with total breakage because they thought this was an obviously great idea (shaving off bytes is an irrational imperative many many people will follow to great lengths as a prerogative before doing any kind of logical analysis — and let's be fair *many* relatively clever JS devs have deep delusions WRT dependency resolution because most of the time it's magic). I would hate that to become a common scenario, I think people will jump into it and get irritated to the point of rage-quit after usurping a lot of @isiahmeadows' support investment, and it will be unpleasant for everybody. At the risk of pressing a point too far: please let's focus on a holistic v1 release with documentation that makes no mention of the fact this is possible or desirable, and let's quietly work at making that documentation coherent as an orthogonal task.

**Comment by isiahmeadows** [comment]
@barneycarroll I'm not saying they should be *encouraged*. I'm just saying they should at least be *documented*, even if done in a way that it's "these parts are partially unstable and are not meant for general use, but they are here in case you need deeper hooks into Mithril's internals", and the latter is closer to what I had in mind, anyways.

**Comment by barneycarroll** [comment]
A couple of things:

What's the value proposition?

In other words, what is it that you propose to document, exactly? Nobody has supplied a use case for piece meal usage. It's an academic abstract. Tracing this conversation back thorough the months, it's fair to say @tivac was instrumental in elegantly splitting the API surfaces, so I was thinking he might be a good person to hit up for a use case that might provide a starting point for a perceived need to document. But in his own words:

> I'm not planning on using pieces of mithril, fwiw. Mithril is small enough that ignoring the bits we don't want is more cost effective than trying to customize it.

I would at least ask that you illustrate the feature you want documenting before you insist we document it. 

> …you have to read the source to figure out what is offered by each module. That isn't ideal for future users.

The ideal is illusory. The fact that Mithril is composed of multiple purpose-focussed modules is actually of principle value when reading the source. Any other value has yet to be proven. Without any identifiable need to use pieces of Mithril in isolation, there is no "feature" these future users are missing out on. If you want to try and compose your own Mithril build from the constituent parts, or *have* figured out a use for Mithril sub-module usage, then I would say reading the source is essential. The idea that it's somehow important to document the fact that Mithril is, under the hood, composed of discrete modules — to a person who finds it less than ideal to read source code — is frankly risible.

The general point here is that good documentation is hard, voluminous documentation is exponentially harder, and no documentation is better than bad documentation.

You commented recently that we have too many issues & not enough manpower. This is a footgun at worst and a trivial anecdote at best. It is in no way important in Mithril v1's roadmap.

**Comment by lhorie** [comment]
The use case is if someone wants to use m.render but not include m.request in the bundle, for example. I'd say that it's not a common use case, but that is still valid.

I agree modules that are reasonably usable as standalone things should be documented, but in an inconspicuous corner of the docs, and with a "only read this if you're an advanced user who really knows what you're doing" warning above it.

`var m = require("mithril")` is still recommended over anything else.

I'm just gonna go ahead and close this issue, since I'm well aware that it needs to be done
