### ISSUE TITLE
[rewrite] Document equality logic divergence in view diffing

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#1429]
@alexander-travov [took to Gitter to share his discovery](https://gitter.im/lhorie/mithril.js?at=58395d1073abd79c559aca59) that a vnode that is strictly identical to one in its place in the previous tree will skip diff, which is new behaviour introduced in v1.

The use case is a component that changes its own state, whose vnode is computed once and referenced in a higher order component view.

[In this fiddle], a component's view consists of 2 child Button vnodes: one computed at view time, the other pre-computed in global scope. Clicking either button will change its state, which reflects in the component's view, but the second button only has its initial lifecycle triggered, so the change is never persisted.

[This fiddle](https://jsfiddle.net/barney/hvvqdp7u/) shows functionally equivalent code for Mithril v0.2. Without the vnode equality check skipping diff for the second component's tree, we can mutate vnodes and still have the view persist.

This is implicit in the [components documented advice to avoid factories](https://github.com/lhorie/mithril.js/blob/rewrite/docs/components.md#avoid-component-factories), but the logic should be more explicit. This should be linked to in the migration docs, since people may be relying on skipping hyperscript and mutating trees in current Mithril apps.

**Comment by alexander-travov** [comment]
[The v1.0 fiddle ](https://jsfiddle.net/vscdyx0y/)

**Comment by isiahmeadows** [comment]
@lhorie Is this intentional, a bug, or undefined behavior?

**Comment by barneycarroll** [comment]
Like @alexander-travov says, we should also add a note to the migration docs before considering this closed.

**Comment by lhorie** [comment]
@barneycarroll you have a broken link in your first comment.

Frankly, the v0.2 behavior looks wrong. Mutating a vnode in the `old` side of a diff ought to yield undefined behavior since in that case the old vnode is no longer in sync with the DOM, and by definition it should be. The 0.2 behavior isn't documented either, so imho it falls flatly in undefined behavior territory.

Checking a vnode against itself as a `shouldComponentUpdate` mechanism of sorts is something @JAForbes had brought up before when exploring streams. It's not illegal to use it that way, but it certainly isn't an intended use case, and it's most definitely not idiomatic. I can't see any use case that justifies relying on 0.2 behavior. That 0.2 jsfiddle in OP could just as easily be accomplished using idiomatic usage, so it shouldn't have relied on the undocumented behavior.

**Comment by barneycarroll** [comment]
AFAIC I don't think this will be a gotcha for people authoring hyperscript directly — one kind of assumes that a node explicitly created outside of a view is intended to cache — but I've got a niggling fear this could cause problems for abstractions on top of Mithril, which may choose to skip hyperscript and write vnode directly / perform their own caching.

@tivac does this behaviour present problems for Mithril Objectify?

**Comment by tivac** [comment]
@barneycarroll Hah, given the vnode structure issues I ran into I've mostly given up on `mithril-objectify`. If anything I might try & release a 1.0 compatible version that simply parses selectors ahead of time.

The vnode structure isn't changing now, and as far as I'm aware it hasn't gotten any easier to know what bits need to go where, so I doubt `mithril-objectify` will ever be as complete as it was for 0.2

**Comment by barneycarroll** [comment]
OK — but either way the virtual nodes are returned in place in the views, right? No magic caching logic?

**Comment by tivac** [comment]
It's just precomputing the `m()` calls and replacing them with the object equivalents, no caching. I don't think it'd be tripped up by this behavior.

**Comment by JAForbes** [comment]
@barneycarroll @lhorie I'd really like it if we can keep this in (or something like it).  I've only explored it a bit because I've been stuck on 0.2x for so long, but I can imagine some really nice performant stream workflows with this behaviour.

Also its kind of illogical to cache something and then not expect it to be cached later, so the 1.0 behaviour seems pretty logical to me.

**Comment by barneycarroll** [comment]
@JAForbes what are you referring to here?

> I'd really like it if we can keep this in (or something like it).

**Comment by lhorie** [comment]
@barneycarroll he's talking about the 1.0 behavior where diffing a vnode against itself shortcuts diffing for it and its subtree

@JAForbes I don't think that behavior is going to change since it can't really get any more performant than what it does now
