### ISSUE TITLE
[rewrite] RouteResolver bugs

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#1455]
Several routing issues seem to be present on latest RC. 

This toy app attempts to demo mocked authentication logic.

https://jsbin.com/nuduba/edit?js,console,output

The default route is `/home`, which just has a render.
Next is `/profile`, which has render and onmatch. Onmatch checks to see if you're authenticated and redirects you to `/login` if you're not
`/login` renders a form which some delay after submission (no input validation) authenticates you and redirects you to where you were attempting to access (`/profile` or `/home`)
`/logout` has no render, just an onmatch which unauthenticates you and sends you back `/home`

Each render function returns a fragment whose first node is a heading, and whose second is the persistent Nav component, which displays either `/login` or `/logout` depending on authentication status

***

The bugs:

1. If you inspect the rendered links, `/home` and `/profile` are prefixed with `#!` as per the documentation. The third link, `/login` or `/logout`, is always in 'path' mode, ie without the hashbang. This doesn't seem to have any adverse effects (all links work as expected the first time round) but it's mysterious nonetheless.
2. When navigating to `/profile`, onmatch is always triggered, contrary to the documentation (I believe this is a good thing, mind)
3. But the `/profile` page's render function never triggers - it appears as though a RouteResolver can have either onmatch or render but not both
4. If I get routed to an onmatch route twice in a row, `m.route.get` returns nothing

**Comment by pygy** [comment]
1) Since the `href` changes, you must also set `onupdate` to  `m.route.link` (that's a potential gotcha, which we may want to document (adding `onupdate` to the description would be a good start).
2) Yes, I forgot to update the docs (I missed that sentence actually).
3) You forgot to call `resolve()` when authenticated to finalize the resolution.
4) You're using cdn.rawgit.com, which has probably cached an older version. I can't repro with the bare rawgit.com link which points to the current tip.

**Comment by barneycarroll** [comment]
Right on all counts - it's all fixed here: https://jsbin.com/nuduba/edit?html,js,console,output
