### ISSUE TITLE
[rewrite]What happens if an asynchronous function called while onremove()?

### ISSUE THREAD

**Issue by lugrugzo** [lhorie/mithril.js#1512]
### Description:

I'm asking this because I'm making HTTP request from a page and that request can be not finish when a user change the route. I know I can't cancel a `Promise`, so I'd like to know what happens in terms of memory-leak? 

I'd like to know if this approach is good, or Mithril is handling this situation for me?

``` js
oncreate: function () {   
    this.someHttpFunction() 
},

onremove: function () {
    console.log("onremove")
    this.removed = true
},

someHttpFunction: function() {
    
    var self = this
    
    Http.post(...).then(function(response){
        
        if(self.removed) {
            console.log("has response, but this component is not exists anymore") 
            return
        }
    })

}
```

**Comment by barneycarroll** [comment]
@lugrugzo as you say, Promises aren't cancellable, so there's no way of removing the internal stack allocation for that Promise's resolution. There's nothing Mithril can do about this - it's a language / engine level problem. In practice though your code looks logically safe, and since Javascript is garbage collected there is no practical danger in this - the allocation will disappear when the engine determines that it can no longer be referenced - this shouldn't be a problem :)

**Comment by lugrugzo** [comment]
Thank you for your explanation.

**Comment by pygy** [comment]
@barneycarroll Agreed for your general conclusion, but re. Promises not being cancellable, that's not true. [Promises can be canceled](https://gist.github.com/pygy/6290f78b078e22418821b07d8d63f111) but the Promise producer must explicitly support it and if any few do.

**Comment by barneycarroll** [comment]
@pygy I love that gist, it's really useful - I'd missed your closing comment about the cancellability hubub. The difference is simply between one of practical application concerns and low-level implementation logic - the discussion on the standards track gets lost in the popular discussion about how to implement the author-facing API on top of Promises, but AFAICT the salient stuff has to do with the ability to remove resolution stack frames on cancel. I suppose a good comparison is the fact it's impossible to polyfill WeakMaps / WeakSets in a meaningful way because the language-level contract must ensure low-level engine references are deallocated. To put it another way, there's no possible polyfill implementation that will effectively 'delete' all trace of the Promise's resolution chain from internal memory: in your implementation those chains and stacks will I assume be garbage collected at some point, but a 'proper' cancellability specification would detail a formal contract for when that construct can be scrapped from memory and the event queue be categorically told that that Promise essentially never existed.

**Comment by pygy** [comment]
I don't think the parallel with WeakMaps holds.

Until a Promise is resolved (either fulfilled or rejected),the event queue doesn't know it exists. Scheduling occurs when `fulfil` or `reject` (as in `new Promise((fulfil,reject) =>...)`) are called. The rest of the state is local to the promises and can be collected as soon as they are. That's why you can't reuse a single pending Promise to implement the scheme in the gist, as  each and every promise that adopted its state would keep a reference to it. Earlier versions of the gist were doing that and there were leaks. If no references to `fulfil` and `reject` and the Promise are kept, the Promise can be collected even it it hasn't been resolved.
