### ISSUE TITLE
Mithril sometimes doesn't redraw application

### ISSUE THREAD

**Issue by roman0x58** [lhorie/mithril.js#1546]
### Description:

Hi guys, I found some strange behaviour, when I use `Promise.all` with callback sometimes application doesn't redraw, then it redraw twice. 

### Steps to Reproduce:

I've created a jsfiddle example - https://jsfiddle.net/b61tqsa2/

**Comment by alexander-travov** [comment]
That's probably because several mithril autoredraws (two after each `m.request` and one after `onclick`) do not mix well with manual DOM changes `e.target.disabled=...`.

Adding `m.redraw()` helps https://jsfiddle.net/b61tqsa2/2/

As I understand there is a race between ending of:
1. onclick handler (after which happens autoredraw)
2. execution of Promise.all chain calls (which update the `value`). There is no autoredraw on `Promise.all` resolution (only after `m.request`).

If 1. with autoredraw comes first you end up with broken UI.

**Comment by alexander-travov** [comment]
Here is more idiomatic version https://jsfiddle.net/b61tqsa2/6/

**Comment by mglazer-cengage** [comment]
You can note by adding onupdate event to the button that it is being called 3 times, by adding m.redraw as noted above it is now called 4 times which seems to resolve your issue.

**Comment by roman0x58** [comment]
@alexander-travov oh, thanks, now I understand. I forgot some things about mithril autoredraw system. I thought after resolving Promise.all application should redraw, and I'm wrong...

**Comment by alexander-travov** [comment]
@roman0x58 BTW, if you don't need autoredraw after `m.request`s, you can add `{background: true}` and end up with only two redraws, but that can be premature optimization...

**Comment by roman0x58** [comment]
@alexander-travov yeah, I already found that option in the docs, thank you anyway
