### ISSUE TITLE
[1.0] Don't throw an uncaught m.request rejection

### ISSUE THREAD

**Issue by mindeavor** [lhorie/mithril.js#1556]
It's very useful to see uncaught errors in promise chains, but I don't think throwing them is a good idea. With the dev tools open, it triggers the js console and can be pretty annoying, especially since it doesn't give you a good stack trace.

I suggest using console.warn instead, which displays a nice message without interrupting the page.

**Edit:** I'm using `v1.0.0-rc.8`

**Comment by tivac** [comment]
Sorry, you're talking about https://github.com/lhorie/mithril.js/blob/rewrite/request/request.js#L86 and https://github.com/lhorie/mithril.js/blob/rewrite/request/request.js#L90 ?

I think that code is doing exactly the right thing. The promise can't resolve because there's an error so it rejects. I'm not sure how `console.warn` would make any sense there. Would the promise resolve with an error? Just never resolve or reject? None of the alternatives I can imagine make much sense in the context of a promise-returning API.

You can `m.request().then().catch(console.warn.bind(console))` if you really don't want to know about it.

**Comment by mindeavor** [comment]
Sorry, I should have looked at the codebase first. I'm definitely not saying it shouldn't reject. What I'm saying is, it throws an error that – if uncaught – causes chrome's dev tools to go into exception mode (the code stepper). Normal promises do not do that; if you have an unhandled reject, it silently swallows the error.

This line is the culprit: https://github.com/lhorie/mithril.js/blob/rewrite/request/request.js#L22 – it's the line that chrome dev tools opens up when there's an unhandled promise rejection.

**Comment by lhorie** [comment]
Unhandled promise rejections don't get silently swallowed. Chrome logs eagerly (and potentially incorrectly) and Firefox waits for a timeout before logging.

**Comment by mindeavor** [comment]
Woah, you're right. I must have been using an old version of chrome. Thanks!
