### ISSUE TITLE
Routes & keys issues

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#1578]
[In this bin](https://jsbin.com/hihiluy/edit?js,console,output), I'm trying to conditionally reinitialise a component in a RouteResolver based on data passed through `m.route.set`.

A couple of issues defy expectation:

1. Clicking either button causes 2 redraws in quick succession. Seeing as the event handler and the `route.set` call execute in the same tick, I would expect this to collapse to one redraw.
2. When Component 2 is passed a new key, it fails to reinitialise, triggering an update instead. I would expect the new key to signal the requirement for a new component, destroying the old and creating a new isntance.

**Comment by lhorie** [comment]
1) the first redraw is from the event (and would do nothing). The second redraw is the actual route change. We can't not redraw the first time since at that time we don't know what's going to happen next, and we can't not redraw the second time, since that would mean that the UI would not reflect the route change. You can set `e.redraw = false` to prevent the first redraw

2) The issue here is that you're mixing keyed and non-keyed vnodes. A fragment must have either all keyed or all non-keyed vnodes, but not both. If you wrap an array around Component2, it'll be re-initialized as expected.

I'm updating the docs re: 2)

**Comment by pygy** [comment]
@lhorie I know I'm insistent, but point 1 would not occur if autoredraw was fully async (unless the route resolution is delayed by the user, in that case two redraws is a good thing, one after `onmatch()` runs and one when the route is finally resolved).
