### ISSUE TITLE
Fix: Todo - Extended example

### ISSUE THREAD

**Issue by supermensa** [lhorie/mithril.js#1588]
JSFiddle for the [extended todo list](https://jsfiddle.net/glebcha/q7tvLxsa/)
fails because the external resource for moment.js  isn't from a https source.

Use this instead [cdnjs:moment.js](https://cdnjs.com/libraries/moment.js/)

**Comment by barneycarroll** [comment]
There are a few examples of snippets including explicit HTTP links, which also flummoxed me when I copied and pasted them into online playgrounds, since common wisdom these days is that we should have HTTPS everywhere. Should we have a general rule of omitting the protocol in snippets, such that the resource resolves to whatever protocol the host resource was served with?

The intro snippet would thus become:
```html 
<script src="//unpkg.com/mithril"></script>
```

The caveat is that these links would break if the user were serving them from the file system, but seeing as the documentation doesn't advocate that workflow, and refers both to jsfiddles and local server workflows, this would seem to be the pragmatic approach.

**Comment by barneycarroll** [comment]
@glebcha care to fix your jsFiddle? Moment's CDN serves HTTPS: https://momentjs.com/downloads/moment.js

**Comment by glebcha** [comment]
@barneycarroll sure, thanks for your remind!

**Comment by glebcha** [comment]
@supermensa @barneycarroll fixed with mithril 0.2.5. Will rewrite for upcoming 1.0.0 soon.

**Comment by isiahmeadows** [comment]
Closing, since this issue has not been updated in over a month, and typically, issues inactive for that long do not usually produce any action. If you feel something in Mithril needs added or changed, please file a new issue.
