### ISSUE TITLE
Error with jsx compiled object

### ISSUE THREAD

**Issue by oceanwap** [lhorie/mithril.js#1601]
I was earlier using Mithril v0.2.5 version with jsx compiler to compile html into jsx object like  
`<span aria-hidden="true">&times;</span>` to
`{tag: "span", attrs: {"aria-hidden":"true"}, children: ["&times;"]}`
Now I upgrading to Mithril v1.0.0 and using same jsx compiler and it's giving me error

Uncaught TypeError: Object prototype may only be an Object or null: undefined

for "`&times;`"
![image](https://cloud.githubusercontent.com/assets/823717/22728456/0c364764-ee04-11e6-921f-d618e7b08c10.png)

**Comment by pygy** [comment]
The children must be vnodes, not raw strings. vnodes that have a single string as children can also be optimized to use the `vnode.text` field.

You may be better served by Babel, using the pragma `@jsx m` then @tivac's [mopt](https://github.com/tivac/mopt) to turn the `m()` calls into `m.vnode` invocations. You'll probably get better perf by using trees generated by `m.vnode` rather than object literals because it makes it easier for JS engines to optimize the Mithril core renderer (see [here](http://stackoverflow.com/questions/37058643/why-do-monomorphic-and-polymorphic-matter-in-javascript) for a general description of monomorphic vs polymorphic code).

**Comment by oceanwap** [comment]
I was using grunt msx. Now suddenly official documentation has webpack configuration and I haven't used it yet. 

So updating everything at once is an issue for me. I thought I would update mithril first and then move to webpack.

**Comment by barneycarroll** [comment]
@oceanwap I think you should try using JSX instead of MSX. MSX hasn't been updated in 2 years, so it's not compatible with Mithril v1. You should be able to make JSX work with your Grunt setup, though. The advantage of MSX over JSX is that MSX introduced an extra performance benefit specific to Mithril vnodes - but Mithril v1 is so much faster, you probably won't see the difference. Like @pygy says, there are extra tools available if you want to get extra performance - but it sounds to me like you need to upgrade Mithril first and think about the rest later. What does your current Grunt setup look like?

By the way, jump on to [the chatroom](https://gitter.im/lhorie/mithril.js) if you want to talk about this live - we're available pretty much around the clock, and happy to help - it may be easier to talk back and forth rather than post comments on Github. :)

**Comment by oceanwap** [comment]
I was finally able to configure grunt for grunt-babel with transform-react-jsx . Earlier I was trying to do it with babelify which was not working for some reason I don't know.

I tried **mopts** but that is increasing the size while my priority right now is keeping my application small size(unless It gives me some significant performance inprovement) as it's a payment application so want it to be light weight for low network and slow mobile internet too. 

Find below my grunt config. [Gruntfile.txt](https://github.com/lhorie/mithril.js/files/762787/Gruntfile.txt)

My priorities are below.

1. Making application smallest possible for loading on slow mobile internet.
2. Making application compatible with most browsers.
3. Making application faster for slow low spec devices.

**Comment by isiahmeadows** [comment]
@oceanwap Here's my advice:

Specific to Mithril:

1. Do note that the baseline is IE 9 and Safari 7. The update dropped support for most of the archaic, horribly bug-ridden hacks for browsers, and requires full ES5 support. If you need an idea of what APIs this may use, check out [the DOM mock](https://github.com/lhorie/mithril.js/blob/next/test-utils/domMock.js) used for testing.
1. Use `@jsx m` instead of MSX, so it compiles down to the primary API.
1. Keep Mithril as a global, so you don't have to import it every time.
1. Create a Babel plugin to compress the nodes down some. You can make a few basic optimizations easily (Mithril caches these, anyways):
    - `m("div", null, ...children)` &rarr; `m("div", ...children)`
    - `m("div", [...children])` &rarr; `m("div", ...children)`
    - `m("div", {class: "foo"})` &rarr; `m("div.foo")`
    - `m("div", {id: "foo"})` &rarr; `m("div#foo")`
    - These will only make a slight hit to performance, since most low-spec devices (and their underpowered browsers) don't always benefit as drastically from the more advanced optimizations that most major, ultra-modern engines employ.
1. Do profile the crap out of your application, and implement `onbeforeupdate` accordingly to avoid unnecessary updates.

More general:

1. Most ES6 features are much slower and often more memory-intensive than their ES5 counterparts when transpiling, and there are actually ways to avoid the need. In my case:
    - [This particular module](https://github.com/isiahmeadows/thallium/blob/4a2d484390bcbcd4f0e50d09e9727972c7f45ac7/lib/methods.js) is the reason why I don't need classes (that even supports getters, setters, and mixins)
    - Callbacks make a surprisingly nice substitute for push-oriented generators (i.e. `yield value` &rarr; `send(value)`), even including delegation. Pull-oriented generators (i.e. `value = yield`) are rarely useful outside of async code in my experience, and Promises/Observables/etc. + functional programming solve much of that already.
    - I probably *should* write a blog post at some point detailing the idioms I use to avoid transpiling in Thallium (which is tested against PhantomJS 2 and its semi-ancient engine). My baseline is pure ES5.1 with a dependency on ES6-compatible promises, and browsers are supported if they exist, so that's why I have come up with various idioms to avoid transpiling.
1. Most other general practices regarding compatibility, performance, etc. still apply.

**Comment by isiahmeadows** [comment]
Closing, since this issue has not been updated in over a month, and typically, issues inactive for that long do not usually produce any action. If you feel something in Mithril needs added or changed, please file a new issue.
