### ISSUE TITLE
Add the topic "mithril" to Mithril's repositories

### ISSUE THREAD

**Issue by dbohdan** [lhorie/mithril.js#1615]
So that a [search for topic:mithril](https://github.com/search?utf8=%E2%9C%93&q=topic%3Amithril&type=Repositories&ref=searchresults) finds this repository and https://github.com/lhorie/mithril. Compare the top result for [topic:vue](https://github.com/search?utf8=%E2%9C%93&q=topic%3Avue&type=Repositories&ref=searchresults).

**Comment by isiahmeadows** [comment]
@dbohdan I'll note that the latter repo is specifically for the deployed website, and is otherwise unused and unuseful for anyone not actually working directly on it (basically Leo). This is really the only official Mithril repo apart from that - the rest are all community-maintained.

@lhorie Would you mind adding the `mithril` keyword to this repo?

**Comment by lhorie** [comment]
added
