### ISSUE TITLE
Doc: Why XHR instead of fetch

### ISSUE THREAD

**Issue by shibukawa** [lhorie/mithril.js#1648]
This section describes like this:

```
XMLHttpRequest provides hooks for progress listeners for long running requests (e.g. file uploads).
```

But fetch can support progress callback like this:

http://stackoverflow.com/questions/35711724/progress-indicators-for-fetch/

But still continuing using XHR is reasonable.

**Comment by shibukawa** [comment]
And a current version of Desktop Safari starts supporting fetch. Adding "Mobile" to Safari is good.

http://caniuse.com/#search=fetch

**Comment by tonyalaribe** [comment]
Yeah. I wonder about that. Though i like m.request api too. I think fetch works best in transpiled environments, and one strength of mithril is that it doesnt need to be transpiled.

**Comment by isiahmeadows** [comment]
The reason is because of the lower level features like progress events. Progress indicators, timeouts, and cancellation are the main reason why `fetch` isn't used under the hood, but once `fetch` actually reaches feature parity with `XMLHttpRequest` in all supported environments, `m.xhr` is likely to be deprecated more than anything else.

**Comment by tivac** [comment]
Closed since there's no action to take currently.

**Comment by qgustavor** [comment]
In case you update this section from the documentation add that [fetch is abortable](https://github.com/github/fetch#aborting-requests), but [only few browsers support it yet](https://caniuse.com/#feat=abortcontroller).
