### ISSUE TITLE
Model layer architeture doubts - Mithril 1.x

### ISSUE THREAD

**Issue by marciomunhoz** [lhorie/mithril.js#1716]
I'm creating a new application and would like to use Mithril 1.x, however, I have some doubts about the architecture.

Which of the following architectures would be most appropriate?

1- 
/model
	user.js
```javascript


	var model = {
		getUsers: function() {
			return m.request...
		}
	}
```
/views
	user.js
```javascript

	var state = {
		users: []
	}

	var user = {
		oninit: function(vnode) {
			model.getUsers().then(function(users){
				state.users = users
			})
		},
		view: function(vnode) {
			return m("div", [
				state.users.map(function(user){
					return m("p", user.name)
				})
			])
		}
	}
```
2-
/model
	user.js

```javascript
	var model = {
		users: [],
		getUsers: function() {
			return m.request().then(function(users) {
                              model.users = users
                        })
		}
	}
```
/views
	user.js
```javascript
	var user = {
		oninit: function(vnode) {
			model.getUsers()
		},
		view: function(vnode) {
			return m("div", [
				model.users.map(function(user){
					return m("p", user.name)
				})
			])
		}
	}
```

**Comment by CreaturesInUnitards** [comment]
I'm a fan of 2. I have several apps in production which all use a global state object coupled with stateless components.

**Comment by hugufc** [comment]
Considering you can reuse the already fetched users in others components I would stay with 2.

**Comment by lhorie** [comment]
I do 2 myself

**Comment by chebum** [comment]
I'd vote against both of them. In both 1 and 2  `model `is a singleton. While component being a singleton is OK in a lot of situations, making model a singleton will make tests much more complex. You will have to mock server requests. Some tests will require one response, others will require another. You will have to modify parts of model in every tests you will write. This will inevitable cause problems.

Why not to pass the model instance via `vnode.state`?

**Comment by leeoniya** [comment]
> While component being a singleton is OK in a lot of situations, making model a singleton will make tests much more complex

it really depends on what type of tests you want to write. a singleton model/state makes it very easy to write Acceptance Tests [1], which are really the critical tests for an app. Unit Tests [1] are better for a deliverable library or app internals that has explicit API contracts that cannot regress. A singleton model makes Unit testing more challenging since there's less purity/isolation and more side-effects. All arguments I encounter seem to miss this distinction. As always, the answer depends on what you're building and for whom.

[1] http://softwaretestingfundamentals.com/acceptance-testing/

**Comment by marciomunhoz** [comment]
@chebum thank you for the reply!
I could not understand very well, could you give me an example?

**Comment by chebum** [comment]
@leeoniya good point. Did you mean that overriding `model` is basically simpler when it's a singleton? Why not to make it a factory ("virtual" function) that creates a model and injects it into components. It will be almost as easy to override for end-to-end tests while still allow writing unit tests. What do you think?

**Comment by chebum** [comment]
@marciomunhoz for tests you will need to override the model like that:

```
model.getUsers = function() {
    return [1,2,3];  //Fake collection to prevent server request
}
```

There are several problems with this approach when writing unit tests:

- The fake collection we're returning here will change from test to test.
- `getUsers` method may have important side effects that we will need to replicate in test overloads.
- You may forget to restore the component state and thus break other tests in the suite. The same may happen due to the side effects of `getUsers` method.
- There may be several singleton components which will make mocks even harder to write.

**Comment by tivac** [comment]
@marciomunhoz did this help? Please close it out if this isn't generating useful discussion.

**Comment by marciomunhoz** [comment]
@tivac ok! thanks!
