### ISSUE TITLE
Proposal to eliminate Mithril's `this` magic

### ISSUE THREAD

**Issue by balupton** [lhorie/mithril.js#1722]
I did my first Mithril app earlier this week, and a few hours of it was a constant confusion of how exactly `this` worked, and then vetting to just never use it, and use the `vnode` argument instead.

For instance, given [this fiddle](https://jsfiddle.net/balupton/mw3yud8e/) I would expect the following to result in `this IS object component` for the alert and the render, however that is not the case.

``` javascript
const ObjectComponent = {
	assert () {
	return (this === ObjectComponent)
		? 'this IS object component'
		: 'this WAS NOT object component'	
	},
  
	view () {
		return m('div', this.assert())
	}
}

alert(ObjectComponent.assert())

m.render(document.getElementById('object-result'), ObjectComponent)
```

As I expected Mithril wouldn't have to do anythign with `this` on objects, that it would just call the object methods directly, passing over the state in the `vnode` argument, as that seems more intuitive and simpler.

I also expected the only things Mithril would do in regards to `this` would be that if Mithril received a ES6 class, it would instantiate it, such that `this` referred to the class instance - however it seems Mithril currently does not have support for ES6 classes.

As these expectations turned out to not hold true, it seems that mithril must do something like:

``` javascript
vnode.state = Object.assign({}, Component)
vnode.state.view.call(vnode.state, vnode)
```

Which is beyond strange to me when it can just do:

``` javascript
vnode.state = {}
Component.view(vnode)

// Or with class support, something like:
if ( typeof Component === 'function' && Component.toString().indexOf('class') === 0 ) {
  const component = new Component(vnode)
  component.view(vnode)
}
else {
  Component.view(vnode)
}
```

which has the benefits of:

- at least to me in my app, working as expected
- not needing to do anything more than it needs to, which has performance benefits
- seems to align with the functional stateless notion more, as state by default is just arguments, which seems as it should be, even according to resources like this https://github.com/rethinkjs/manifest that seem popular in the mithril world

That all said. What do the mithril people think? Can we do without the `this` magic? If not, why must it persist?

**Comment by pygy** [comment]
Your assumptions were wrong, but we're partly to blame for it.

This is intentional, [documented](https://github.com/lhorie/mithril.js/blob/683d85a9527dd98e81bc4b220ed5a75d26eb0f5d/docs/components.md#state) behavior (but some of the details changed during the v1 dev cycle and the [live docs](mithril.js.org/components.html#state) do not reflect the final code).

`this` in the `view` and hooks points to the `vnode.state`, which (for POJO component) prototypically inherits from the component itself.

We went from deep clone to shallow clone to prototypal inheritance, after quite a few discussions. Having `this` point to the component object itself is not uninteresting, but I don't think we'll change again at this point.

Support for ES6 classes is there in git HEAD, it will land with the  next release, as will the docs fixes.

If you need singleton data on your components, you can attach an object to the component:

```JS
const singleton = {
	assert () {
		return (this === singleton)
			? 'this IS the singleton'
			: 'this WAS NOT the singleton'
	}
  }
const ObjectComponent = {
	singleton,
	view () {
		return m('div', this.singleton.assert())
	}
}

alert(ObjectComponent.assert())

m.render(document.getElementById('object-result'), ObjectComponent)
```

But then you might as well keep it out of the component and just do `m('div', singleton.assert())`.

**Comment by spacejack** [comment]
👎 from me on this issue. While I'm sure `this` behaviour could be explained better, I personally have no problem with it.

Class components are in the next release so if you want to have `this` behave exactly like it does in a class you can use those.

Might not be a bad idea to adjust the docs so that the POJO examples all use vnode.state and class examples use `this`.

**Comment by isiahmeadows** [comment]
Yeah, this is only an issue because the docs haven't been caught up to what's in HEAD. But no, we're not changing `this` to the component itself.

**Comment by balupton** [comment]
Ok thanks for the details everyone!

For others wondering what is going on behind the scenes, this seems to be the relevant code:

https://github.com/lhorie/mithril.js/blob/683d85a9527dd98e81bc4b220ed5a75d26eb0f5d/render/render.js#L104-L124

Cheers!
