### ISSUE TITLE
Problem: diff engine defies expectation. Proposal: redraw strategy as a virtual node attribute

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#409]
I've mentioned before that it's a bit confusing when what the author conceives of as a completely distinct element is interpreted by the diff engine as a modification upon another. Here's a trivial example:

```javascript
return m( '.' + loading ? 'loading' : 'loaded', 'thing' );
```

If I were to describe the construction above, I'd say its a "thing with 1 of 2 classes, depending on a condition". And this is what the diff engine will interpret it as when loading changes.

```javascript
return loading ? m( '.loading', 'thing' ) : m( '.loaded', 'thing' );
```

But I'd describe the snippet above as "1 of 2 things, depending on a condition".

The difference is contrived in those examples. The real issue is when you have large nested structures, and the diff engine reaches a node which, like the cached node, is simply a div with perhaps a class or 2 and a `config` element. Consider the following scenario:

```javascript
function view(){
	return condition ? widget1 : widget2;
}

function widget1(){
	return m( '.sprawling', m( '.nested', m( '.structure' ), { config : pluginX } ) );
}

function widget2(){
	return m( '.something', m( '.completely', m( '.unrelated' ), { config : pluginY } ) );
}
```

`condition` starts as true, then an event switches it to false, and the view redraws. Now `pluginY` executes for the first time with `isInitialized` as `true`, and `pluginX`'s `context.onunload` never fired. This is completely unintuitive.

The standard approach to this problem is to assign unique IDs or keys on any element that could be confused for another, but that leaves you with the grim task of managing identities yourself — which becomes unmanageable at scale.

So my proposal is for a special `redraw` attribute which would introduce extra logic in the diff engine. The principle is to supersede the `subtree` directive by making the functional equivalent of the `m.redraw.strategy` flag available on a granular level from within the view — and then extending the flag with a `deep` value, which extends the diff logic to accommodate the problem under discussion.

* `none` would behave as `subtree: "retain"` currently does, and effectively aborts the build process for the node in question.
* `all` is the opposite and builds the subtree from scratch.
* `diff` isn't checked for: this is the current default behaviour, which compares tagName, attribute keys, and the values for `key` and `id`.
* `deep` goes some way further than current behaviour and attempts to compare attribute values as well.

What constitutes a reasonable 'deep' comparison (which I'm well aware is a perennial problem in JS programming). These are the credible options AFAIC:

1. Compare primitive values only. 
2. Compare all values by identity.
3. Compare all values by identity, except functions: compare these by `Function.prototype.toString`.

1 solves the example, and all my current expectations. I could fork this functionality relatively easily. 2 is more comprehensive and allows for differentiating elements that are statically identical but which have different `config` and event handlers. 3 is a Terrible Idea for the sake of example that uses non-standard behaviour in an attempt to cater for expectation shortfall in 2, when the function is not the exact same instance, but looks the same. This will still lead to expectation shortfall in all sorts of common scenarios.

What do we think?

**Comment by lhorie** [comment]
Hi Barney

Thanks for suggesting this, it's definitely something worth thinking about.

As it stands, I think the proposal wouldn't work because of the complexity in Mithril's current diffing heuristics (e.g. how should these flags be treated when m.redraw.strategy is "all" or "none"?).

Also, I don't see any obvious use cases for an `all` flag. If someone wanted that, they could conceivably even use element.innerHTML, but I'm having a very hard time thinking of a valid reason why someone would purposely use that as a rendering strategy.

And since the semantics for `none` and `diff` flags already exist, the only new thing would be the `deep` flag. If I understand correctly, the use case for this is to be able to recreate an element instead of diffing it based on some logic that is not covered by the current diff conditional (i.e. a `shouldComponentUpdate` of sorts, except that it affects the component lifecycle instead of whether diffing should happen for its children).

The only thing that is pertains to lifecycles is `config`, so I think this proposal essentially boils down to the need to have some way of resetting the isInitialized flag based on some arbitrary condition. Since config functions are already hooks to arbitrary computations, this is somewhat doable via something like this:

```javascript
var config = function(el, isInitialized, ctx) {
  if (shouldRecreate()) {
    ctx.onunload()
    isInitialized = false
  }
  //rest of config goes here
}
```

I fully admit this code is ugly as hell (and it doesn't even work in some cases), but I'm presenting it as food for thought in terms of what is the minimum amount of impact required to implement the idea needed in this proposal.

A proper solution would need to actually recreate the DOM element (in order to play well w/ libraries that don't provide `destroy` methods). This is something my snippet obviously doesn't handle correctly.

So theoretically, the simplest solution would be an attribute that takes a function, which is then called in the diff engine's if statement for whether an element should be recreated. The question would then be whether the function overrides the conditional altogether or not (presumably yes).

**Comment by barneycarroll** [comment]
@lhorie sorry for the delay in getting back to you. I've been thinking about this on and off and become slightly less convinced about it. But that's still plenty of conviction remaining ;)

> As it stands, I think the proposal wouldn't work because of the complexity in Mithril's current diffing heuristics (e.g. how should these flags be treated when m.redraw.strategy is "all" or "none"?).

I'd say these top level flags are overrides. Isn't that how `{ subtree }` currently behaves?

> Also, I don't see any obvious use cases for an all flag.

Neither do I, it would be an awful idea in practice. This is in part due to the dubious aim of maintain semantics upstream, but also of trying to rationalise how the logic would work compared to those.

> The only thing that is pertains to lifecycles is `config`

Good point. As with above, I can't think of any reason why somebody would want to continuously destroy and rebuild an element every redraw.

> I fully admit this code is ugly as hell

…But it offers a way to demonstrate proof of concept using current Mithril, rather than wading into core hackery without a clear outcome in mind. I'll try and get that working and take a step back to see if some kind of standardized function invoked by a new key is worthwhile. Good suggestion.

> … positional identity … which is essentially the core of the problem…

Mithril.Elements is ingenious, but the whole problem AFAIC is that positional and key-based identity are kludges that happen to work in the simplest situations – the notion of multiple instances of the same module at different locations in the DOM, without awareness of each-other, is the ultimate contender for when these methods break down. I maintain that the 'comprehensive diff' (ie, has the element changed at all or are we just passing over?) is a useful condition in and of itself (at least, it would solve all my problems).

> The other question is what would the function need to look like in application space

I'll get back to you :)

**Comment by nordfjord** [comment]
This would be immensely useful,
I remember having some troubles with including css files in m().

So having something like
```js
m( 'head', [
    m( 'link[rel=stylesheet][href=/styles/main.css]', { redraw: 'diff' } )
] );
```
to make sure the css file isn't reloaded on route change would in my opinion be much better than having to specify `m.redraw.strategy( 'diff' );` in all top level controllers.

furthermore having `m.redraw.strategy( 'diff' )` in all controllers adds complexity when it comes to config functions.

This is by no means preventing me from using mithril effectively, all my config functions are simply written using this pattern:

```js
var config = function( forceRedraw ) {
    return function( element, isInitialized ) {
        if ( !isInitialized || forceRedraw ) {
            // Do stuff
        }
    };
};
```

So I believe having a redraw strategy local to the element would by no means be a roadblock, but would rather force users to use a pattern such as the one above on only those elements which require a local redraw strategy.

**Comment by lhorie** [comment]
Update: there's some preliminary code to address this in the ctx-reuse-flag branch.

Usage:

```
m("div", {config: config})

function config(el, isInit, ctx) {
  ctx.reuse = true //don't recreate on route change if not needed
}
```

or when using w/ `strategy("diff")` in controller constructors:

```
m("div", {config: config})

function config(el, isInit, ctx) {
  ctx.reuse = false //recreate on route change
}
```

Misc: Currently flag is write-only (i.e. it does not report default state). Flag name sucks, suggestions welcome.

Status:

- tested: yes
- documented: no

**Comment by lhorie** [comment]
The flag is now called `retain`

**Comment by barneycarroll** [comment]
Brilliant stuff @lhorie! This feels just right to me — extending the `ctx` argument's build-loop  interactions is intuitive and simple. I *think* this should work with components whose controllers are initialised in the view loop too… Can you push the branch?

**Comment by uxnow** [comment]
:+1:
