### ISSUE TITLE
onunload doesn't fire on page refresh

### ISSUE THREAD

**Issue by kvanberendonck** [lhorie/mithril.js#416]
Would like to prevent the user from refreshing the page accidentally.

Also, would be nice to clean stuff up properly with the server over websockets and whatever.

**Comment by barneycarroll** [comment]
You're thinking of [document.beforeunload](https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload), which is a native API.

**Comment by kvanberendonck** [comment]
I know it's native. I have to use a mixture of both in my app at the moment, which is quite messy combined with #417 which I can't really hack around.

**Comment by StephanHoyer** [comment]
Can you give a fiddle to demonstrate the problem. I still don't get it.

**Comment by lhorie** [comment]
The problem with this proposal is that I can't attach things to onbeforeunload in older IEs without the risk of getting clobbered by 3rd party code, because those browsers only support the `onbeforeunload` property but not `addEventListener("beforeunload")`. Very lame.

On a related note, I've added support for unloading modules (see #420), so you'll be able to call this from your `onbeforeunload` handler

```javascript
onbeforeunload = function() {
  m.module(root, null)
}
```

To prevent unloads based on whether `preventDefault` was called in a controller's onunload, you'll be able to do:

```javascript
onbeforeunload = function() {
  if (!m.module(root, null)) {
    return "are you sure you want to leave?"
  }
}
```

The workaround until that change lands is to pass an empty module as the argument instead of `null`, e.g.

```javascript
m.module(root, {controller: function() {}, view: function() {}})
```

**Comment by kvanberendonck** [comment]
I don't think the third party clobbering is an issue.

You already do it here:
https://github.com/lhorie/mithril.js/blob/next/mithril.js#L596
