### ISSUE TITLE
window.location is wrong in controller constructor

### ISSUE THREAD

**Issue by kvanberendonck** [lhorie/mithril.js#418]
From the controller constructor you would have expected the page to change already.

If you access `window.location` from a controller constructor, it will be the parameters from the previous route not the current route.

**Comment by lhorie** [comment]
this is actually by design. There are two cases that break if location.href points to the new URL at controller constructor time:

1 - history.pushState requires the page title as one of its arguments, so calling it before rendering yields useless history titles (e.g. in ctrl+h in chrome)

2 - redirection also calls history.pushState, so calling it before rendering would yield two calls (which means the back button would break)

**Comment by kvanberendonck** [comment]
Thanks, I'll see if this works.
