### ISSUE TITLE
documentation: FP-friendly log

### ISSUE THREAD

**Issue by StreetStrider** [lhorie/mithril.js#459]
Hello, again.
http://lhorie.github.io/mithril/mithril.request.html

```javascript
//a FP-friendly console.log
var log = function(value) {
    console.log(value)
}

var users = m.request({method: "GET", url: "/user"})
    .then(log);
    .then(function(users) {
        //add one more user to the response
        return users.concat({name: "Jane"})
    })
```
This `log` does not look fp-friendly. If your promise component works as Promise/A+ it should not automatically pass value from one `then` to next. So, in last function `users` will be `undefined`. I don't test your code, maybe it does such automatical value pass-thru (or `then` works similar to event-emitter `on` and does not creates new promise), but if not, one additional `return` required.
```javascript
var log = function(value) {
    console.log(value)
    return value
}
```

**Comment by StreetStrider** [comment]
I'v looked through promises section in doc. It notes only diffrerence from A+ API:
> Mithril promises attempt to execute synchronously if possible.

So I think subject of this topic is certainly a bug.

**Comment by lhorie** [comment]
This is a documentation error.  `log` should return value. Thanks for catching. A fix will be pushed in the next released

**Comment by StreetStrider** [comment]
Thanks. Good job.

**Comment by barneycarroll** [comment]
Hey @lhorie, don't want to tread on your workflow toes but why don't you associate the relevant commits with the issues they fix?

There's a lot of recondite stuff in Mithril core that otherwise eager followers miss out on because issues are resolved  independently of the associated implementation details.

If your commit message matches  `fix(es|ed)?\s#\d` somewhere, github will link it up automatically.

**Comment by lhorie** [comment]
@barneycarroll I add the issue number in the commit when I remember to, but I forget to sometimes
