### ISSUE TITLE
using something like .settle for async components?

### ISSUE THREAD

**Issue by leeoniya** [lhorie/mithril.js#468]
Hi @lhorie,

I'm not too familiar with the way the redraw system works, but looking through 90843f6bdbaaadaec3192c07243aa85defe2a71a on the components branch made me wonder if the sub-component's view can return a promise, signaling to the parent(s) to defer rendering/redraw until all sub-components' views have `.settled()`. This would then only have a single redraw call, though it would obviously be delayed until all async is finished.

views that don't return a promise can be rendered immediately and promisified views can all be added to a single PromiseSet to be batched on `.settle()`, this would work as a aggregation/throttling mechanism and would result in a maximum of 2 redraws with low overhead and the benefits of 0-delay for synchronous views.

**Comment by barneycarroll** [comment]
@leeoniya good catch — and the idea of 'settling' is interesting. This is another aspect of the fact that controllers now execute in the redraw cycle, which also invalidates redraw strategy: effectively, sub-components cannot perform blocking XHR.

'm.sync' may provide the API hook you're looking for: my app has plenty of sub-components that often have independent asynchronous asynchronous data requirements, so by default all my XHRs have `background: true`, because I rarely want to freeze the whole UI just because one component is waiting on server data. But there are other times when a collection of components won't make sense until multiple requests have resolved, and I'll want to display a 'loading' state until it's all ready. In these cases the containing component is the one that needs to take responsibility for the requests, since it should be the one that decides it isn't 'ready' to draw until various responses are received. So I make the parent controller initiate the various XHRs: it then sets an internal 'ready' flag to `false`, and then calls `m.sync( this.xhr1, this.xhr2).then( () => this.ready = false;)`. The view then looks like this:

```Javascript 
if( !ctrl.ready ){
	return m( '', 'Loading...' );
}
else {
	return [
		component1( ctrl.xhr1 ),
		component2( ctrl.xhr2 )
	];
}
```

@lhorie I've been thinking about the amount of breaking changes components makes to the currently advocated workflow, and wonder if it might be worthwhile implementing an internal 'post-redraw hook'.  I figure caveats like this and redraw strategy are pretty big ones and it might be possible to salvage a few cases like this where the build step can be prevented and the last view output discarded if a controller invokes blocking XHR or changes strategy…

**Comment by lhorie** [comment]
@leeoniya the underlying problem is not so much of what technology is used to handle asynchrony, it's more of a chicken and egg problem: the diff engine can only know of the existence of a component if it evaluates the template tree, so the controller for a component always gets initialized after the first redraw has started.

What I have in place for now is that the component's view does only one redraw, as expected, but the rest redraws more times. I'm not sure that's something that can be optimized away without breaking edge cases, since it's technically possible to mutate the model from a component, and potentially affect the data displayed by upstream components (though, I grant, this is not likely to be a common scenario). If we decide that updating upstream data is not allowed, another alternative I've thought about it to add a variation of @bsuh's submodule proposal so that only components would be rendered after the async stuff completes. But again, this is a somewhat big change in the code.

**Comment by philtoms** [comment]
This is a good use case for an proof of concept that I have been working on just lately. Before the components branch was introduced, the redraw phase was cleanly divided into three sub phases: 

1. v-dom construction - via m.redraw, and then
2. dom/diff - via render/build
3. configs - via render

This, so my POC argument goes, provides a rational outcome that can be reasoned with and which does not require special async handling, or documenting of restricted coding patterns. In short, applications were easier to reason with before the components branch. 

Any inline component solution that works in the construction phase of the redraw will avoid the chicken and egg scenario. In any such solution, I believe the following amendment to m.render would support mid-redraw async scheduling:

```javascript
m.render = function(root, cell, forceRecreation) {
    ....
    // outstanding requests defer build phase
    if (pendingRequests === 0) {
      cellCache[id] = build(node, null, undefined, undefined, cell, cellCache[id], false, 0, null, undefined, configs);
      for (var i = 0, len = configs.length; i < len; i++) configs[i]()
    }
}
```

Moreover, the async behaviour conforms to [existing documentation](http://lhorie.github.io/mithril/mithril.computation.html). Calling m.request from a view or from an inline controller will work as expected.
