### ISSUE TITLE
Poor vdom benchmark results?

### ISSUE THREAD

**Issue by tivac** [lhorie/mithril.js#477]
Not necessarily an issue, Mithril's been plenty fast for us in production! More surprised at the results and curious to get @lhorie's thoughts.

http://vdom-benchmark.github.io/vdom-benchmark/

Mithril scores at or very near the bottom in every single benchmark for me in both FF & Chrome.

**Comment by asafyish** [comment]
Yeah, I was wondering about it too.

**Comment by barneycarroll** [comment]
I haven't been overly enthused with vdom-benchmark ever since I spent a day trying to install it and run my own tests. The rationale behind sandboxing the execution environment makes sense – Dart usage less so. Ultimately there's so much black magic involved I'm not sure how much to trust its results.

**Comment by qwitwa** [comment]
Isn't that link what http://lhorie.github.io/mithril-blog/thoughts-on-performance.html was about?

**Comment by tivac** [comment]
Looks like it probably is, the different URL for it threw off my dupe searching! 😞
