### ISSUE TITLE
Unexpected routing

### ISSUE THREAD

**Issue by jsguy** [lhorie/mithril.js#480]
Hi Leo,

I've found an interesting issue in mithril `m.route` seems to redirect to the default route if you override the anchor tag that has m.route as config, to demonstrate the issue:

http://codepen.io/anon/pen/ZYqGaB

Basically you get /one -> / -> /two

Override function:

```javascript
ctrl.onc = function(event) { 
  if(document.URL !== event.target.href) {
  	console.log('route to: '+event.target.href);
    m.route(event.target.href, {});
  }
  event.preventDefault();
  return false; // prevent default/propegation
};
```

And anchor:

```javascript
return m('a', {config: m.route, onclick: ctrl.onc, href: "/two"}, "click me to see root run, then get redirected to /two")
```

**Comment by barneycarroll** [comment]
When you use `config : m.route`, Mithril binds an event listener for the click. So as soon as `module1`'s view is rendered, Mithril attaches an event listener. However, this binding only happens when the element is rendered to the page: the `onclick` event you bound was already attached before the element was rendered. So when you click, your `onclick` handler resolves first. The full href is parsed by the router – `http://s.codepen.io/boomerang/1fabba7480ed69a13c8745a69e3816e11426074808651/index.html?/two` – and it can't find any matches, so it goes back to the default route. All this happens synchronously. *Then* when the synchronous stack has resolved, the event handler that Mithril bound internally as a result of `config : m.route` resolves – and that makes sense, so it goes to `/two`.

The problem is that you're trying to get automatic route handling, but then you're trying to override it. You have to go one way or the other, since otherwise the automatic handler has no idea you've decided to take care of things yourself. Either change the `href` in the view to represent the route outcome you want, or don't use `config : m.route`, and rely on logic in the `onclick` handler to cater for all outcomes.

**Comment by jsguy** [comment]
Ok, so from what you're saying, there are 2 options:

1. Change the href to be the full URL, ie: `document.location + "?/two"`
2. Or don't use config: m.route

Is that right?

**Comment by jsguy** [comment]
Ok, I see the problem - using the full path doesn't match, it MUST be "/two", and it will work fine - here is a 2nd example where I'm just using "/two":

http://codepen.io/anon/pen/Pwyjoo

It goes straight to "/two" :)

@barneycarroll Cheers for the info, it helped a lot :+1:

**Comment by barneycarroll** [comment]
@jsguy yeah ` config : m.route ` does some clever stuff — you need to either replicate that logic or just rely on `href` attribute being right in the virtual DOM (TBH looking at the original problem it's hard to work out what the user wanted in the first place).
