### ISSUE TITLE
Query string params not available

### ISSUE THREAD

**Issue by derekscruggs** [lhorie/mithril.js#485]
I'm working on an app that uses Google for auth. The callback url invoked by Google looks like this:

    http://example.com/?auth=google&code=some-long-random-string

I'm using `m.route.param('auth')` to check for these values, but Mithril is reporting them as undefined.

I checked `location.href` just to be sure and the url is correctly formatted.

**Comment by barneycarroll** [comment]
You should check that you've set `m.route.mode = 'pathname'` before invoking `m.route( rootElement, defaultRoute, routeMap )` — otherwise Mithril won't be aware that you're using 'literal' routing and will assume the whole query string is to be interpreted as a path to match whatever routes you set up in your route initialisation.

It's important to realise that Mithril's routing component is designed first and foremost to route your single page application — it isn't designed as a tool to help work with external API's URI endpoints (although you should be able to do that, incidentally, with the advice above).
