### ISSUE TITLE
m.request json array mapping problem

### ISSUE THREAD

**Issue by MattMcFarland** [lhorie/mithril.js#487]
So I created a dummy json file and am succesfully loading an exerntal json file.  The problem is, I can't get the model to map to the array in the json file properly.

This is a very small unit test (basically):

Javascript

```javascript
function log(value) {
    console.info(value);
    return value;
}

var User = function(data) {
    this.name = m.prop(data.collection.name);
    this.url = m.prop(data.collection.url);
}

User.list = function() {
    return m.request({method: "GET", url: "/mock/users.json", type: User}).then(log);
}

var users = User.list();

console.log(users());
```

JSON:
```json

{
    "collection":
        [
            {
                "name": "geoff",
                "url": "geoff.com"
            },
            {
                "name": "joe",
                "url": "hoe.com"
            }
        ]


}
```

the log function shows the file is loading, but i cant seem to create the list of users.  It seems to because of "collection" - but its invalid json to just start with an array.
Any ideas??

https://mithril-mattmcfarland.c9.io

**Comment by brainwork** [comment]
You are looking for the unwrap options in `m.request`, [read more about it here](http://lhorie.github.io/mithril/mithril.request.html#unwrapping-response-data)

Right now you are trying to map the `collection` property to a `User` object - which doesn't work. You want to map every item in `collection` to a `User` object and you can do so by using the `unwrapSuccess` method that should return `data.collection`. Then in your `User` model remove the `.collection` bits because they are not needed.

**Comment by MattMcFarland** [comment]
Thanks for your response.  I did see that bit about unwrap, but didnt make the connection!
