### ISSUE TITLE
What's up with Object.observe?

### ISSUE THREAD

**Issue by farzher** [lhorie/mithril.js#493]
Wouldn't this be really useful for mithril?

Anytime controller data changes or whatever, redraw.
It'd be as simple as that, and you'll also get less unnecessary redraws from user events and stuff.

Why aren't you using `Object.observe`? What's wrong with it?

**Comment by lhorie** [comment]
Well, there's nothing wrong with `Object.observe` per se, but support for it is still [extremely poor](http://caniuse.com/#feat=object-observe)

Mithril doesn't use it because it doesn't need it. Object.observe is more useful for templating engines that do dirty checking (like Angular) or that have observable-based infrastructure (like Ember, Knockout), but it turns out to not be that useful to virtual dom engines.

**Comment by farzher** [comment]
I didn't realize support was so bad! It was in chrome since like a year ago.

I don't like typing `m.redraw.strategy('none')` in most of my event handlers. `O.o` would be a nice fix for that

But the poor support makes it unusable anyway. Maybe it's something to consider later
