### ISSUE TITLE
Make .toJSON work recursively

### ISSUE THREAD

**Issue by calvinfroedge** [lhorie/mithril.js#495]
It would be nice to get properties to JSON recursively...example:

```
data = m.prop({
  foo: m.prop('bar')
})
```

Ideally this would become

`{foo: 'bar'}`

Unless I'm thinking about this wrong and there's no reason to have properties within properties? But I currently have logic in my code that looks like this:

`foo()[bar]()[baz] = m.prop('')`

Can I refactor that so only `foo` is a property and everything under it is just an object and retain bindings on change?

https://github.com/lhorie/mithril.js/blob/master/mithril.js#L388

**Comment by barneycarroll** [comment]
Isn't that exactly how it does work?

**Comment by calvinfroedge** [comment]
No, the result is:

`{foo: function}`

**Comment by lhorie** [comment]
I'm getting `{"foo": "bar"}`, as expected. Here's a [jsfiddle](http://jsfiddle.net/z7eaosjv/)

Do you mean you want it to be {foo: "bar"} when not calling JSON.stringify()?

To achieve that, one would forego `m.prop` within the object structure. In practice that just means that instead of `{foo: m.prop("bar")}`, you define the data structure as `{foo: "bar"}`, and instead of using `m.withAttr("value", someProp)` to do bindings, you'd do something like `m.withAttr("value", function(v) {obj.prop = v})`

**Comment by barneycarroll** [comment]
I was trying to remember why I ended up thinking this was a bad idea (I tried to do the same thing myself – nested `m.prop` structures – a while back, and almost immediately rejected it). The reason is that practically speaking, these things get difficult to manage. For instance, there is probably a dependency somewhere on `data().foo` – but by espousing `m.prop` at the top level there's implicitly a need to be able to easily set `data`. And the convenience of assigning `data` as a setter is kind of made redundant by the fact that whatever you set needs to have a `foo` that's also an `m.prop`. Basically any kind of use case convenience quickly ends up being compromised.

**Comment by calvinfroedge** [comment]
@lhorie Ah, got it. Yes, I was kind of expecting .toJSON to behave recursively. I didn't realize JSON.stringify and .toJSON interacted like that on JS objects. Just learned something!

@barneycarroll Great. I may need to refactor a bit, then = )

**Comment by lhorie** [comment]
Btw, there was a thread a while back suggesting overloading `valueOf`, so that you could do stuff like:

```javascript
var a = m.prop("foo")
console.log(a + "bar") // foobar
```

But the general conclusion was that this was too magical and gave the incorrect impression that doing things like `a = "baz"` would set the getter-setter (when in fact, it overwrites it, potentially breaking unrelated parts of the app)
