### ISSUE TITLE
View loses consistent state when using deferred

### ISSUE THREAD

**Issue by deflexor** [lhorie/mithril.js#508]
Here is example:

http://jsbin.com/wogifajiqe/1/

If you quickly click `a` then `b` checkboxes then `a` will stay checked while underlying value will be false.

**Comment by pygy** [comment]
Deferred is a red herring: ​commenting out ​the promise creation and
resolution still results in the same issue.

**Comment by lhorie** [comment]
In a nutshell, what's happening is that clicking `b` resets the value of `a` *before* a redraw happens.

Interacting with the DOM element itself affects its state independently of Mithril because that's just how checkboxes work, but since the model value gets reset before the redraw, the diff engine thinks it hasn't changed and doesn't update the DOM element with the correct value.

Checking the DOM to be sure that the checkbox value is correct would beat the point of using a virtual dom algorithm because the engine would have to check every single attribute to ensure synchronization.

The solution is to force a redraw after setting the value of `a` to true (either by calling `m.redraw` or using the `background` option in the case of a request)
