### ISSUE TITLE
enhancement: class attr should accept an object

### ISSUE THREAD

**Issue by farzher** [lhorie/mithril.js#545]
It should just loop the keys, and join them by a space if their value is truthy.

So then instead of this

```js
class: (function () {
	var classes = '';
	classes += task.completed() ? 'completed' : '';
	classes += task.editing() ? ' editing' : '';
	return classes;
})()
```

We can just write this

```js
class: {completed: task.completed(), editing: task.editing()}
```

**Comment by tobscure** [comment]
+1

**Comment by tivac** [comment]
The use of an IIFE to accomplish that is interesting.

```js
class: [
    task.completed() ? "completed" : "",
    task.editing() ? "editing" : ""
].join(" ")
```

Has been working out well for us. We use a helper to avoid all the ugly ternaries though, so it looks more like this:

```js
class: [
    optional(task.completed(), "completed"),
    optional(task.editing(), "editing")
].join(" ")
```

**Comment by tropperstyle** [comment]
Love it. I frequently do this pattern to try and keep my view tree lean, but this would drastically reduce boilerplate.

```javascript
view(c) {
  return m('div', { class: classList }, [
    ...
  ]);

  function classList() {
    var classes = [];
    if (c.completed()) { class.push('completed'); }
    if (c.editing()) { class.push('editing'); 
    return classes.join(' ');
  }
}
```

**Comment by nordfjord** [comment]
I have a pretty generic classList function I use:

```js
function classList( classes ) {
    if ( Array.isArray( classes ) ) {
        return classes.filter( function ( item ) {
            return !!item;
        } ).join( ' ' );
    }
    // Assume Object
    var keys = Object.keys( classes );

    return keys.filter( function ( key ) {
        return !!classes[ key ];
    } ).join( ' ' );
}


classList( [
	1 === 1 ? '1is1' : '',
	0.1 + 0.2 === 0.3 ? '0.3is0.3' : ''
] );
//-> "1is1"

classList( {
    '1is1': 1 === 1,
    '0.3is0.3': 0.1 + 0.2 === 0.3
} );
//-> "1is1"
```

feel free to use it

**Comment by farzher** [comment]
@nordfjord 
I've already extended mithril to have `class` accept an object.
I just think it's something that everyone should have in core

@tivac
The IIFE thing is weird, isn't it. It's from mithril's todomvc application.

**Comment by tropperstyle** [comment]
@farzher is there a gist or pull request somewhere?

**Comment by tobscure** [comment]
Furthering @farzher's original example, true values in the object could use the key as the class name, while truthy strings could be used as the class name. e.g.:

```javascript
class: {
  completed: task.completed(),
  editing: task.editing(),
  priority: task.priority() == 'high' ? 'high' : 'low'
  // equivalent to
  high: task.priority() == 'high',
  low: task.priority() != 'high'
}
```

**Comment by farzher** [comment]
@tropperstyle my code to extend the class is written in livescript and a little involved, I don't think it'll be too useful for anyone https://github.com/farzher/mithril-livescript-todomvc/blob/gh-pages/mithril-extended.js#L57

I don't have a pull request. I'm sure @lhorie could add this easily if he wanted to. (I'll make a pull request if you want though). Where do we make pull requests to? `next` or `components`?

@tobscure I think it's pretty standard to just use the `key` for the class, and show it for any truthy value. I'm actually right now using a string as a truthy value to show a class if the string isn't empty `class: {editing: item.oldTitle}`
Also I really don't like how the key name there is arbitrary and doesn't do anything.
Seems unnecessary. But that's an interesting idea.

**Comment by tobscure** [comment]
@farzher You could convert truthy values to boolean: `!!item.oldTitle`

But yeah good point, the key being arbitrary isn't ideal. Hmm, can you think of a more elegant way than this to include a dynamic class in the object?

```javascript
class: (function() {
  var classes = {
    completed: task.completed(),
    editing: task.editing()
  };
  classes[task.priority()] = true;
  return classes;
})()
```

**Comment by barneycarroll** [comment]
@tobscure there is none in ES5. ES6 allows dynamic property names in literals, but depending on your toolchain and browser support matrix, it's probably not a viable option:

```Javascript 
{
	completed: task.completed(),
	editing: task.editing(),
	[ task.priority() ] : true 
}
```

An easier way to do this might be using maps, or in ES5, 2-dimensional arrays:

```Javascript 
class : classFromMap( [
	[ 'completed', task.completed() ],
	[ 'editing', task.editing() ],
	[ task.priority(), true ]
] )

function classFromMap( map ){
	return map.reduce( function( array, pair ){
		if( pair[ 1 ] ) array.push( pair[ 0 ] )
		
		return array
	}, [] ).join( ' ' )
}
```

**Comment by tobscure** [comment]
@barneycarroll I'm using babel so the ES6 dynamic property names are perfect, thanks.

Didn't know about maps either - they seem pretty apt, although admittedly the syntax is a bit more cluttered.

**Comment by barneycarroll** [comment]
@tobscure Babel is incredible. The problem is when you start to treat ES6 as second nature and you end up writing what would be very terse little ES6 modules that end up compiling to 10 times the size in ES5 :/

Turns out that real Maps wouldn't help here: I always forget that Map keys have to be non-primitives, and ironically you can't map over Maps.

**Comment by StreetStrider** [comment]
It is good to know this issue is in discuss. I'm thinking about this helper since first day using mithril. Thanks to mithril composability this issue can be solved as helper and I've already solved it for my own. But I think this is such a basic thing and it definitely deserves to be in mithril's base.

**Comment by Naddiseo** [comment]
I'm :+1: for this idea, but I'm not sure what the best implementation would be.

Until now I've been using either the `Array#join` method, or my own (es6) function:

```javascript
function cx(...params) {
	let classes = {};
	params.filter(c => c && c.length > 0).forEach(c => classes[c] = 1);
	return Object.keys(classes).join(' ');
}
```

**Comment by nordfjord** [comment]
@Naddiseo 
I would suggest this:
Allow className to be a string, array or object

* if it's a string, leave it as is,
* if it's an array, truthy values will be joined together,
* if it's an object, keys represent classes, truthy values allow that key to be added to the classlist
  * if however the truthy value is a string that string should be added instead.

**Comment by StreetStrider** [comment]
@nordfjord, I have the similar ideas, I might add:
* if a **function**, it is invoked and return value is checked for **truthiness** and if true, converted to **string**,
* if **function** is met in **object**, it is invoked and **truthy** values are meant that **key** must be added.

**Comment by Naddiseo** [comment]
@nordfjord, by "best implementation" I meant most optimal. This is something that will have to be performed every redraw, so should be as fast as possible.

**Comment by tivac** [comment]
All of this sounds like the perfect thing to write a small utility function for. I don't think any of this should be in core.

**Comment by Naddiseo** [comment]
@tivac, to play devil's advocate, that "utility function" is used in pretty much every non-trivial mithril application. Isn't that enough reason to put it in core? 

Another way this could be done would be to integrate the logic with `el.classList`, only downside being that it's not supported on IE<10.

```javascript
var classes = node[classAttr];
if (type(classes) === OBJECT) {
    node.className = "";
    for (var cls in classes) {
        if (!!classes[cls]) node.classList.add(cls);
        // when IE fixes .toggle(), this can be used instead: node.classList.toggle(cls, !!classes[cls])
    }
} else if (type(classes) === ARRAY) {
    node.className = "";
    node.classList.add.call(node.classList, classes);
} else {
    node.className = classes
}
```

**Comment by tivac** [comment]
@Naddiseo Given the wide range of requested behavior & divergent opinions on formatting within this thread it seems like something that should be developed & refined external to mithril core. Since core just expects a string this is a trivial thing to build as a stand-alone function in user-land.

**Comment by mindeavor** [comment]
@lhorie has a post for [writing view extensions like this](http://lhorie.github.io/mithril-blog/extending-the-view-language.html), but it _would_ be nice to be able to do something like `m.viewHelpers.classes = function () {...}` built in, so we can have these nice things and not have to explicitly call functions everywhere.

**Comment by farzher** [comment]
@barneycarroll Whoa, variable object keys! That's the first thing I've seen ES6 do that livescript can't do better ;)

I think you guys are going a little too crazy with the class attribute haha o_O

@mindeavor That's a very cute idea. Although I'd call it `m.attr.class = function(value){ return newValue }`
That's maybe a little too limited though? I couldn't make a hook for any attribute matching  `x-*` for example. But maybe that's unnecessary and this covers everything most people would want to extend :+1:

**Comment by lhorie** [comment]
I was thinking of providing something along the lines of what @mindeavor mentioned so people can then put these features into plugins that they can share on npm.

I'm reluctant to add specific magic/sugar features to core because then we get a slippery slope of features, e.g. should core support dynamic classes in maps? arrays? recursive structures (`[cond1 ? "foo" : "bar", {baz: cond2}]`)? How about `config` sugar (e.g. #492, arrays for multi-configs), bi-directional bindings, on(swipe|pinch|gesture), etc, etc, etc.

With a plugin system, all of those features can live in a micro-utilities library similar to amp.js, so that core continues to merely mirror the underlying DOM API, and sugar is provided exclusively by libraries

**Comment by tivac** [comment]
@lhorie what'd be the hook that invokes the registered plugin(s)? I'm not against the idea but I don't find bare functions particularly onerous and they have the advantage of only running when you tell them to.

**Comment by farzher** [comment]
@tivac Is this what you're asking about? https://github.com/lhorie/mithril.js/blob/next/mithril.js#L63
I assume we'd basically add this

    if (plugins[attrName]) attrValue = plugins[attrName](attrValue)

^ pseudo-code
(is that a performance issue?)

**Comment by tivac** [comment]
@Farzher That only allows a single plugin per attribute, with later plugins stomping newer plugins. There's ways to solve that, but all of them lead to more code.

Since @lhorie mentioned it I went & looked at what amp.js plugins actually look like: http://amp.ampersandjs.com/

It looks like they're all just functions and you decide what to do with it? That sounds great.

**Comment by farzher** [comment]
@tivac yeah... idk how you'd deal with that. If you have two plugins using the same attr, you'll have conflict issues

You prefer just `{class: toClass({whatever: true})}`?
I don't like the verbosity. That's pretty ugly. But that is more flexible (and requires no core changes, that obviously already works)

I want custom attributes, like `init`, or `onenter`, or automatic 2-way databinding. Which I've already added, but the process is currently  a bit messy

**Comment by tivac** [comment]
@farzher I like the clarity. I either know *exactly* what `{class: toClass({whatever: true})}` does, or I can figure it out by quickly determining what `toClass()` does.

As you mentioned it also helps keep mithril's core lighter, which is always a win in my book.

**Comment by lhorie** [comment]
@tivac I was thinking either something like @barneycarroll's [m.attrs](https://gist.github.com/barneycarroll/54961d3c5040d1465bc1#file-mithril-attrs-js), or something more generic like a `m = spy(m, function(vdom) {return modifiedVdom})`

**Comment by tropperstyle** [comment]
I like @barneycarroll's m.attrs implementation as it is similar in nature to jQuery.fn.customFeature. It seems like the mithril vdom function should have an explicit hook for custom attributes, then use that hook for existing special treatment of the "class" attribute. This seems like the best middle ground. It keeps mithril core lean and prevents excessive utility functions for very common behavior. I don't like `m = spy(m, func..)` because it reminds me of the early days when Rails encouraged everyone to extend functionality with alias_method_chain. It feels more like a dirty monkey patch than a clean extension.

**Comment by barneycarroll** [comment]
A few reasons I like `m.attrs` more than the spy idea:
1. Like @tropperstyle says, the spy pattern is basically an open-ended monkey patch. Anything could be going on there — and debugging potential third party plugin interactions with Mithril is going to be awful.
2. m.attr gives a specific opt-in contract. Dubious third party plugins have a limited scope because you have to invoke them explicitly, rather than relying on them to decide if and how they want to come into play.
3. You can see code making use of m.attr at a glance. If I see `bidi` or `classList` in a template, I'll think either "that shouldn't work" or "I know what that does". Basically you can see dependencies in the client code.
4. As a follow through from this, you get some kind of standard for plugin APIs, and you know where to look if something's not behaving as you expect. With spies, you'd have to look everywhere and debug the whole stack.
5. Limited computational expense: with m.attr you know there's a loop through a map of plugins, and if no matches are found that's it. With spy you have to run a function for each plugin you have installed every time you call m. m is ultra performant right now but it could easily become orders of magnitude more expensive if you want to occasionally invoke cool functionality via spies. With m.attrs I can risk installing very expensive or logically flaky plugins (that doesn't mean crap BTW — select2 is best in class at what it does, even if it's highly unperformant and flaky at scale) if I know when and where I'm invoking them — I can easily limit the scope of my investment.

**Comment by williscool** [comment]
"the spy pattern is basically an open-ended monkey patch' - @barneycarroll  

brilliant

**Comment by farzher** [comment]
@barneycarroll 

> m.attr gives a specific opt-in contract. Dubious third party plugins have a limited scope because you have to invoke them explicitly

Isn't that not actually true though because plugins would bind to `m.attr` themselves, and all you'd do is include them after mithil?

```
<script src="mithril.js"></script>
<script src="mithril-class.js"></script>
```

Or were you thinking plugins should work like
```
m.attr.class = require('mithril-class') // (or however ES6 imports work)
```

**Comment by barneycarroll** [comment]
@farzher that's an interesting point — dependency injection in Javascript is a controversial subject and largely depends on the end user's wider environment (as you say, ES6 — and CommonJS / Node, which is the syntax you used — have their own attitudes).

In a way, you could argue m.attr is regressive in that it encourages the jQuery attitude to namespace whereby there's a contract for plugins to hook in as properties of an existing object. But that's an advantage, because you can do dependency injection however you want it (@lhorie 's spy idea is equally ambivalent on this point).

In the jsbin I posted (and the gist), there's no domain-specific dependency mechanism. It relies on Mithril being exposed as `m` and it 'parasites' it. As such, you get to avoid the minefield of dependency injection best practice by saying "give me Mithril as m, and I will hook on to it". You could be just stacking scripts in an HTML document, you could be using RequireJS or SystemJS or Browserify — whatever. That's your preference.

I would stress that if m.attr were to be a plugin and not an addition to core (which is what I'm proposing), I would package it via UMD and would definitely have Mithril as an injected dependency (as opposed to hard-coded). The point is to add a method to the existing Mithril.

You're right in saying that any given plugin could be doing anything anyway, but that's true of anything: Witness evil.js — if you blindly include Javascript in your app it could be doing anything (even overriding native XHR! :0).

Asking authors and users to package and invoke m.attr plugins as discrete objects to be integrated according to their setup is too much to ask and not that useful AFAIC.

**Comment by lhorie** [comment]
spy is more or less the same pattern that people have been doing to extend mithril so far.

The biggest pro is that it's very flexible: you can create custom behavior based on the tag name or the presence of a specific CSS class (or even a combination of conditions). For example, you can swap out `m("input[type=datetime-local]")` with a component conditionally based on browser support.

The drawback is that without a canonical behavior identifier, it's not as easy to find where a custom behavior comes from.

The pros for m.attrs are what people have already said: it's cleaner and more intuitive. The drawback is that it's not quite as flexible.

---

@barneycarroll WRT making `m.attr` a plugin, I think people are generally averse to the idea of using a plugin in order to use another, and there's also a matter of setting a precedence in terms of what is an acceptable way to extend core, i.e. given m.attr itself would use monkeypatching to extend m, what's stopping someone else from thinking "ew, I need a plugin to use `bidi` ?!, I'll just roll my own... by monkeypatching m like this guy". Not saying that it shouldn't be a plugin, just that it's prone to [this](https://xkcd.com/927/)

---

One issue that neither idea is directly addressing is name collisions. Say someone were to write a big jQueryUI-like library that defines a `onswipe`, and you want to include another `onswipe` library that does swipes better. Then the two clash and things blow up.

A poor man's solution might be to namespace (a la Angular's ng-* / ui-* / etc). Another might be to come up with an API that leaves registration open ended (e.g. @farzher's idea of `m.attrs.foo = require("foo")`)

**Comment by barneycarroll** [comment]
@lhorie to be clear, I'm proposing this as an addition to core. Right now, Mithril is a black box. You have to monkey-patch if you want to extend it's behaviour. If this were in core, it wouldn't need to monkey patch, and nobody else would need to either.

WRT collisions I think we can get the best of both worlds by setting a convention for plugins to auto-register to their key of choice, but also expose the transformation function itself so the user can rebind to their key of choice if so desired.

So here's a naive bidi custom attribute (I've tweaked m.attr source to return the transformation function). I think this reads nicely. If this is all it takes to write a Mithril plugin, awesome.

```javascript
import m from 'mithril'

export default m.attr( 'bidi', function bidi( node, prop ){
  node.value   = prop()
  node.oninput = m.withAttr( 'value', prop )
} )
```

In my app:

```javascript
import m    from 'mithril'
import bidi from 'm.attr.bidi'

let value = m.prop( '' )

m.module( document.body, {
	view : ctrl => m( 'input', {
		bidi        : value,
		placeholder : 'Write here please'
	} )
} )
```

Then later on I realise I need dropdowns, checkboxes, etc. I slowly remember how awful the disparity in DOM form element APIs is. I decide I need a more fully-featured bidi plugin. After searching about, I find this one: it handles dropdowns and select boxes. Awesome.

But for some reason I want both plugins. Maybe this other bidi plugin is more powerful but also has some edge cases where I don't want to use it, or maybe I have a pathological problem with premature optimisation, and believe that it's not worth invoking the bigger bidi plugin when I know I just want text input binding. In any case, I want both. It's my call. My app now looks like this:

```javascript
import m     from 'mithril'
// These plugins are registered with the names 'mithril-bidi' && 'm.attr.bidi' on NPM / CommonJS / Bower, but internally both will try to register to the 'bidi' custom attribute
import bidi1 from 'm.attr.bidi'
// I'm calling them bidi2 and bidi1
import bidi2 from 'mithril-bidi'

// ...but that's just to get 2 distinct variable references.
// In my application code, I want to reference them like this:
m.attr( 'bidi',  bidi1 )
m.attr( 'bidi2', bidi2 )

let name      = m.prop( '' )
let country   = m.prop( 'UK' )
let countries = [ /* ... */ ]

m.module( document.body, {
	view : ctrl => [
		m( 'input', {
			bidi        : name,
			placeholder : 'Name please'
		} ),
		m( 'select', {
			// I don't care if you think this is stupid,
			// I should still be able to do it. And I can.
			bidi2 : country,
		},
			countries.map( country => m( 'li', country ) ) 
		)
	]
} )
```

**Comment by littlehaker** [comment]
We can use [classnames](https://github.com/JedWatson/classnames) to turn object to string for class.

eg: `{class: classnames('foo', {bar: isBar()})}`

**Comment by StreetStrider** [comment]
@littlehaker, great stuff.

**Comment by impinball** [comment]
@littlehaker I don't exactly trust the maintainer, considering [these](https://github.com/JedWatson/classnames/pull/48#issuecomment-144057565) [three](https://github.com/JedWatson/classnames/pull/47#issuecomment-144062342) [comments](https://github.com/JedWatson/classnames/pull/36#issuecomment-103764348) on PRs from someone *with* commit access. A TL;DR for each, not in order:

1. A clear speedup for a trivial module, specifically using arrays instead of a built string, isn't enough to convince him it's worth merging. Merging that would be a common sense move. (I would merge any PR that passes tests and brings performance increases, even in cold paths.)
2. The use case for a named AMD module for a library isn't clear, even though it should be. Any AMD library should be named, especially if it can be loaded directly on the client. It's common sense.
3. `object.hasOwnProperty(prop)` > `{}.hasOwnProperty.call(object, prop)` somehow...Not smart if someone uses `hasOwnProperty` as a class name. Even worse if user input isn't sanitized first, and parsed into a class name. Oops.

Better to use [classSet](https://npm.im/classset) or similar. At least that one is written intelligently, without trying to hold on to anti-patterns.

**Comment by dcousens** [comment]
Hi @impinball!

It would have been better to address these comments on the PR's themselves rather than referencing it here.  In any case:

> A clear speedup for a trivial module, specifically using arrays instead of a built string, isn't enough to convince him it's worth merging. Merging that would be a common sense move. (I would merge any PR that passes tests and brings performance increases, even in cold paths.)

A clear speed up needs benchmarks.
I still have no idea if that 'speed up' works it all, and its likely V8 might just opimize this query entirely.
We have no way of telling, so I'm sorry but I put the burden of truth on the PR author to provide **a reason** to change a module that is downloaded ~13000 times a day.

> The use case for a named AMD module for a library isn't clear, even though it should be. Any AMD library should be named, especially if it can be loaded directly on the client. It's common sense.

I have no experience with AMD,  so,  I was hoping you could explain why it is necessary.
I don't personally want to break anything that is used by people who use that syntax, so a blank PR without any description isn't going to automatically get a merge from me,  sorry.

**Comment by impinball** [comment]
@dcousens 

1. I understand your sentiment, but a speedup anywhere is a speedup IMHO. And the common cases are string arguments.
2. I'm not that worried about it.
3. hasOwnProperty fix: #49

**Comment by JedWatson** [comment]
I'm going to jump in here, although this is not my favourite way to enter a thread:

> I don't exactly trust the maintainer

Not sure if you've looked at my profile but I put a serious amount of time into OSS and work hard to make sure people _can_ trust packages I author. `classnames` I take particularly seriously because it has about 500 dependents on npm and is [linked to from the React docs](https://facebook.github.io/react/docs/class-name-manipulation.html) as the recommended way to achieve the syntax being described above.

For background, `classSet` used to be shipped with React addons but the React team wanted it to be shipped and maintained separately, so we created `classnames` instead. Members of the React team helped review it for performance and implemented tests to prevent regressions for people moving from `classSet`.

> a speedup anywhere is a speedup IMHO

The speedup PR cited is absolutely _not_ clear cut; the original implementation of classnames used an array w/ `.join(' ')` and we moved to string concatenation because it seemed to be faster in more real-world scenarios (running in browsers, not server-side). The PR sped up some paths and slowed others, and wasn't benched in the target environment.

Speed is crucial in this package since it gets run _during_ the render cycle; the number of times this function has been run in browsers all over the world is pretty crazy. So we are pretty conservative about changes.

> And the common cases are string arguments.

That's a total assumption.

Trust is not just about responding to PRs but also protecting users from unexpected changes and performance regressions. Stability is important, particularly for utility packages. If someone can help establish a performance enhancement we can _trust_, I'm going to be very happy to merge it.

**Comment by impinball** [comment]
@JedWatson @dcousens I'll reply with this: ranting like a dumbass is probably not the smartest thing to do on a public feature request discussion, and I screwed up by doing that very thing. I've already been trying to make amends on that repo through action as well as words. :rose: I hope you accept this apology of mine. :disappointed:

**Comment by JedWatson** [comment]
@impinball no worries, I didn't feel good ranting here either but didn't feel OK leaving it hanging without explanation, lest someone else take the wrong message by only having partial information from one of several related GitHub issues.

Thanks for your involvement in `classnames`, it takes many perspectives to develop a robust OSS package - seriously, I've spent more time managing and maintaining that package than many others (literally days) which on a `time / lines of code` basis is insane. But ultimately the whole community benefits and it's worthwhile.

Back to the original point of this issue, I'd be stoked to see `classnames` included as syntax sugar in Mithril to transform arrays and objects into strings, but I also agree that `{class: classNames({ whatever: true })}` is explicit and unopionated. React includes it in the docs but leaves the decision on which library / method to use up to the author which makes sense and keeps the core light.

**Comment by lhorie** [comment]
Personally, I like explicit and unopiniated `</two-cents>`

**Comment by StephanHoyer** [comment]
Same here.

I mostly do
```javascript
// init one time
var m = require('mithril');
m.classy = require('classnames');

// use everywhere
m('div', {
  class: m.classy('baz', { bar: true })
}, 'foo')
```

**Comment by JedWatson** [comment]
@StephanHoyer keeping is classy. Nice :grinning:

**Comment by StephanHoyer** [comment]
OFF TOPIC
@JedWatson I'm curious to know why you prefer react over e.G. mithril since you appear to like lightweight solutions over heavy ones.

**Comment by JedWatson** [comment]
@StephanHoyer I'll try and answer but I feel like I've spammed enough people today who are watching various repos and issues :grimacing: so let's take any followup conversation elsewhere maybe?

I've been watching mithril for a while now and admire the project, I wouldn't say I specifically "prefer" React. I find it a pragmatic choice for various reasons including maturity and the broader ecosystem (not to mention our stack at work is trending towards equal parts node, react and react-native)

Honestly I'm trying to answer this without sounding opinionated (or comparing a framework I'm very familiar with to one that I'm not) and it's hard. Mithril is definitely lightweight as a framework, but I also find React code (i.e. React components, not React itself) to be lightweight and clear. Before getting so heavily into it I spent a lot of time assessing different options including Ember, Angular and Polymer as well as lighter frameworks like vue.js and mithril, and writing for React just "felt right" to me.

Mithril seems slightly more opinionated and verbose in the code you write for it than React does. It's not so much a matter of more or less abstraction, but where the abstraction sits. I suspect someone more familiar with mithril could make good arguments against that, I think it's also a personal thing.

I've also been part of the React community for a while now, so there's a certain momentum to that, and there's a lot of creativity around it that I enjoy w/ emerging patterns & technology like Redux, Relay, GraphQL and approaches to managing CSS.

**Comment by tivac** [comment]
> @lhorie
> Personally, I like explicit and unopiniated &lt;/two-cents&gt;

![hooray](http://i.somethingawful.com/forumsystem/emoticons/emot-golfclap.gif)

Reiterating my strong support for keeping this out of mithril core, it should stay in user-land where it belongs.

(PS Hi @JedWatson I'll get back to KeyStone someday I swear)

**Comment by impinball** [comment]
I would have to agree with @tivac in that this should not be in core. There's actually other  things that should be removed from core. A couple examples are the promise implementation and `m.request()`, as they are almost completely independent of one another, have almost no coupling in core, and there are other modules with the same functionality. I personally wouldn't use them if they weren't in core, because they aren't the best in either size or speed. Bluebird is fast. Promiscuous is tiny (smaller than what's currently here, with an ES6 style API). jQuery's `$.ajax()` is available standalone, and is easy to alter to use a different promise implementation.

**Comment by JedWatson** [comment]
@impinball +1  `classnames` was pulled out of React for the same reasons which ties this whole thread together nicely. They're still trying to get rid of addons that really shouldn't have been bundled in the first place.

@tivac hi! :wave:

**Comment by StephanHoyer** [comment]
@JedWatson Thanks for the insight. I'm now feeling reassured to use the right framework, since your points are mainly personal taste.

Me for myself find react much more opinionated and verbose than mithril (mainly due to the use of JSX and ES6-classes). But that's my personal opinion.

**Comment by impinball** [comment]
@StephanHoyer I agree.

**Comment by realdope** [comment]
I'd rather have JedWatson's classnames as a part of Mithril than m.withAttr, as it's easier to write a proper event handler than it is to write a [a?'cls1':'', b?'cls2':''].join(' '). But that's just my personal opinion.

**Comment by tivac** [comment]
Use `classnames`.
