### ISSUE TITLE
Better way to hook onto DOM element destruction

### ISSUE THREAD

**Issue by tobscure** [lhorie/mithril.js#552]
If I am setting up global event handlers in a component like this:

```javascript
var MyComponent = {
  controller: function() {
    var ctrl = this;
    this.scrollHandler = function() {
      // do something
    }
    this.onload = function(element, isInitialized) {
      if (isInitialized) { return; }
      $(window).on('scroll', ctrl.scrollHandler);
    }
    this.onunload = function() {
      $(window).off('scroll', ctrl.scrollHandler);
    }
  },
  view: function() {
    return m('div', {config: ctrl.onload.bind(ctrl)});
  }
}
```

But then I include the component in a root component that cancels the unloading:

```javascript
var IndexPage = {
  controller: function() {
    this.onunload = function(e) {
      e.preventDefault();
    }
  },
  view: function() {
    return m('div', m.component(MyComponent));
  }
}
```

When I route away from that root component, firstly the sub-component unloaders are called (and thus my scroll event handler is turned off), and then the root component's unloader is called, cancelling the transition. But it's too late - my event handler has already been lost.

Really, I want this event handler detachment to be tied to the destruction of the DOM - after all the unloaders have been run and we know for sure that we're unloading the component.

Possible solution is a `destroy` hook in the attrs object of a vDOM element, similar to `config`?

```javascript
return m('div', {
  config: ctrl.attachScrollHandler.bind(ctrl),
  destroy: ctrl.detachScrollHandler.bind(ctrl)
});
```

This might also be a good time to talk about a nicer config/init API, as brought up in #492

**Comment by lhorie** [comment]
config context onunload is probably what you're looking for:

```
m("div", config: config)

function config(el, isInit, ctx) {
  if (!isInit) {
    ctx.onunload = function() {
      //do stuff here
    }
  }
}
```

**Comment by tobscure** [comment]
Ah perfect - sorry, didn't know that existed!

What do you think about the simpler APIs though? (init/ destroy attrs)

**Comment by lhorie** [comment]
I've avoided adding too many custom attributes for the sake of keeping learning curve small. Things like init/destroy would fall in the umbrella of things that can be handled via [template extensions](http://lhorie.github.io/mithril-blog/extending-the-view-language.html). I don't really want to add specific features from this umbrella into core because it becomes a slippery slope of features.

I'm debating whether to add the extensibility mechanism in core (and possibly exposing these and other tools in a utilities library. On the one hand the extension mechanism can be very expressive, but on the other, it can wreck performance if you're not careful.

**Comment by tobscure** [comment]
Fair enough, solid reasoning :)
