### ISSUE TITLE
Some events cannot be handled

### ISSUE THREAD

**Issue by Naddiseo** [lhorie/mithril.js#574]
Consider the following example:

```javascript
function view(ctrl) {
    return m('div', { ontransitionend : ctrl.transitionFinished.bind(ctrl) });
}
```

It will not work since mithril uses the [older way](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Older_way_to_register_event_listeners) to add events instead of `addEventListener`. I'm assuming this is for performance and compatibility reasons, but it does break the assumption that "on{eventname}" is how you register events for a given element.

**Comment by barneycarroll** [comment]
All the properties (except Mithril-specific properties like `key`, && `config`, and `style`, which accepts an object) in the object passed as the second argument to m() will be treated as attributes or properties for the DOM element. In your case, you might want to try:

```javascript
function view(ctrl) {
  return m('div', { config : function( el, init ){
    el.addEventListener( 'ontransitionend', ctrl.transitionFinished.bind(ctrl), false );
  } );
}
```

BTW, you may be better off binding your controller methods to the controller instance on declaration instead of relying on them being bound properly in the view, eg

```javascript
var component = {
  controller : function(){
    this.transitionFinished = function(){
      this.animated = true
    }.bind(this)
  },
  view : function(ctrl) {
    return m('div', { config : function( el, init ){
      el.addEventListener( 
        'ontransitionend', 
        ctrl.transitionFinished, 
        false
      );
    } );
  }
}
```

**Comment by Naddiseo** [comment]
@barneycarroll I'm not entirely sure using config works in this case. My understanding is that the config function is called after the render at which point it may be too late to add the event listener.

Here's a jsfiddle that demonstrates the problem: https://jsfiddle.net/v3bmL497/6/

**Comment by barneycarroll** [comment]
Config gets called as soon as the DOM element is appended to the document — synchronously — so the asynchronous transition will not be able to call back before then. 

Gotta rush ATM — I'll make sure to take a closer look at your fiddle later…

**Comment by darsain** [comment]
I've also noticed issues with using `on{eventname}` properties. For example, IE developers decided that `onwheel` property won't be a thing (see [782835](https://connect.microsoft.com/IE/feedback/details/782835/missing-onwheel-attribute-for-the-wheel-event-although-its-supported-via-addeventlistener) & [768199](https://connect.microsoft.com/IE/feedback/details/768199/onwheel-feature-detection)), so in IE `wheel` event can be bound only via `addEventListener`.

It seems that in future there will be more events that can't be bound via `on{eventname}` properties, as spec bodies and browser developers apparently don't care about this anymore and will rather recommend using `addEventListener`.

Does this warrant implementing an abstraction for `on{eventname}` properties, which would use `addEventListener` in the background? Because seriously, we can't be moving everything into configs...

**Comment by Naddiseo** [comment]
I'm thinking something similar to the following snippet. The only problem with using it is that the events don't get unregistered.
```javascript
// Detect which method should be used for registering events.
function detectEventListener() {
    if (window.addEventListener) {
        return function (el, type, listener) {
            return el.addEventListener(type.slice(2), listener);
        };
    }
    else if (window.attachEvent) {
        return function (el, type, listener) {
            return el.attachEvent(type, listener);
        };
    }
    else {
        return function (el, type, listener) {
            el[type] = listener;    
        };
   }
}
var addEvent = detectEventListener();

// ... later in setAttributes()
//hook event handlers to the auto-redrawing system
else if (typeof dataAttr === FUNCTION && attrName.indexOf("on") === 0) {
        addEvent(node, attrName, autoredraw(dataAttr, node));
}
```

**Comment by lhorie** [comment]
@Naddiseo I see a couple of issues with your code:

1) timeout parameter is being passed to reject, instead of setTimeout here: `this.timeout = setTimeout(openingDfd.reject.bind(null, "Animation timeout", 1500));`

2) your modal view gets created w/ the `in` class already applied to it, so it doesn't trigger a transition. In order to trigger a transition, the DOM needs to be painted at least once without the `in` class, then painted again with it. You can achieve this by pre-drawing the modal on page load (while it's still invisible), or by combining m.redraw(true) and reading `offsetWidth` or similar to force a repaint before setting the `in` class.

Here's a jsfiddle demonstrating transitionend events firing: http://jsfiddle.net/3x3xu8ak/

**Comment by Naddiseo** [comment]
@lhorie, thanks for the feedback.

1) I noticed that in my "production" code too. Doesn't affect the outcome though.
2) I did manage to get it to produce the correct redraws with the correct classes, but I'm not entirely sure it's painting. My updated fiddle: https://jsfiddle.net/v3bmL497/9/

Okay, so transitionend does actually work :) with mithril, but it's still jarring to have to use config to register the handler. I'm in the same boat as @darsain for this, worth considering perhaps?

**Comment by tivac** [comment]
I was really surprised by this behavior as well. I appreciate the simplicity of the current method but I think having to know which events require attachment via config fn vs which can just be added is violating the principle of least surprise. I totally understand the advantage of avoiding `addEventListener`, not having to track added events and clean things up seems great. It does make certain events pretty awkward to use unfortunately.

**Comment by maranomynet** [comment]
+1 what @tivac said.
I was very surprised (and disappointed) to realise that `on{eventType}` wasn't being captured and bound via `addEventListener`.

**Comment by maranomynet** [comment]
FWIW, I made an attempt to write a wrapper function to provide a few basic super-powers to Mithril's `m()` – including DOM Level 2 event bindings for all event's that haven't been explicitly white-listed as Level 0 safe.

That and custom attribute transformations (a là [mattr](https://github.com/barneycarroll/mattr/)) and exposing a small handful of utility functions to help dealing with the minimalistic nature of `attrs.config` and `ctx.onunload`.

https://gist.github.com/maranomynet/f138d874f296be3752df

So far, it seems to be working pretty well.

**Comment by impinball** [comment]
@maranomynet They aren't captured, but I don't see a lot of point in using it. Also, with Mithril's eager redrawing, if the node is still unchanged, yet the property value changes, then it's easy to accidentally register multiple listeners in rapid succession, an easy way to create a horrible memory leak and a whole range of bugs from duplicate function calls. For similar reasons, React does the same thing. It's unnecessary state that is generally better off not having in the first place.

**Comment by maranomynet** [comment]
@impinball it's not trivial, but quite possible.
The gist has gone through a few revisions, but has reached a state where it's stable and working nicely – only registering events when attributes are added, removing events on attribute removal, etc. etc. and tries to be as fast as possible.

Based on a few days of use, the convenience is remarkable. :-)

**Comment by impinball** [comment]
Question: which is actually faster, `on{event}` or `document.addEventListener`?

**Comment by maranomynet** [comment]
Not sure. But `document.addEventListener()` is always faster than a `on{event}` that doesn't trigger at all.

`document.addEventListener()` that you manually add via a `config` will run faster than something that goes through a convenience wrapper that picks up on unsupported `on{event}` attributes.

But it costs developer time and is more error-prone - unless you roll your own convenience functions, which then cost cycles, anyway. :-)

YMMV! :-)

**Comment by lhorie** [comment]
FYI, rewrite branch now uses `addEventListener` so it should support every event type including transitionend, etc
