### ISSUE TITLE
Allow m.redraw to optionally specify the desired frame-rate.

### ISSUE THREAD

**Issue by lawrence-dol** [lhorie/mithril.js#580]
Could we be allowed to specified the target frame-rate for m.redraw(). Many interactions do not need anything near the 60 FPS hard-coded rate.

This would be a simple addition of any optional parameter:

    m.redraw = function(force,rate) {
        //lastRedrawId is a positive number if a second redraw is requested before the next animation frame
        //lastRedrawID is null if it's the first redraw and not an event handler
        rate = rate || FRAME_BUDGET;
        if (lastRedrawId && force !== true) {
            //when setTimeout: only reschedule redraw if time between now and previous redraw is bigger than a frame, otherwise keep currently scheduled timeout
            //when rAF: always reschedule redraw
            if (new Date - lastRedrawCallTime > rate || $requestAnimationFrame === window.requestAnimationFrame) {
                if (lastRedrawId > 0) $cancelAnimationFrame(lastRedrawId);
                lastRedrawId = $requestAnimationFrame(redraw, rate)
            }
        }
        else {
            redraw();
            lastRedrawId = $requestAnimationFrame(function() {lastRedrawId = null}, rate)
        }
    };

This would enhance our ability to reduce unnecessary redraws for most (non-animation related) changes to the model.

(PS: Sorry about the initial blank post; hit ENTER by accident on a window flip).

**Comment by lhorie** [comment]
FRAME_BUDGET isn't a rate, it's the amount of time left until the next frame (and not frames after that), and it's only used to polyfill requestAnimationFrame, which doesn't let us specify a custom refresh rate.

This code exists to batch synchronous calls that happen within a frame (since it's pointless to redraw faster than the monitor refresh rate).

To go slower, you can wrap m.redraw in a setTimeout
