### ISSUE TITLE
The Google spreadsheet is suboptimal for sharing snippets

### ISSUE THREAD

**Issue by pygy** [lhorie/mithril.js#587]
It has poor readability and explorability.

I think we'd be better off using the Wiki.

FWIW, here's another one by @barneycarroll turned into a gist: https://gist.github.com/pygy/89c34b25ad7dd145c2dc

**Comment by lhorie** [comment]
Refresh my memory, where's the spreadsheet again?

**Comment by pelonpelon** [comment]
Spreadsheet (link found at the bottom of the wiki Community Projects page)
https://docs.google.com/spreadsheets/d/1ga0CL9WoOC5VZmVMVwGpmX260_fZZ7A6vUat91EJRiY/edit#gid=0

I've been saving gists of anything useful I find on the google list, gitter, issues tracker, etc. They're useless for publication because I didn't include comments or credit the authors. But I would welcome one place to contribute patterns/snippets, where people could comment and help correct and refine the code.

I wish jsbin or jsfiddle or plunker had a comment system.

I will copy this comment over to Gitter since it's not technically an issue and should probably be closed.

**Comment by lhorie** [comment]
Ok, closing
