### ISSUE TITLE
Issues with strictly adhering to uri.js

### ISSUE THREAD

**Issue by sdalezman** [lhorie/mithril.js#619]
We are upgrading to 0.2.0 which looks great so far, but we are running into an issue with routing due to following the serialization techniques of uri.js. Uri.js serializes an array: `bar=["hello", "world"]` in the following manner: `bar=hello&bar=world`. This is problematic because [tornado](https://github.com/tornadoweb/tornado) (our server framework) expects multiple arguments to be serialized in the following manner: `bar%5B%5D=hello&bar%5B%5D=world`, which is an encoding of two brackets `[]` after the variable name. 

I wanted to open a discussion around providing the ability to override the default building of a query string by mithril when calling `m.route(String path [, any params])`. I understand that this adds complexity to the route object, however I think that because many servers don't conform to the same standard of how uri's should be encoded this is necessary. I can't imagine that we are the only ones experiencing any issues with regards to the uri encoding. 

Our entire site uses mithril and if this isn't added to mithril we will have to maintain a side by side implementation of mithril just to augment `buildQueryString`. This would cause us to not be able to upgrade to newer mithril versions in a timely manner. 

I am happy to submit a pr with the necessary code changes - I wanted to open a discussion before doing so.

**Comment by Naddiseo** [comment]
This isn't really a mithril issue, it's an issue with tornado not being able to parse Uri.js output.

Why not just shim/replace `buildQueryString` instead of maintaining the whole library? a la: `m.route.buildQueryString = myBuildQueryString`

As for Uri.js output itself, where I work we decided that it's not the optimal way of transferring data to the server and instead use a json encoded parameter, which is then parsed separately on the server. We discovered that a url encoded json structure takes up (I think it's exponentially) less space than the equivilent Uri.js encoded one.

**Comment by sdalezman** [comment]
Thanks for pointing out that buildQueryString is exposed on the route object!! I didn't see that when browsing through the source code, that's a huge help.

And that's really interesting regarding the Json encoded parameter, I'll definitely have to play around with that idea. 

Going to close this, as it's not an issue. Thanks again!

**Comment by barneycarroll** [comment]
Hi @sdalezman, I've been using Mithril with URIjs from day one. It quickly becomes apparent that URIjs is far more complex and configurable when it comes to URI parsing and manipulation than Mithril (as one might expect), often in ways you can't expect Mithril to understand completely.

Because URIjs is far better at constructing URIs than Mithril, I use it to construct fully formed paths before handing them to Mithril, rather than relying on different methods of each. So my route invocations typically look like this:

```Javascript 
m.route(
	URI( m.route() )
		.methodX( ... )
		.methodY( ... )
		.methodZ( ... )
)
```

It's true that `m.route( URI( m.route() ) )` looks confusing. Until a recent point release it was possible to override the `URI.href` constructor, which I used to take `m.route()` instead of `window.location` if it was constructed without input.
