### ISSUE TITLE
What is the valid way to change only part of page on URL change using m.route?

### ISSUE THREAD

**Issue by AlexeyGrishin** [lhorie/mithril.js#622]
Hello,

I've started using mithril.js in my project and met a problem which I'm not sure how to solve. I use m.route for internal navigation between different pages. But one of the pages is shown in popup over another, and I'd like to have a separate URL for it, i.e. when `/page1` opens page without popup and `/page1/overlay` opens same page with popup over it. I've tried to map both URLs on same component, like that:

```
m.route(document.getElementById('form'), "/", {
  "/": Page1,                                           
  "/:action": Page1
})
```

and then inside Page1.view show popup only if `m.route.param('action') == 'overlay'`. It works, but on popup opening/closing it re-creates Page1 component. As that page loads some data by ajax it leads to noticeable flickering.

Here is jsfiddle which illustrates the problem: when you click on "open overlay" or "close overlay" the URL in browser address line is changed, but top page is reloaded (it uses timeout to emulate ajax call).
Result: https://fiddle.jshell.net/GRaAL/wvbhf9q8/2/show/light/?/
Source: http://jsfiddle.net/GRaAL/wvbhf9q8/3/

Could you please point me the valid way to achieve that? Is there way to not re-create component on URL change?

Thank you very much in advance.

**Comment by barneycarroll** [comment]
Hi @AlexeyGrishin, the reason this is happening is that Mithril assumes you want to re-initialise when the route changes, and sets the redraw strategy to `all` when route change occurs. Like you, I discovered this wasn't desirable in my application, so I make sure my top level component controllers [reset redraw strategy to `diff`](https://lhorie.github.io/mithril/mithril.redraw.html#changing-redraw-strategy): because they are executed before the view is computed, they are able to keep subcomponents in place. [Here's a fork of your fiddle demonstrating this](http://jsfiddle.net/barney/safyz4kk/0/). [Here's another one with alerts during controller execution](http://jsfiddle.net/barney/safyz4kk/1/), to show how this affects execution logic.

**Comment by AlexeyGrishin** [comment]
Thank you so much! I've been sure there shall be something for such scenario, just missed that part of documentation.
Probably in docs for `m.route` shall be reference to redraw strategy?

**Comment by barneycarroll** [comment]
> Probably in docs for m.route shall be reference to redraw strategy?

That's a good point — this isn't the first time people have been looking for this functionality…

**Comment by pelonpelon** [comment]
I added a link to a jsbin to the wiki under Solutions to Common Problems with @barneycarroll 's solution:
http://jsbin.com/zutisu/4/edit?html,js,output
