### ISSUE TITLE
Bug in the "getting started" page

### ISSUE THREAD

**Issue by pieroxy** [lhorie/mithril.js#624]
The example in the "getting started" page ends with `m.mount(document, {controller: todo.controller, view: todo.view});` while the jsFiddle uses `m.module(...)`. I believe the jsFiddle is correct since using `m.mount(...)` doesn't work.

https://lhorie.github.io/mithril/getting-started.html

**Comment by sdalezman** [comment]
@pieroxy in mithril 0.2.0 `m.module` has been renamed `m.mount`. Per the change log: 

Calling m.module will still work, but should be considered deprecated. Rationale: Mithril modules and components are the same thing, therefore from now on, they will be referred to as components, since that name is more descriptive of their purpose, and causes less confusion in the face of ES6 modules.

Can you share the jsfiddle where m.mount doesn't seem to work.

**Comment by pieroxy** [comment]
The thing is, in the jsFiddle, if you replace `m.module` with `m.mount` it doesn't work... Maybe we should update the jsfiddle with a newer version of mithril.

I'm talking about the jsFiddle that is linked in the "getting started" page:

http://jsfiddle.net/milesmatthias/fbgypzbr/1/

**Comment by sdalezman** [comment]
It's because the jsFiddle is loading mithril 0.1.32. 

Here is a jsFiddle with 0.2.0 and it works: http://jsfiddle.net/fbgypzbr/16/. 

The getting started page should be updated with an updated jsFiddle

**Comment by pieroxy** [comment]
That was my point. So I'll leave the issue open. Thanks for the clarification.
