### ISSUE TITLE
Views of child components are not redrawn when passed via Controller

### ISSUE THREAD

**Issue by mt0erfztxt** [lhorie/mithril.js#650]
Example of expected/unexpected behavior in this [jsfiddle](http://jsfiddle.net/mt0erfztxt/c9cd8ksa/). When I pass child components directly to `view` via `args` argument all works. If pass same components through `controller` then nested views of component are not redrawn any more, to see it in action uncomment lines 34-48. Am I doing something not in 'Mithril way' when use `controller` to prepare/configure components for `view`?

**Comment by lawrence-dol** [comment]
In the failing case you are only creating the vdom once, when the controller initializes. In the working case you are creating the vdom every time the view runs. The latter being what you want to be doing if you want to have subsequent changes to the content reflected in your view. Otherwise the value of `groups` is simply the vdom of the content as it was when the component was initialized.

**Comment by mt0erfztxt** [comment]
Thanks for your reply and you are right! This was clearly stated in Mithril docs also. Example in fiddle above was simply ... stupid? I modified it to be more similar to code with which I have a problem. New version is here [jsfiddle](http://jsfiddle.net/mt0erfztxt/n8ubLmdo/). Now I am not creating an array in `controller` but save a reference of `content` argument and use it in `view`. As I suppose the `content` argument in `view` is a same object as `ctrl.content`, but still no luck. Feels like my problem lie in lack of understanding of JS as a language.
