### ISSUE TITLE
Route adds two questions marks to location

### ISSUE THREAD

**Issue by Naddiseo** [lhorie/mithril.js#659]
Example: http://jsbin.com/lezaqareve/1/

Click the button twice.
On the second time, the console prints "http://null.jsbin.com/runner??hello=world"

**Comment by Naddiseo** [comment]
Work around is to use `m.route.mode = 'pathname';`

**Comment by pelonpelon** [comment]
I believe this solution worked by accident.

`m.route.mode = search` (the default) inserts "?"
`m.route.mode = hash` inserts "#"
`m.route.mode = pathname` inserts "" (an empty string)

That empty string is there, you just can't see it :wink:

This is the signature of this particular use of m.route:

`void route(String path [, any params] [, Boolean shouldReplaceHistory])`

"path" should be listed in the routes object (the example doesn't create routes, it uses m.mount directly). When a routes object has been created, redirecting to a non existent path (including the empty string) fails quietly. But without a routes object, Mithril attempts to assemble a route (I assume because the path can't be checked against a non existent routes object).

**I think it should be an error to call m.route with a path that is not in the routes object even when no routes object exists.**

**I wonder if all calls to m.route should should fail when no routes object exists.**

**Comment by Naddiseo** [comment]
Exactly; I looked through the source and saw that I could use 'pathname' as a workaround.

It probably should error without using a route object. The reason I'm using it like that is because it's a single page with no other routes, but I want bi-directional bindings between the url parameters and my model. I was hoping I could rely on mithril for the `window.onpopstate` event, but apparently can't. I'm probably using mithril outside its intended usage for this usecase.

**Comment by barneycarroll** [comment]
> I wonder if all calls to m.route should should fail when no routes object exists.

I reckon they should. We already have an error for when `m.route.param` is called before route initialisation.

Somebody once opened a ticket about the API disparity between `m.route.mode` and others in that this is pretty much the only Mithril API hook that allows direct setting (`m.attrs[ x ]` would be another ;) ) whereas the convention is to use functions to pass in the value. This could be another area to get valuable error catchment in.

**Comment by barneycarroll** [comment]
> I'm probably using mithril outside its intended usage for this usecase.

@Naddiseo I think if you're building anything that's more complex than TODO MVC and using Mithril's 'less core' functionality (XHR, routing, promises — basically everything that isn't about view rendering), you're going to find a need to extend or complement the API at some point.

My app deals with a host of web services and involves such things as query parameters in the URI that change as the user types. The goal (for development sanity and user convenience) is to make everything as RESTful as possible. 

Because URI abstraction is difficult enough regardless of Mithril's API, I'm using [URIjs](http://medialize.github.io/URI.js/) (which I highly recommend — W3C URL API has nothing on this). With the number of people implicitly relying on URIs to make the Internet work and the prevalence of SPAs , you'd think getting the 2 to interop cleanly would be easy. It's not the case. URIs are hella difficult. 

If you don't mind ditching users without `pushState` (or 'HTML5 history API') and your server can dish out the same thing I when browsers require any subpath on your app domain, then `pathname` is the best choice. If not, go for `hash`. The problem with both hash and query is that they hack / override part of the browser Location API, and the native API is ambiguous and dumb. Personally I think it's far easier to sacrifice native hash logic (scrolling into view the element whose ID corresponds with the hash string). YMMV.

**Comment by Naddiseo** [comment]
@barneycarroll, here's how I got around the limitations: http://jsbin.com/purojinoho/5/edit?js,console,output

I would have preferred to use mithril for the popstate event. I'm only using it so that using history back didn't cause a page refresh, and I can have some sort of perma links.

**Comment by barneycarroll** [comment]
@Naddiseo Mithril effectively uses `popstate` and `hashchange` as far as I've seen — reload has never been a problem and should be reported as a bug AFAIC. Because Mithril's default attitude to route change is that it requires a full redraw (ie trashing the whole DOM and building the next view from scratch) I've extended all my top level components to invoke `m.redraw.strategy( 'diff' )` to prevent huge lags as the user types and the route updates (the controller, in turn, makes me requests based on the new route params).

**Comment by Naddiseo** [comment]
@barneycarroll, it only adds the event listeners if you install with `m.route($el, default, routes)`. I'm running into the issue that I have a variable number of search parameters, so I can't easily use pathname/hash to store the data..

**Comment by barneycarroll** [comment]
For clarity: my application relies on ultra responsive search to render complex data. I have been able to render non-trivial views (ie every search result invokes its own component which renders a non-trivial view [complex nested DOM] and may make extra HTTP requests itself — all the while holding a stateful UI while being a part of an occlusion culled lazy loading list) and Mithril's routing has not blocked me in the slightest. What _has_ blocked me is default component behaviour (destroy and rebuild the view by default — whereas I want to diff all the time), but that's another story.

**Comment by barneycarroll** [comment]
@Naddiseo fancy getting on Gitter to discuss gory details? https://gitter.im/lhorie/mithril.js?at=551323bac183f73134d03e00

**Comment by lhorie** [comment]
I think calling `m.route` if you mounted using `m.mount` falls under undefined behavior
