### ISSUE TITLE
Background m.request should redraw on resolution 

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#664]
What do we think?

**Comment by pelonpelon** [comment]
Let's say there's a bg request taking a long time. The user keeps interacting with the app, maybe fiddles with some input. m.request resolves, redraw is called, and suddenly the view reconfigures with the new data. It could be jarring. It might overwrite some user input. Think 2g phone connection.

Just thoughts.

But I'd love to have the option.
Set and forget!

**Comment by lawrence-dol** [comment]
I think it should. If the newly resolved data affects the model in some what that changes the view, it needs to be seen; if it doesn't affect the view, then the redraw is moot. But 99.999% it will affect the view.

**Comment by barneycarroll** [comment]
@pelonpelon bit of a tangent, but I reckon it's pretty bad practice to have any part of your application written in such a way that a redraw will make it loose state. But it's also extremely common — a developer in that situation (ie with user input that isn't Mithril-bidi-bound) will figure this out the hard way eventually (or their users will) anyway…

**Comment by pelonpelon** [comment]
@barneycarroll  *"a redraw will make it loose state"*
I'm not sure what you mean. A redraw will update from an old view-state to a new view-state that is synched with model-state (that just got updated by a returned m.request).
I believe that is the usual intended flow of data, is it not?

**Comment by barneycarroll** [comment]
> It might overwrite some user input.

I was referring to this bit.

**Comment by pelonpelon** [comment]
Oh, gotcha.
I might have been a little overzealous in my counter argument.
Of course user input should not update without user confirmation.
I still feel an m.request redraw should be an option, not the default.

**Comment by epidemian** [comment]
:+1: for making background requests redraw on completion, or having an option for them to do that.

Right now, the [docs](http://mithril.js.org/mithril.request.html) for `m.request` mention that you should use `.then(m.redraw)` when using background requests. This does not cover all cases, as it won't redraw on request errors, which non-background requests do by default. So it should be `.then(m.redraw, m.redraw)`, which starts to look a bit silly.

Moreover, sometimes setting `m.redraw` in the request promise chain is not so straightforward. For example:

```javascript
User.fetch = function(id) {
  var req = m.request({
    method: 'GET', 
    url: '/api/users/' + id,
    background: true,
    initialValue: {loading: true},
  })
  req.then(m.redraw, m.redraw)
  return req
}

userDetail.controller = function() {
  this.errors = m.prop()
  this.user = User.fetch(1).catch(this.errors)
}
userDetail.view = function(ctrl) {
  if (ctrl.errors()) {
    return m('.error', 'Error loading user: ' + ctrl.errors().message)
  }
  return ctrl.user().loading ? 'Loading...' : [
    // user data...
  ];
}
```

I'd like to have all requests to this API endpoint be run in the background, and redraw when finished, so i set that on the `User.fetch` function. But, in case the request fails, the `m.redraw` callback will be called before calling the `errors` callback set by `.catch(ctrl.errors)`, so the view gets redrawn before the errors are set and will show the user as loading instead of showing the API error.

This is not a problem if the request is not set as `background:true`, as the redraw [is done](https://github.com/lhorie/mithril.js/blob/129e0baf434514e12796179b6ef5f623ab5d51e5/mithril.js#L2222-L2224) once the request is done and all the callbacks in the promise chain have been called.

If background requests should redraw by default, maybe [these lines](https://github.com/lhorie/mithril.js/blob/129e0baf434514e12796179b6ef5f623ab5d51e5/mithril.js#L2222-L2224) on `m.request` could be changed to:

```javasctript
} finally {
	if (options.background === true) m.redraw()
	else m.endComputation()
}
```

But maybe this could be achieved by another option:

```javascript
} finally {
	if (options.background !== true) m.endComputation()
	if (options.redraw) m.redraw()
}
```

Is the possible loss of user input the only cause for not redrawing automatically on background requests?  If that's the case, given that background requests are not the default, couldn't that be addressed on the docs for background requests? (something like "background requests are done this way, but bear in mind that they will redraw the view once completed, so beware of transient user input state")

What do you think?

**Comment by lawrence-dol** [comment]
You don't actually want it to actually do a redraw, you want it to queue a redraw on the event loop.

**Comment by lawrence-dol** [comment]
Any part of the UI that's affected by a pending async action should be replaced with a throbber until the action completes, so the entire losing state argument is moot.

**Comment by epidemian** [comment]
Oh, thanks for the tip @lawrence-dol, i hadn't though of using `setTimeout`! :smiley_cat:

**Comment by isiahmeadows** [comment]
@pelonpelon @barneycarroll 

BTW, if you diff the user state with the server data, and update both accordingly to the merged diff, you've avoided that problem altogether. Now, the user is alerted with new data, and the changes are (hopefully) saved on both ends, barring network connectivity problems.

Worst case scenario, if the network is that unreliable, but the data doesn't have to be fully real-time (e.g. with a web-based checkbook), you could just store the changes in `localStorage` or similar to send up to the server once a connection can be established, in case the user has to load a cached version of the page, and you still want the data the user sees to remain current relative to the client.

**Comment by TheChifer** [comment]
+1

**Comment by barneycarroll** [comment]
I'm not sure how likely this is to make it into Mithril v0.2.X, but this behaviour — non-blocking *and* redrawing after resolution — is baked in to the [rewrite](https://github.com/lhorie/mithril.js/tree/rewrite).

**Comment by isiahmeadows** [comment]
Closing, since we are no longer accepting feature requests for 0.2.x.
