### ISSUE TITLE
Bad link in release notes for v0.2.0

### ISSUE THREAD

**Issue by ariutta** [lhorie/mithril.js#670]
Small issue - the v0.2.0 release notes ("Virtual DOM tree can now contain components") link to:

https://github.com/lhorie/mithril.js/blob/v0.2.0/mithril.component.md

but that link 404s. I think the intended link is:

https://github.com/lhorie/mithril.js/blob/next/docs/components.md

**Comment by tivac** [comment]
https://github.com/lhorie/mithril.js/blob/v0.2.0/docs/components.md is the correct link.

**Comment by lhorie** [comment]
The link does work from the website. Am I missing something?

**Comment by venning** [comment]
@lhorie, I think he's referring to the **version number links** on the [change log](http://mithril.js.org/change-log.html).  They all 404.

**Comment by ariutta** [comment]
I was actually referring to [the v0.2.0 release notes](https://github.com/lhorie/mithril.js/releases/tag/v0.2.0), but @venning correctly points out additional dead links.

**Comment by venning** [comment]
Huh.  I've never noticed that "release notes" section on GH before.  Thanks @ariutta for pointing that out.  No idea how that gets edited, but it appears to be correct now.

The change log needs a redo since the `/archive` directory was removed in [a subsequent commit](https://github.com/lhorie/mithril.js/commit/cd403225a259f4a8a574e83a419cd14167082984).

**Comment by barneycarroll** [comment]
The way archive sits with version control always screws me up. Fresh checkouts often ask me to commit the deletion of huge swathes of documentation. Is that the way it's meant to work?

**Comment by lhorie** [comment]
Changed links to point to mithril.js.org
