### ISSUE TITLE
This commit makes mithril stop working on android 2.2

### ISSUE THREAD

**Issue by mingodad** [lhorie/mithril.js#697]
Hello !

I'm testing mithril an discovered that it's not working on android 2.2/2.3 and probably others because of this commit:
https://github.com/lhorie/mithril.js/commit/dfb37fec9cd25ca5f18282cbe97120dc69dad43a

That commit uses a reserved word "catch" that's rejected by android 2.2/2.3 and probably others.

Changing that property name to any non reserved keyword seems to make mithril work again on android 2.2/2.3 .

P.S.: With the minified mithril it works because the minifier replace the "catch" by a short name.

Cheers !

**Comment by XrXr** [comment]
I think this can be fixed by just making it `prop["catch"] = // ...`
I don't have an Android 2.2/2.3 to test it, though.

Using reserved words as property names is a ES5 feature and unfortunately, unpolyfillable. Maybe this changes the [claim](http://lhorie.github.io/mithril/archive/v0.2.0/comparison.html) (Vue section) about everything used by Mithril can be polyfilled.

**Comment by lhorie** [comment]
Changed to the bracket syntax
