### ISSUE TITLE
<audio> elements and routes

### ISSUE THREAD

**Issue by llambda** [lhorie/mithril.js#726]
Not sure if this is a legitimate issue or not. If I have an audio element in a view, it seems to get re-rendered on route change. The problem is when the element disappears, the browser stops playing the audio stream, even if I render the same audio element. Would the solution be to not destroy audio tags on redraw? I tried m.redraw.strategy("diff") to no avail. As a workaround, using a hidden audio element separate from the vdom can potentially work. I guess sometimes you'd want the audio to stop and other times you wouldn't.

If there were a way to call m.route('blah') that only changes the browser's displayed route, but not actually performing a route change/render, that would work too, as I can re-render my components appropriately, I just want the URL to change for the purposes of copy-paste/bookmark triggering the appropriate route.

Edit: forget about the audio, I can handle it with HTMLAudioElement. What I really want is ability to change the displayed route without triggering a redraw. E.g., user clicks something, shows more specific details about some item, and I want the route to reflect that, but I don't want to trigger a route and redraw everything, since that will cause undesirable flicker.

**Comment by pdfernhout** [comment]
@llambda I don't think you can expect a component that is updated by m.route not to redraw entirely (by default). That just seems to be the way Mithril is designed. Still, there seems to be a "retain" option that might help with the situation your outline, although I have not tried it. See:
https://lhorie.github.io/mithril/mithril.html#persisting-dom-elements-across-route-changes
"When using the router, a route change recreates the DOM tree from scratch in order to unload plugins from the previous page. If you want to keep a DOM element intact across a route change, you can set the retain flag in the config's context object."

This issue may also be connected to issue #694, as it seems that when Mithril 0.2.0 unmounts any component (which happens during an m.route change), it will rebuild all mounted components (even though the documentation suggests that only the changed component will be rebuilt). Otherwise, perhaps you could perhaps just mount your audio component at startup and just leave it mounted, without having to use the "retain" flag?

In general, I don't notice much page flickering with Mithril, so I can also wonder if there is some other issue going on in your app or your testing (like maybe a lot of logging)? But perhaps the audio component takes a long time to rebuild, so that may be causing the flickering? So, if you improve that, maybe the flickering will no longer be an issue?

==== Creating your own routing

BTW, I don't use Mithril's m.route in an application that uses the hash (in part as a legacy from converting the code to Mithril from Dojo/Dijit where I had set up a different routing approach). The code I wrote for handling hash changes has some minor complexity for handing the hash (mostly parsing the hash, storing the parts of the hash in a "clientState" object, rebuilding the hash from the clientState object, and comparing changes to stored values to avoid spurious page changes like you are concerned about). The parsing and hash construction is mostly specific to the application, so you'd have to write your own for that.

The general code for handing hash changes is triggered by this:

    window.onhashchange = urlHashFragmentChanged;

And the code for setting the hash (in TypeScript, otherwise do JavaScript defaulting for the newValue arg) is:

    function hash(newValue = null) {
        if (newValue === null) return window.location.hash.substr(1);
        
        if (history.pushState) {
            history.pushState(null, null, "#" + newValue);
        } else {
            location.hash = "#" + newValue;
        }
    }

And here is code for optimizing-out spurious changes:

    function updateHashIfNeededForChangedClientState() {
        var newHash = hashStringForClientState();
        if (newHash !== hash()) hash(newHash);
    }

There is also another place in the application where I check if the current page has really changed to also reduce spurious redraws.

It is possible that the approach may not be 100% reliable in older browsers where polling might be needed to check if the hash value changes and change the history? See the Dojo library for a more complete hash monitoring solution which involves polling for older browsers. But this code above probably works as well as Mithril's m.route approach for hash routing (at least, I hope it does).

I'm glad I responded to this question as I found a bug in the above code for the non-pushState pathway while looking at it again. :-)

**Comment by barneycarroll** [comment]
You can prevent a total redraw during routing by inserting `m.redraw.strategy( 'diff' )` in top level controllers (ie the controller of the component the route points to).

**Comment by pdfernhout** [comment]
@barneycarroll Your suggestion of using "diff" in a top-level controller presumably would help with preserving the state of the nested components of other mounted components if one of those has the audio component (but see also issue #694 and a potential issue involving the global unloaders variable)? However, I don't think "diff" will work as expected during a route change in Mithril 0.2.0 for the specific component being routed using m.route. In the original issue, llamda mentioned "diff" did not work as expected too. A route change ultimately involves remounting a component using m.mount where the routed component is replaced entirely. All other mounted components will get rebuilt with a redraw strategy of "all" (which preserves the top-level component but replaces all nested components) -- unless presumably those components use "diff" as you suggest. So, I don't see how "diff" could help with the component being remounted by m.route? That said, I have not been using m.route, so my understanding of this may be incomplete. Would Mithril ever retain the HTML DOM elements for a completely replaced (unmounted/remounted) Mithril component? Could you point to a jsfiddle or other example where the "diff" strategy works with m.route?

**Comment by barneycarroll** [comment]
@pdfernhout I've written a couple of jsbins demonstrating this but can't find them at the minute (on mobile) — will try to dig up later.

Redraw strategy applies to the whole of the next redraw, so if a top level component (ie the one invoked by `m.mount` — which is used under the hood by `m.route`) invokes it, then it's entire view — including any subcomponents invoked in its view, all the way down, will be subject to the same policy. It's a very odd API and difficult to explain. To make things worse, the `onunload` API is basically incompatible with diffing because it relies on root elements being destroyed.

**Comment by llambda** [comment]
I forgot about 'retain' and will have to try that out. It appears that mithril is indeed unmounting all my components and remounting them on the route change, hence the "flickering". (When I just plainly nest the components without using routes, there is not "flicker".) I suppose that is by design, which makes sense.

As far as audio, I figured I can use a module-local HTMLAudioElement outside of my view and controller and manage it from a module, so the audio part is more or less solved. Or mount it to a separate DOM element.

@pdfernhout I like your approach to the hash routing. I think something like that is what I want to do. I will have to play around some more and see where I get. 

Thanks everybody for the help!

**Comment by impinball** [comment]
@llambda As for just replacing everything, that is mostly by design. Mithril eagerly redraws. And `.retain = true` is definitely the way to go with keeping the node live.

**Comment by sjungwirth** [comment]
`retain` has a couple of problems in 0.2.0, see https://github.com/lhorie/mithril.js/issues/724. I ran into a similar issue as you, except with iframes (youtube iframe API) where the iframe is destroyed and recreated every route change which results in reloading a bunch of files each time.
