### ISSUE TITLE
m.request doesn't handle empty body

### ISSUE THREAD

**Issue by milesmatthias** [lhorie/mithril.js#731]
Returning an empty body to a json request (in rails that means doing something like `head 200`), `m.request` tries to parse the response and makes a JSON error:

```js
Uncaught SyntaxError: Unexpected end of input
```

Obviously there could be a debate about whether or not you should ever get into this situation by not returning a JSON body, but I think this is something that `m.request` should handle correctly -- at least not throw an error.

I'll contribute this at some point when I get a chance but if someone beats me to it, awesome.

**Comment by Naddiseo** [comment]
You could create your own `extract()` or `unwrap()` to check for empty response, and react accordingly.

**Comment by barneycarroll** [comment]
I'd extend @Naddiseo's suggestion with 'should' rather than 'could'. `m.request` expects JSON and as such will break on content that isn't valid JSON. 

The relevant documentation for non-JSON data formats is [here](https://lhorie.github.io/mithril/mithril.request.html#using-different-data-transfer-formats)

**Comment by milesmatthias** [comment]
I still strongly feel that no library that expects JSON should throw an error if an empty response is given. However in the interest of making it easy to use mithril with other non-JSON apis, I just added a line to my custom extractor like @Naddiseo suggested.
