### ISSUE TITLE
Sweet.js Template compiler does not work with ES6 files

### ISSUE THREAD

**Issue by mneumann** [lhorie/mithril.js#744]
I am trying to precompile my Mithril code using the ```template-compiler.sjs```, but unluckily I have written my code in ES6 (using Babel as transpiler). If I translate the code to ES5 and then feed it to sweet.js, it of course can't find the 'm' name anymore, as it gets replaced but the full qualified imported name, which is something like  ```_vendorMithril2$752['default']```. Any hints? I think I am going to rewrite the code in ES5 (I am not using much of ES6), or use some sweet.js macros that enable ES6-compatibility.

**Comment by impinball** [comment]
The template compiler probably needs some heavy refactoring/rewriting, anyways. That'll be especially true with the changes being slated for the next significant release, since some of them are breaking. Another thing is that the [revision before last](https://github.com/lhorie/mithril.js/commit/067f91b4653a61227aeb0eddef39d0251f677295) was published with version 0.1.23, which there have been some API additions since ([the last was trivial](https://github.com/lhorie/mithril.js/commit/e4906706b13ae36b4c950c49ace0a7580134a6ee)).

And as for that attempted workflow, good luck. Babel mangles names for its imports. It always does. And SweetJS does not have complete ES6 support, or else that could work. A better idea would be to create a Babel plugin and use it, although that would also be non-trivial.

**Comment by lhorie** [comment]
I'm now recommending that peopel use [mithril-objectify](https://github.com/tivac/mithril-objectify/) instead
