### ISSUE TITLE
elements inside a SVG foreignobject cannot be correctly outputted

### ISSUE THREAD

**Issue by y0ke** [lhorie/mithril.js#752]
Elements inside of SVG [foreignobject](https://developer.mozilla.org/ja/docs/Web/SVG/Element/foreignObject) seems to be rendered improperly.
reproducible code is  https://jsfiddle.net/gua92u21/1/

```
  view: function() {
    return [
      m(
        "svg",
        [
          m(
            "foreignObject",
            {
              height: 100,
              width: 200
            },
            [
              m(
                "p",
                {
                  width: 100,
                  height: 200
                },
                "ABC"
              )
            ]
          )
        ]
      )
    ];
  }
```
The view code above end up outputting HTML below.
```
<svg><foreignObject height="100" width="200"><p width="100" height="200">ABC</p></foreignObject></svg>
```
This seems correct and If I write above code directly to a HTML file, it will be rendered correctly.
But when I output the above code via Mithril,DOM gets modified and looks like same as the case I write the HTML code directly to a HTML file though it will display no visible element.

 - once modifying the DOM of the `p` element such as adding line break or changing the text value,it will be displayed correctly.
 - replacing the `p` element to simple String, it works properly.(which means the case `foreignobject` has no child element but its value.)
 - so far I've checked,any kind of HTML tag triggers same problem.

**Comment by pelonpelon** [comment]
The documentation on foreignObject says that it must declare a separate namespace or it will not render. Here is a working example of your code: https://jsfiddle.net/dt6mqrq6/1/

I'm not sure why the code works in your HTML. One idea is that the default namespace of the page and the namespace of the foreignObject (which I assume is blank, no namespace) are indeed different. However, when Mithril inserts new svg, the browser assumes that it falls under the namespace of the page, and as per the docs, since there is no separate namespace the foreignObject is not rendered.

That might explain why you can see the foreignObject in the DOM (in view source, or the Elements pane of devtools) yet nothing appears on the page.

My jsfiddle ensures that the browser understands that Mithril is inserting something into the DOM under a separate namespace.

As to why altering the DOM **after** it's rendered causes it to appear, I can only guess that when the browser is recalculating the page, it *guesses* that you intend two separate namespaces.

Namespaces and how browsers deal with them is hard. I'm only making guesses here.

**Comment by y0ke** [comment]
Thanks. that works perfectly.
I still don't get why other ways to insert the HTML code works but Mithril though,as long as giving independent namespace make it working, it's okay to me.
