### ISSUE TITLE
Configure redraw strategy for route redirects

### ISSUE THREAD

**Issue by animecyc** [lhorie/mithril.js#763]
I think it would be a nice addition to the routing interface to be able to change the redraw strategy on route change. I find myself doing the below quite a bit:

```javascript
m.route( ... );
m.redraw.strategy('diff');
```

I would love to be able to do: `m.route( ... ).strategy('diff')` I think that would also help alleviate any confusion as to when you should be setting the redraw strategy (as I lost a bit of time by setting it before).

**Comment by jakobdamjensen** [comment]
While I might understand the reason you suggest it I really don't like mixing routing and redraw related API. I haven't had any use for that myself - perhaps others have.
But I don't see why m.route() would return m.redraw just so that you could set the redraw strategy... Am I missing something here? Perhaps you could make your own wrapper to do this for you?

```
function routeWithStrategy(path, strategy){
   m.route( path );
   m.redraw.strategy(strategy || 'diff');
}
```

People seem to set redraw strategy in the route handling components as suggested in the docs. Is this not a viable path for you to remove the extra lines of code? And I'm asking because I'd like to learn from your experience. I'm curious - not suggesting that you're doing anything "wrong". 
I did the redraw strategy dance in the beginning but after moving model related code out of the components all flickering has stopped. So I don't need the redraw on routes anymore (but it might be relevant later again).

**Comment by nordfjord** [comment]
Hey @animecyc 

This used to bother me as well, but I'm now using a pattern to solve this by making all controllers start by changing the redraw strategy to diff.

Something like this should solve the problem for you on an architectural level.

```js
var base_view = function(module){
  return {
    view: module.view,
    controller: function(){
      m.redraw.strategy('diff');
      if(module.controller) return (module.controller.apply(this, arguments);
    }
  }
}
```

keep in mind this is an abbreviated version of my function, since in my app I use it to splice the modules view into a predefined application wide frame.

**Comment by tivac** [comment]
Closing due to lack of movement.
