### ISSUE TITLE
Thought: defer element removal to user in ctx.onunload function

### ISSUE THREAD

**Issue by nordfjord** [lhorie/mithril.js#808]
After re-reading: http://lhorie.github.io/mithril-blog/velocity-animations-in-mithril.html

The fading out chapter in particular strikes me as odd.

> there's a cognitive dissonance caveat associated with [removal animations] that often confuses people

So here's a proposal to remove that dissonance.

Allow the developer to dictate when an element is removed from the actual dom. This could be achieved in `ctx.onunload` in config functions with something like this:

```javascript
config: function(el, init, ctx){
  if (!init) ctx.onunload = function(rm){
    rm.preventDefault(); // prevent mithril from removing the domElement
    // run your remove animation
    // and then call the remove function
    // which mithril provided you with
   removeAnimation().then(rm);
  }
}
```

The preventDefault function could be something as simple as marking the element with an `isRemoved` flag telling the diffing engine to ignore the element.

**Comment by tinchoz49** [comment]
nice idea!

**Comment by StephanHoyer** [comment]
I use this helper function for this

```
function deferEmpty(fn, timeout) {
  var oldResult = '';
  return function() {
    var result = fn.apply(null, arguments);
    if (!result && oldResult !== result) {
      setTimeout(function() {
        m.startComputation();
        oldResult = result;
        m.endComputation();
      }, timeout);
      return oldResult;
    }
    oldResult = result;
    return result;
  };
}

// wrap the view
viewFn = deferEmpty(viewFn, 1000)
```

But your solution would be far more convenient.

**Comment by mindeavor** [comment]
This seems like a great idea. Animations are difficult to generalize, but can be important in modern day apps. For example, what would be Mithril's answer to this React.js animation helper VelocityComponent? https://fabric.io/blog/introducing-the-velocityreact-library

**Comment by barneycarroll** [comment]
Implementing this would be very difficult (I would say impossible, but some
hacks may arise) because nested Mithril components are instantiated and
removed as a result of their no longer existing in the model. Mithril
doesn't manage models, so preventing the change to the model which would
result in a component's removal is beyond its scope. More realistically,
you'd be talking about reversing the change (since Mithril only knows that
component is being removed as a result of the effect of the change in the
model), then re-applying it. In the past I've seen these methods of
achieving the same result:

1. 'Will be removed' state
Ondrej Brinkel uses outgoing animations in his app Kopa (
https://github.com/kopa-app/kopa). IIRC his method involves building a
'will be removed' state into the view model: when an item is removed from
the deep model, it sets the 'will be removed' flag for that item. This
triggers the outgoing animation in the view, and that animation's callback
removes the view model item completely.

2. Clone the node in config and save it to the context, along with a
reference to its parent and position. onunload, append that clone and
perform the animation on it.
This is probably the easiest method that doesn't involve re-writing your
models or doing any heavy lifecycle hacking.


Regards,
Barney Carroll

barney.carroll@gmail.com
+44 7429 177278

barneycarroll.com

**Comment by tinchoz49** [comment]
mmm yes is true, the second choice is what i'm using in [mithril-transition](https://github.com/geut/mithril-transition)

**Comment by barneycarroll** [comment]
@tinchoz49 neat! I wrote a [much more basic version](https://gist.github.com/barneycarroll/c69fbe0786e37c941baf) of this yonks ago.

Ever since I wrote [Modulator](https://gist.github.com/barneycarroll/0e3c1b9811b47c012b13), in the back of my mind I've been thinking about writing a Mithril wrapper framework which extends Mithril with better component awareness. Mithril has been incredibly slow to develop and the 0.2 API extension was too little too late IMO. By providing a new API hook to invoke components in a context-sensitive way and keeping a more sophisticated and history-conscious internal model, we should be able to execute much more ambitious view logic. Watch this space...

**Comment by nordfjord** [comment]
@barneycarroll Yes the implementation might be nigh impossible, but I merely wanted to point out that there's cognitive load associated with removal animations that's been alluded to by Leo, yet a solution to this load hasn't been found, so I came up with a proposal.

As for your methods of achieving the "same" result, firstly the result of the proposal was less cognitive load, it wasn't only about being able to run removal animations in ctx.onunload (which I'm already doing using a similar pattern to your number 2). However for newbies coming into the framework this is one area where they will suffer, and all of the solutions proposed seem to very literally be to "avoid mithril at all costs while running these animations", or "block your entire page while you run them".

**Comment by barneycarroll** [comment]
This isn't the only aspect of Mithril where desired outcomes hit previously elegant patterns to produce a huge wall of cognitive dissonance - perhaps the most modest example of this (in my eyes) is nested component invocation + occlusion culling: trying to explain the problem was too much for me (or trying to understand it was everybody else's, depending on how you look at it :).

But whereas fixing that would just have been a relatively minor API change, fixing this really requires a deep re-write of Mithril. 

> "avoid mithril at all costs while running these animations", or "block your entire page while you run them"

TBH I think this is inevitable to some degree. Say I've got a player leaderboard updating in real time, each list item being a component with its own internal state. The player previously ranked 2 drops to 5. I want it to flip out downwards and flip in downwards in its new position, and the players previously at 3, 4 and 5 to flip up to indicate the relative movement. Unless I've built a view model on top of the source data that represents the transition state - in which case I don't have a problem - then during the animation my model is effectively out of synch with the view and I _don't want_ Mithril to attempt to render it because it's going to be at odds with what I'm trying to display. So in this situation, I need to stop Mithril redrawing all those components while I carry out those animations.

Yes, that's a fair bit of cognitive load to deal with this situation, which is an exception to the normal logic of virtual DOM statefulness. But the alternative is more cognitive load upfront, right?

**Comment by impinball** [comment]
To be honest, Mithril really needs a partial rewrite. My work is mostly trying to make it easier to iteratively do that. This ranges from my recent work in linting to a previous perf patch that broke a large function into smaller parts (which also made it easier to understand the code).

(Most of my contributions are to make it easier to maintain - I've been actively avoiding anything that would even trigger a minor semver bump in stable releases).

**Comment by lhorie** [comment]
in the works for the rewrite, so I'm going to close it
