### ISSUE TITLE
npm package is outdated

### ISSUE THREAD

**Issue by chrisdavies** [lhorie/mithril.js#831]
I was building a prototype against this, and only just realized that it was last updated 6 months ago:

https://www.npmjs.com/package/mithril

It's got some odd bugs in IE9 that aren't in the latest code, as demonstrated here (http://jsfiddle.net/qjxho57z/2/) Notice when you type in the text area in IE9, the output beneath the text area is one character behind.

So, I think an `npm update` would be nice!

**Comment by fmal** [comment]
Agree, would be great to bring the npm package up to date. Thanks!

**Comment by tivac** [comment]
npm's still on `v0.2.0` which is *technically* still the most recent release: https://github.com/lhorie/mithril.js/releases/tag/v0.2.0

I agree that it'd be nice to see a new release cut w/ the **187** commits to `next` since `v0.2.0` came out. Apparently @lhorie has some big plans to rewrite large parts of mithril in a back-compat breaking way? I've seen it mentioned a few times in random issues but nothing real concrete direct from the source.

A roadmap of future plans would be lovely ¯\\\_(ツ)\_/¯

**Comment by veggiemonk** [comment]
Have you seen #802 ?

**Comment by impinball** [comment]
@lhorie I think now's a good time to cut a patch release, before much work is done on #802. (Most of the non-breaking additions have already been done already).

**Comment by lhorie** [comment]
npm is now pointing to 0.2.2-rc.1
