### ISSUE TITLE
Skipping route change from component mounted in m.route() leaves Mithril in an invalid state

### ISSUE THREAD

**Issue by isiahmeadows** [lhorie/mithril.js#857]
[These 4 tests](https://github.com/lhorie/mithril.js/blob/next/test/mithril.route.js#L105-L222) pass, but when enabled, even individually, they cause over 45 other tests to suddenly start failing. This needs fixed.

**Comment by barneycarroll** [comment]
It might be possible to hack around this to some degree (by keeping an extra reference to the last full view tree vdom and re-applying it with a subtree retainer at the root, resulting in a patch noop that nevertheless reinstates the expected internal view snapshot, allowing the next diff operation to behave 'as if nothing happened', for example), BUT:

IMO this API (`e.preventDefault`) is fundamentally out of place in Mithril and should be removed. Because Mithril is model-agnostic, the model changes that cause any given change in the virtual DOM model are outside of its control. It is fundamentally misleading to say that Mithril can 'prevent' a change whose holistic cause it is ultimately ignorant of.

It is possible for full-fat Mithril (working with mounted components in a redraw-managed strategy) to 'lock' the draw state, and with some work we can feasibly introduce 'time travel' and other more advanced 'patch control' - ie storing and reverting view snapshots and exposing an API that allows the author to reference these and control patch logic to some degree.

Considering the other tasks on the table, I would suggest (at least temporarily) flagging this inconsistent, unreliable and misleading API as deprecated for the interim and returning to it at a later date when component & patching implementation logic may have changed, giving us a better position from which to decide whether to hack or scrap it - as it stands any implementation hack is likely to rely on implementation details that may well change in the near future.

What do you think?

**Comment by isiahmeadows** [comment]
Well...those tests apparently cause Chrome to go idle now... :frowning:

**Comment by 2is10** [comment]
Fixed now? Looks like #1117 enabled those tests.
