### ISSUE TITLE
Problem with subcomponents and redraw strategy 'diff'

### ISSUE THREAD

**Issue by nordfjord** [lhorie/mithril.js#866]
Issue #614
shows how unnecessary unload calls are added to components

if however the redraw strategy is set to 'diff' in controllers, the components don't get re-instantiated on route change.

see: [this bin](http://jsbin.com/xoguzuveje/edit?html,js,output) for an example

Click the link and see that the subcomponent controller get's unloaded twice, and is not instantiated again. Click the link again and for some reason nothing happens.

**Comment by nordfjord** [comment]
This is particularly troubling for people using a base-view pattern such as:

```
function baseview(component) {
  return {
    controller: ()=>{
      m.redraw.strategy('diff');
      return component.controller.apply(this, ...arguments);
    },
    view: ()=>{
      return m('.container', [
        m.component(searchbarcomponent),
        component.view.apply(this, ...arguments)
      ]);
    }
  };
}

m.route(body, '/', {
  '/': baseview(rootcomponent),
  '/a': baseview(acomponent)
});
```

since the searchbarcomponent would be unloaded on the first routechange and never get instantiated again.

**Comment by impinball** [comment]
PRs welcome

**Comment by barneycarroll** [comment]
This is not a 'simply fix bug' situation. It is imtrinsically linked to deep design flaws in component identification logic which would require a new API contract to address properly. Namely:

* Nested components are identified and instantiated based on the identity of their root element. In redraw diff mode, elements are recycled. Therefore Mithril's component resolution logic simply rebinds the old controllers. This is, sadly, expected behaviour according to Mithril.

* Nested component onunload behaviour is a total basket case. No further insight on that one I'm afraid.

**Comment by impinball** [comment]
@barneycarroll I'm aware it probably has to do with this. And I will try see if I can come up with a solution to the modularization problem with as little boilerplate as possible over this Chrismas break, if I have enough time.

**Comment by nordfjord** [comment]
Am I misunderstanding the complexity of the bug?
I would've thought this was easy to fix, just remove the controller from the cached controller array as soon as it is unloaded. Does the unloading function not have access to the cached controllers?
