### ISSUE TITLE
Google Chrome throw SecurityError when mithril is routing with pushState

### ISSUE THREAD

**Issue by baturinsky** [lhorie/mithril.js#867]
Last Chrome version (47.0.2526.73 m).

Uncaught SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'file:///D:/1/Elder/index.html#/c1' cannot be created in a document with origin 'null'.

I have hacked around it by replacing 
		if (window.history.pushState) {
line in mithril.js with 
		if (window.history.pushState && !m.dontUsePushState) {
and then adding 
		m.dontUsePushState = false
in my code

After that routing seem to work right, at least in "hash" mode

**Comment by Bondifrench** [comment]
It's an issue that happened before and seems specific to Chrome when serving files from local instead of a web server: see [mentionned it here](https://groups.google.com/forum/#!topic/mithriljs/aTDuTw3JNt0), [here](http://stackoverflow.com/questions/32398578/history-replacestate-no-longer-working-in-chrome-for-local-file) and [here](http://stackoverflow.com/questions/32508198/systrace-error-uncaught-securityerror-failed-to-execute-pushstate-on-histor)

While an embedded solution into Mithril would be nice and your solution seems valid, other ways to resolve it are:
- use a web server
- open chrome with `--allow-file-access-from-files`

**Comment by impinball** [comment]
Closing, as it's not a Mithril bug: https://code.google.com/p/chromium/issues/detail?id=529313

I may re-open this if and only if they decline to fix it.
