### ISSUE TITLE
News on the rewrite / next version?

### ISSUE THREAD

**Issue by maranomynet** [lhorie/mithril.js#868]
Hi @lhorie, a fiew times earlier this year you said you had a major update/rewrite of mithril in the works.

Now it's been almost 7 months since the last release (0.2.0) so I'm curious whether there is anything still happening? (And if so when?)

Or has mithril entered a "LTS" phase, of sorts?

**Comment by acconrad** [comment]
I second @maranomynet 's request - my company has been considering whether to use React or Mithril for our front-end and if there will be a major re-write with breaking changes, we may not be able to move forward with this framework anymore. Would be great to know now rather than later after we've already invested resources in moving over to Mithril if there will need to be another set of sweeping changes.

Thanks!

**Comment by barneycarroll** [comment]
The best way to keep track of progress is to [watch the Github repo](https://github.com/lhorie/mithril.js#notification-settings) to stay abreast of PRs.

Mithril is currently having its codebase modularised — the source code has always been very terse and highly hand-optimised. The idea is that a modularised code base will make future development easier.

There is a [wish list of Mithril features over here](https://github.com/lhorie/mithril.js/issues/802) which @impinball is keeping up to date as and when new requests are deemed desirable and features are merged in.

I've been working with Mithril and keeping a close watch on it for a year and a half. Based on my insight, I'd say breaking changes are unlikely any time soon. The only place a breaking change might happen lies in component initialisation logic — currently a component's persistence of internal state across redraws is directly linked to the identity of the element. This is what every other virtual DOM framework does, but over the months some people have found this contract to be undesirable in certain scenarios. Changing this behaviour would subtly change the operation of lifecycle hooks in ways we can't fully map out at the moment. Having said this, this possible change is

* unlikely to manifest itself in the near future without a lot more debate 
* will not fundamentally change the Mithril core API
* would not prevent long-term support and backwards-compatible maintenance for people using Mithril according to the current API

I wouldn't be concerned about Mithril being abandoned. It is still much smaller, faster and simpler to work with than React, and the core community is active and engaged. Pop by the [Gitter chatroom](https://gitter.im/lhorie/mithril.js) if you have more questions!

**Comment by lhorie** [comment]
FYI, there *is* one planned breaking change - the promise API will be changed to match the ES6 promise API. But this shouldn't be a big impact, since it mostly only affects calls to m.deferred and m.sync. 

Component initialization logic is not really a breaking change. I think it falls more under the category of supporting an use case that is currently not supported.

@maranomynet I got a bit sidetracked by some yak shaving but I am still working on it, albeit at a somewhat slow pace because kids are eating all my time -.-

**Comment by tivac** [comment]
@lhorie :tada:

Let me know if there's anything I can do to help!

**Comment by maranomynet** [comment]
Thanks for the info guys.

For someone who doesn't closely follow the PR discussions and the various Issue threads, and only looks quickly through the recent commit-history for the master/next branches, not much seems to be happening on the surface.

It's good to know that things are still brewing.

Oh, and btw @lhorie, congrats on the kids! :-)

**Comment by koglerjs** [comment]
>FYI, there is one planned breaking change - the promise API will be changed to match the ES6 promise API.  

Oh good, I came here to think about complaining about that.

**Comment by gamb** [comment]
It seems like there will be a lot of breaking changes in 1.x now. Certainly a departure from the 0.2.x API: https://github.com/lhorie/mithril.js/blob/rewrite/docs/change-log.md#migrating-from-v02x

Will there be any kind of LTS for 0.2.x, or do you expect 0.2.5 to be the last release, @lhorie? Imagine that's optimistic... as I assume 0.x is being used to denote versions that are liable to change radically.

Must say, I've found early releases to be exceptionally stable, and exquisitely simple. Does well on high-performance problems, and also at integrating with third-party libraries i.e. using `config()`. I'm a little reluctant to rewrite existing apps in the new form.
