### ISSUE TITLE
Routes with unicode characters are ignored

### ISSUE THREAD

**Issue by ArthurClemens** [lhorie/mithril.js#872]
This example has 2 routes:

```
m.route(document.getElementById('app'), '/', {
  '/:locale/销售/:filters...': ForSale,
  '/:locale/for-sale/:filters...': ForSale,
```
where the first one is ignored: http://jsbin.com/mayoza/edit?js,console,output

This test shows that the problem is in the routing regex: http://codepen.io/isiahmeadows/pen/KVwjOw

[JavaScript has a Unicode problem - Issues with Unicode in regular expressions](https://mathiasbynens.be/notes/javascript-unicode#matching-code-points) suggests to replace all instances of . in the regex with

```
[\0-\uD7FF\uE000-\uFFFF]|[\uD800-\uDBFF][\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]
```
(regex created by [Regenerate](https://github.com/mathiasbynens/regenerate) )

**Comment by pygy** [comment]
Provided you don't care about stray surrogates (It would be malpractice to use them in routes, IMO), you can reduce it to

```Ruby
/[\0-\uD7FF\uE000-\uFFFF]|[\uD800-\uDBFF][\uDC00-\uDFFF]/
```

Possibly wrapped in a `(?:non-capturing group)`, depending on the context.

**Comment by pygy** [comment]
Looking at the Regexes in the source, I couldn't make heads or tails out of the issue. Everything seemed fine (and is fine as far as regexen are concerned).

I had to resort to the debugger.

The problem is that, on route change, Mithril gets back the path URL-encoded, and [this line](https://github.com/lhorie/mithril.js/blob/0fcba673400c9b9e0873ded902261e2fe21bc46c/mithril.js#L1584) which would otherwise find a match, fails. The path must be decoded, I'll have to figure out where that must happen.

**Comment by pygy** [comment]
At least when `m.route.mode === 'search'`, a `decodeURI` of the first argument [here](https://github.com/lhorie/mithril.js/blob/0fcba673400c9b9e0873ded902261e2fe21bc46c/mithril.js#L1645) should do it. Ive yet to check for the other modes.

If correct, I'll send a PR.

**Comment by pygy** [comment]
So far, the route name is encoded with `encodeURI` (not `encodeURIComponent`) everywhere (Chrome, FF, Safari) but Chrome when `m.route.mode` is `'hash'`. With that mode+browser combo, the Codepen works.

le fu.

le clusterfu.

Could someone test what happens with IE?

We don't want to be decoding twice either.

**Comment by lhorie** [comment]
This works in rewrite branch
