### ISSUE TITLE
Discussion: should we be able to stop a redraw with startComputation/endComputation?

### ISSUE THREAD

**Issue by mikegleasonjr** [lhorie/mithril.js#936]
Hello,

I tried the following, it redraws:

```
m.startComputation();
m.redraw.strategy('none');
m.endComputation();
```

Sometimes it is easier to: draw by default and prevent drawing on exception
than to: not draw by default and draw every time except a special case.

Would that break something?

**Comment by isiahmeadows** [comment]
`m.startComputation()` and `m.endComputation()` block the rendering loop to work with external libraries. `m.redraw.strategy("none")` skips the next redraw, but only with *synchronous* ones that are part of the normal lifecycle (e.g. not by `m.redraw()` or `m.request()` either). But in this case, your behavior [is documented and intentional](http://mithril.js.org/mithril.redraw.html#preventing-redraws-on-events).

@lhorie I think you are better to answer this question, as I'm lost as to why this is and/or should be the case.

**Comment by mikegleasonjr** [comment]
Thanks for the follow up!

It seems that the `m.redraw.strategy()` is used only during dom events.

I have several services that emulate "events" and I'm using `m.startComputation()` and `m.endComputation()` to redraw by default. But that way I can't prevent a redraw.

Not using `m.startComputation()` and `m.endComputation()` in my services and letting the client call `m.redraw()` everywhere is a little bit tedious.

The real question is, how can I achieve what I'm describing?!

**Comment by mikegleasonjr** [comment]
After having read the code, I understand why only sync events can prevent a redraw. After a redraw is prevented, the strategy is immediately set back to `diff` so that any other pending request can redraw afterwards.

When doing async stuff, there could be a situation where 3 async calls are overlapping. If the last one would prevent a redraw (when `pendingRequests` reaches 0), nothing would be redrawn. Even if the first two would have liked a redraw.

We could implement something though for async events. Always use code like in `endFirstComputation()` where we meant to do `endComputation()`. But keeping a global flag to determine the most expensive type of redraw needed by all the pending requests (`all` wins over `diff` which wins over `none`). When `pendingRequests` reaches 0 and the strategy is `none` but the global flag is set, we `redraw()` anyway using the proper strategy.

**ex.:**

1. Let's say we use 3 `m.request()` calls at the same time. `pendingRequests` is now 3. The first one resolves and the client calls `m.redraw.strategy('none')`. The global flag has `none`.

2. The second call resolves, the client doesn't change the redraw strategy, it is `diff` by default so the global flag now contains `diff`.

3. The third call resolves, the client set the strategy to `none`. The `pendingRequests` counter reaches `0`. The current strategy tells to not redraw but the global flag contains `diff`, we redraw anyway.

What do you guys think?

**Comment by barneycarroll** [comment]
Thanks for bringing this up and putting due thought into it.

I think the one thing that 'computations' do that nothing else can is to prevent redraw for a duration. Everything else about the API is contentious, often unexpected, and achievable by direct access to other API methods. In my experience most people confused by start / end computation call one after the other synchronously just to trigger a redraw, which gives some indication of how confusing this API space is.

IMO the API should be renamed to something more explicit about what it is for (the relationship between 'computations' and redraws is unintuitive at best), and there should be no opinionated implicit behaviour on resolution — authors are perfectly capable of setting redraw strategy and calling a redraw, synchronous out otherwise, before or after resolution — and as you say, intervening calls to redraw APIs should be intercepted and re-invoked on resolution.

Here's a little proof of concept (the Promise API is something I stick by in all asynch code where possible simply to reduce esoteric API surface and stick to standards that exist elsewhere, but we can ignore that):

```Javascript 
function lockRedraw( resumeRedraw ){
	var redraw   = m.redraw
	var called   = false
	var forced   = false
	var strategy = m.prop()
	
	m.redraw          = function( input ){
		called = true 
		forced = input
	}
	m.redraw.strategy = strategy
	
	return new Promise( resumeRedraw ).then( function(){
		m.redraw = redraw
	
		redraw.strategy( strategy() )
	
		if( called ) redraw( force )
	} )
}
```

This also tracks *whether there were any redraw calls*.

The thing this doesn't do that you're suggesting and sounds intuitive is to give calls for more aggressive strategies and synchronous redraws precedence over later weaker calls.

I can completely understand the logic behind wanting that: if a given action requests a diff or total redraw, then the fact a later action requests a 'none' redraw (the standard method for marking a DOM event handler as no-op) should not supersede the earlier intent. However this isn't how Mithril behaves currently (regardless of computation implementation logic), as demonstrated in this [fiddle](https://jsfiddle.net/barney/zzmzrfc4/) — redraw strategy is a setter function with string validation, nothing more.

At the end of the day, I believe that behaviour is something that should be addressed — if at all — as a separate issue by the redraw strategy API itself, external to the concerns of the redraw lock / computation API — again this falls into the contentious pit of inconsistent implicit behaviour with one API making up for the failings of another, which we desperately need to avoid in order to mitigate further mixed concerns and thwarted expectations.

**Comment by mikegleasonjr** [comment]
Thanks @barneycarroll for you thorough explanation. I too have made some code during the night to test my theory out.

I have a modified `endComputation()` that does what I describe above and **all the tests are passing**:

```
	var pendingRequests = 0;
	var pendingRedrawStrategy = "none";
	m.startComputation = function() { pendingRequests++; };
	m.endComputation = function() {
		if (m.redraw.strategy() === "diff" && pendingRedrawStrategy !== "all") pendingRedrawStrategy = "diff";
		else if (m.redraw.strategy() === "all") pendingRedrawStrategy = "all";

		if (pendingRequests > 1) {
			pendingRequests--;
			m.redraw.strategy("diff");
		} else {
			pendingRequests = 0;
			if (pendingRedrawStrategy !== "none") {
				m.redraw.strategy(pendingRedrawStrategy);
				m.redraw();
			}
			else {
				m.redraw.strategy("diff");
			}
			pendingRedrawStrategy = "none";
		}
	}
```

You should also replace any `endFirstComputation();` calls by the regular `m.endComputation();`

That's it

**Comment by isiahmeadows** [comment]
@mikegleasonjr I think I would like your idea better, although I wouldn't merge it until 0.2.2 gets released (i.e. past `-rc`). It could break for some uncommon cases. Conceptually, it's more consistent, which is almost always better. [1]

[1]: ES5 functions are a case where consistency didn't work, because people got confused over *every* function having its *own* `this`. Hence, ES6 arrow functions.

**Comment by mikegleasonjr** [comment]
Okay I will fork / document / test this feature and submit a PR for the future.

I am very happy with the community here and this project. The library is amazingly small and fast which satisfies all of my OCDs :) I admit the documentation for the corner cases are a little bit scattered here and there and you have to look at the source to understand what's going on but hey, you're only at 0.2.

Can't wait to show you the project I'm working on with Mithril.

**Comment by mikegleasonjr** [comment]
After a discussion on the channel (and despite successfully implementing this feature in a branch), I decided not to pursue this route. I will fork and remove the auto-redrawing system from Mithril altogether and cann `m.redraw` in userland on demand (except on route change, I will keep that in Mithril). I will at the same time get rid of deferreds to save size. I think it should be bring your own if you want to use Promises. If anyone is interested, I can explain my choices somewhere.
