### ISSUE TITLE
Is there any advantage to use m.prop() ?

### ISSUE THREAD

**Issue by whatifif** [lhorie/mithril.js#946]
With Redux, all state can be described as a simple JSON object.

And this JSON object can be used directly in 'view'.

Is there any advantage to use m.prop() ?

**Comment by mikegleasonjr** [comment]
Just a user of the library here. It helps with functional programming. Wherever you can pass a callback to a function, you can then pass a `m.prop` without defining a closure. An example of this can be found here: http://mithril.js.org/mithril.withAttr.html

Also you can't pass by reference ints or strings in javascript so passing a function helps to share a state between components. I agree that sharing a JSON has the same effect but things get more coupled than just a single property that can be anything.

You can use a JSON object as your models also nothing prevents you from doing that. 

I wrote myself some utility functions for properties that have the advantage of producing one liners in my code (to have "computed" properties, properties derived from other properties, without having to define them):

```
// my model
var valid = m.prop(false)
var enabled = m.prop(false)
[...]

// in render
m.component(MyComponent, {
  enabled: props.and(this.valid, this.enabled)
})

// MyComponent will have an enabled property which will
/ /resolve to true only if the parent model is valid and enabled.
// The property is evaluated on each call so the data is always
// current.
```

I have several of those, the each return a "computed" `m.prop`:

- `props.and`
- `props.not`
- `props.equals`
- `props.in`

There are probably far more advantages than the ones I described here, maybe others can chip in so I can learn too :)

**Comment by whatifif** [comment]
Thanks for your detailed explanation.

I think that using directly JSON as model is simpler than converting all it properties into m.prop() if there is no critical reason to use m.prop().

**Comment by isiahmeadows** [comment]
Also, there's the canonical "request a value and store it in a prop", which is very idiomatic for Mithril:

```js
var component = {
  controller: function () {
    this.value = m.prop()
    m.request({method: "GET", url: "/api.json"}).then(this.value)
  },

  view: function (ctrl) {
    return m(".display", [
      m(".value", ctrl.value()),
    ])
  },
}
```

It also makes data binding easier. [Here](https://lhorie.github.io/mithril-blog/asymmetrical-data-bindings.html)'s a post by @lhorie detailing form input. There's other areas, too.

**Comment by barneycarroll** [comment]
@whatifif like @isiahmeadows says, passing writable primitive references, which is most common in forms. Because primitives are immutable in JS, you normally need to pass a reference to the object they are bound to and the key on which they are stored. This gets verbose, clunky, brittle, fast. Functions, on the other hand, can be passed everywhere. They can also be coerced back to their stored value via `toJSON`.

```
view : ( { name } ) =>
  m( 'label', 
    'Name',
    m( 'input', {
      value : name(),
      oninput : m.withAttr( 'value', name )
    } )
  )
```

`m.prop` is especially useful if you're using ES<6, where writing functions is incredibly verbose and drowns out the salient references and structure of a view. In ES6, they're less useful since you can relatively easily write anonymous arrows on the fly:

```
view : model =>
  m( 'label', 
    'Name',
    m( 'input', {
      value : model.name,
      oninput : ( { target : { value } } ) =>
        model.name = input
    } )
  )
```

But you're right — there's no critical reason for this functional virtual DOM idiom stuff. At the end of the day it's all developer ergonomics.
