### ISSUE TITLE
Release candidate minified code raises error when using m.trust

### ISSUE THREAD

**Issue by ArthurClemens** [lhorie/mithril.js#965]
Trying out a newer release than 0.2 I got this browser error when using `m.trust`: "The implementation did not support the requested type of object or operation". In fact it appears that no call to `m.trust` can be used at all, not even `m.trust('<p>hello</p>')`, which certainly should have been noticed by others...

I have tried both `0.2.2-rc.1` and the latest commit. My package.json:

    "mithril": "0.2.2-rc.1"

and 

    "mithril": "git+https://git@github.com/lhorie/mithril.js.git#8d06cb8142af8730a0181b3e6ff3255ebbaef586"

With more tests I could pinpoint it to the `mithril.min.js` file. Using the non-minified file no error appears, so the bug must be introduced in the minifying process.

**Comment by ArthurClemens** [comment]
I was clearly using an outdated .min file. Could we generated the min file automatically?

**Comment by pygy** [comment]
It would be ideal to test it as well... A pre-version NPM hook that runs uglify, the linter and the test suite would help.

I also use [a `prepublish` hook](https://github.com/j2css/j2c/blob/v1_preview/package.json#L7-L8) to push to github, but it requires the use of a custom `inpublish` package because [that hook runs on `install` too](https://github.com/npm/npm/issues/3059).

Although in this case, it wouldn't have helped since we're at the tip of the dev branch and `npm` doesn't have a say on what happens there... I suppose that a `git` hook would do, but I've never used any.

**Comment by barneycarroll** [comment]
I think it should be taken as read that synchronising the docs, minified files, Typescript defs, etc is not something we can expect to happen on every git commit. Devil's advocate: every commit is in fact a release, and changes each of these things. Using unpublished minified files just strikes me as asking for trouble: we're looking at something that is pretty much labelled as 'might be released, depending on what comes up in testing' (release candidate), and saying "screw the ability to debug, I need to save those 10kb".

Granted, versioning in Mithril (and pretty much every modern JS project in the last 3 years for that matter) is ad-hoc, and I think 'release candidate' is a bit disingenuous in this case because there's no clear strategy of what it would take for a candidate to be promoted to release status (we've always been catching bugs in the wild, and I certainly haven't seen any fundamental change in approach to indicate this won't continue to be the case).

It's a shame Travis integration weren't a bit more clever: it'd be nice, for instance, for there to be a dev branch for Travis to hook into and test on commit, then run procedural tasks like minification on test success, finally committing to next with the results. This way we could rely on a 'safe' branch, make no commitments as to the state of master, and do away with 90% of human error. Doesn't that exist?

**Comment by isiahmeadows** [comment]
It is possible to configure Travis to automatically push the minified
version to GitHub after a successful minified build. It's just not trivial.

Also, if it's only failing in the minified version, I'm pretty sure it's a
bug in uglify-js. Not that we don't have to work around it, though. :-(

**Comment by ArthurClemens** [comment]
It is not in uglify-js. The bug exists in 0.2.2-rc.1, was fixed after that, but that fix was not yet included in the min file (because no new min was built).

**Comment by isiahmeadows** [comment]
Ok. That's also possible. Forgot about that.

**Comment by tivac** [comment]
@ArthurClemens Looks like a new min got built today.

https://github.com/lhorie/mithril.js/commit/f17658e2d35f311897fc0b4b8c11c11a5a7d1c7d

**Comment by lhorie** [comment]
yeah, I just synced to non-minified file
