### ISSUE TITLE
m.redraw adds duplicate content with m.trust (a new case)

### ISSUE THREAD

**Issue by chosroes** [lhorie/mithril.js#981]
Hi,

I have almost the same problem as [issue 721](https://github.com/lhorie/mithril.js/issues/721)
But in my case, when using two identicals m.trust() in the same m():

```javascript
m('div', [
  m.trust('&nbsp;'),
  m('button', 'Button 1'),
  m.trust('&nbsp;'),
  m('button', 'Button 2')
]);
```

When redrawing, it duplicates the html at the end of the parent div.

I use the unicode char instead of the nbsp. But it would be great to fix this anyway.

Thx

**Comment by isiahmeadows** [comment]
PRs welcome. `m.trust()` is pretty buggy ATM.

**Comment by tivac** [comment]
@chosroes I can't repro this in Chrome, Firefox, or Edge. Can you provide some more details?

Here's my attempted repro: https://jsbin.com/siyeci/5/edit?html,js,output

Clicking "Button 1" forces a redraw (note the timestamp changing), but I never see any duplicated content appearing. I changed your `&nbsp;` to a `&copy;` just so it was easier to see in the rendered HTML.

**Comment by isiahmeadows** [comment]
@tivac I don't know if it's related, but [this test](https://github.com/lhorie/mithril.js/blob/next/test/mithril.trust.js#L44-L55) is intentionally disabled because it literally renders `12<td>foo</td>`, not `<td>1</td><td>2</td><td>foo</td>` like it's supposed to. Mithril's literally sanitizing trusted HTML when it's supposed to *trust* it and leave it as-is.

**Comment by tivac** [comment]
@isiahmeadows It's because it used `appendTextFragment()`, and that looks to strip out any tags.

https://jsbin.com/xopobipese/1/edit?html,js,output

https://github.com/lhorie/mithril.js/blob/next/mithril.js#L1137-L1144

it made that choice because of this line in the `injectHTML()` method:

https://github.com/lhorie/mithril.js/blob/next/mithril.js#L1148

Did the functionality of `injectHTML()` change? It's possible I'm misreading it but it doesn't look like it would work atm...

**Comment by isiahmeadows** [comment]
1. I'm aware that's the current behavior. I think I mentioned that above
the test as well.
2. That function (`appendTextFragment`) should *not* be stripping anything.

**Comment by tivac** [comment]
Sorry, wrong JSBin link.

https://jsbin.com/wuvola/1/edit?js,output

Shows that `document.createRange().createContextualFragment(...)` as used in `appendTextFragment` definitely strips HTML.

**Comment by isiahmeadows** [comment]
Ok. I misread things, then...damn it :frowning:

**Comment by isiahmeadows** [comment]
@tivac What's the difference between your example and [this](http://pagedemos.com/str2fragment/)? They look way too similar to me (mod you using `querySelectorAll()`, but changing that to `getElementById()` didn't change anything) to figure out what's going wrong with the approach.

**Comment by tivac** [comment]
Looks like it does some filtering and only accepts valid HTML? Modified it from using random `<td>` and it appears to be fine.

https://jsbin.com/wuvola/2/edit?js,output

So I guess this is still a no-repro as far as I can see. Need @chosroes to chime in w/ more details.

**Comment by isiahmeadows** [comment]
I'm guessing it's that the `<tr>` and `<td>` tags are being wholly ignored because they're not in a table. Seems like yet another HTML gotcha (and test bug...:frowning:).

**Comment by tivac** [comment]
Closing due to lack of movement.
