### ISSUE TITLE
Rendering background-image url

### ISSUE THREAD

**Issue by hiranpodi** [lhorie/mithril.js#996]
Image is displaye propely when it is a proper img tag

`<img src="images/erp/C:%5CProgram%20Files%20(x86)%5CMYTEST%5Cbitmaps%5C10001.jpg"  class="scale">`

But same image not rendered at all when it is set as  background-image url

`background-image: url("images/erp/C:%5CProgram%20Files%20(x86)%5CMYTEST%5Cbitmaps%5C10001.jpg");`

The issue seems to be exist when the image path contain "C:"

**Comment by isiahmeadows** [comment]
Could I get a code snippet and/or fiddle/pen/etc.?

**Comment by hiranpodi** [comment]
HTML page

```
<html>
<body>
<script src="mithril.min.js"></script>

<script>


var app = {
  // model
  name: m.prop('John'),

  // app
  controller: function () {
  
  },

  view: function (ctrl) {
    return [m("button", [m("img[src='C:\\Temp\\mith\\field.png\']"),"xxxx"]),
	m("div", {'style': { 'background-image' : 'url(\"field.png\")'}},"yyyy"),
	m("div", {'style': { 'background-image' : 'url(\"C:\\Temp\\mith\\field.png\")'}},"zzzz")];
  }
};

m.module(document.body, app);

</script>


</body>
</html>
```


This is the DOM 


```
<html>
<head></head>
<body>
<button><img src="C:\Temp\mith\field.png">xxxx</button>
<div style="background-image: url(&quot;field.png&quot;);">yyyy</div>
<div style="background-image: url(&quot;C:Tempmith\f ield.png&quot;);">zzzz</div>
</body></html>
```

You can see

**C:\Temp\mith\field.png** is converted into **"C:Tempmith\f ield.png"**

This suggest something wrong in the **regex **that converts background url

**Comment by hiranpodi** [comment]
@isiahmeadows Please let me know if you want the above files

**Comment by isiahmeadows** [comment]
Mithril *should* be leaving those alone, unaltered.

[Here's a pen for that.](http://codepen.io/isiahmeadows/pen/vGJaRj?editors=0010)

**Comment by surfmuggle** [comment]
Based on your sample it was not easy to see the bug. Is the path to field.png valid? How if i [fork your pen ](http://codepen.io/anon/pen/GZvwyB?editors=0010)

**Comment by cundy** [comment]
One thing that could be happening. Why to use local machine absolute path on src images or similar ? It would be a security vulnerability if the client could request local file system files and then use JavaScript to figure out what's in them. I'm not completely sure but it seems that firefox and IE have extensions to access local resources, but Chrome is more restrictive. I hope it helps.

**Comment by isiahmeadows** [comment]
@cundy I largely agree with that sentiment. My stance is that it's generally a bad idea, but it's not the library's responsibility to prevent legitimate use cases on the premise of potential sheer stupidity.

@hiranpodi Try this snippet. If it works, it may be because the backslashes are being escaped twice, once by the DOM and once by CSS.

```js
<html>
<body>
<script src="mithril.min.js"></script>
<script>
var app = {
  view: function (ctrl) {
    return [m("button", [m("img[src='C:\\\\Temp\\\\mith\\\\field.png\']"),"xxxx"]),
    m("div", {'style': { 'background-image' : 'url(\"field.png\")'}},"yyyy"),
    m("div", {'style': { 'background-image' : 'url(\"C:\\\\Temp\\\\mith\\\\field.png\")'}},"zzzz")];
  }
};

m.module(document.body, app);
</script>
</body>
</html>
```

Another reason why Windows file paths suck, BTW.

**Comment by hiranpodi** [comment]
Local file path is given in the example is to prove that mithril is interfering with the url. My poit is mithril shouldn't amend/loose anything from the image url.

The real issue is as I have described originally where "c:" exist in a url which is not a local path, it is just a valid url in one of our web servers.

**Comment by isiahmeadows** [comment]
@hiranpodi Try that above snippet. I'd like to see if it actually works as intended, since [this pen](http://codepen.io/anon/pen/dMdVXK?editors=0010) seems to show it correctly escapes the URL (you'll have to inspect the iframe element in the bottom).

**Comment by lhorie** [comment]
Ook, so this one is a bizarre one to explain.

If you have a css property that contains a string such as `url("\fc")`, the backslash initiates a unicode escape sequence, so in my example `\fc` becomes `ü`. Invalid escape sequence do weird things. So to get a backslash value in that string, you need to type a double backslash. BUT, since the css property string is itself in a javascript string, the double backslash needs to be doubled again. So you need the string to be `'url(\"C:\\\\Temp\\\\mith\\\\field.png\")'` as @isiahmeadows mentioned

So the behavior in OP is not specific to mithril and actually correctly. You can verify that this is a browser behavior by setting document.body.style.backgroundImage via console in any browser.
